### ISSUE TITLE
Precompile to ES5?

### ISSUE THREAD

**Issue by kjakobson** [euvl/vue-js-modal#1]
Hi, could you please precompile index.js to ES5? I would really like to use your plugin, but I don't want to change Babel settings in webpack (that is, include **node_modules** folder in settings).

**Comment by euvl** [comment]
@kjakobson sure, i will do it on these weekends if thats ok.

**Comment by euvl** [comment]
Done

**Comment by euvl** [comment]
@kjakobson done
