### ISSUE TITLE
Scrolling modal like Semantic UI?

### ISSUE THREAD

**Issue by nilsi** [euvl/vue-js-modal#10]
Hi,

This modal looks great! However, I wonder if I can achieve something like Semantic UIs scrolling modals:
https://semantic-ui.com/modules/modal.html#/examples

Where the modal resizes according to the content and makes the whole window scrollable? 

Thanks

**Comment by euvl** [comment]
@nilsi it's a good idea, i do not really have bandwidth currently to do it, but i will definitely will look into it later for the future.

**Comment by denjaland** [comment]
Just wanted to add a +1 on this one.
We need a way to have the width and height auto-calculated based on content.  Since we are using the modal to host a wizard, the content height can change during wizard, and now it simply falls off the modal.

I very much like the plugin though!

**Comment by euvl** [comment]
Yeah it is nice idea, when i was doing a plugin my concern was correct positioning and manual resizing. Thats why always should have height specified...

I will try to look into it, but if you guys want to hack something up which does not break other functionality I will gladly accept PR :D

**Comment by nilsi** [comment]
Thanks, when I have time I might look into it but for now Im using semantics. Would gladly change to this one though because it feels much faster overall.

**Comment by euvl** [comment]
Hey @nilsi, @denjaland,

I have finally added `height="auto"` flag & `scrollable` content, if you are using the component, please take a look here:

https://github.com/euvl/vue-js-modal#height-auto
