### ISSUE TITLE
Cannot access to refs on opened event

### ISSUE THREAD

**Issue by saeedvaziry** [euvl/vue-js-modal#102]
I want to access to refs after modal opened but i get undefined...

*this is my code :* 

    <template>
        <div>
            <modal name="avatar" width="500" v-on:opened="opened">
                <div ref="div"></div>
            </modal>
        </div>
    </template>

    <script>
    .
    .
    .
    methods: {
        opened: funciton(){
            console.log(this.$refs.div); // undefined
        }
    }
    .
    .
    .
    </script>

**Comment by saeedvaziry** [comment]
???

**Comment by euvl** [comment]
!!!

**Comment by euvl** [comment]
This was fixed in `1.3.2`
