### ISSUE TITLE
How to remain content when opening after closing?

### ISSUE THREAD

**Issue by leadream** [euvl/vue-js-modal#103]
Hi, thanks for your work at first.

I'm using this plugin in my website, but there is a problem trapped me. I put a form in the modal, so I want the modal to remain content filled by users when they reopen it after closing.

How can I achieve it or Any tips? thank you.

**Comment by euvl** [comment]
Hey @leadream, thanks! 
You will have to store your data somewhere (vuex, localstorage, sessionstorage or just in variable) on `beforeClose` event and restore it on `beforeOpen` event.

**Comment by shreyanshpanchal** [comment]
This is a very important issue.
If i send a PR fixing this? Any chance of acceptance?

**Comment by euvl** [comment]
sure, create pr and i am happy to review it
