### ISSUE TITLE
PivotX and PivotY documentaiton has inversed examples

### ISSUE THREAD

**Issue by muresanandrei1** [euvl/vue-js-modal#104]
It says "(50% from top)" for pivotX and "(50% from left)" for pivotY, isn't it the other way around?

**Comment by euvl** [comment]
Yep ty

**Comment by euvl** [comment]
Fixed

**Comment by muresanandrei1** [comment]
Good luck and thanks for the awesome modal!

**Comment by euvl** [comment]
Thanks 👍 😄
