### ISSUE TITLE
Props as String, while Numbers expected

### ISSUE THREAD

**Issue by onekiloparsec** [euvl/vue-js-modal#11]
Hi. When trying to set width and height of the modal (even if it works fine anyway!), one gets a bunch of errors saying height and width props as passed as String rather than Number. Changing the declaration of the modal with or without quotation marks has no effect. My current declaration:

`<modal name="sites-list" width=800 height=500>`

The errors:

<img width="668" alt="screen shot 2017-05-01 at 12 11 55" src="https://cloud.githubusercontent.com/assets/226224/25577610/b544b04a-2e67-11e7-876d-fdf5c5273751.png">

I'll be happy to help with a PR, but I am unsure on where to start.

**Comment by euvl** [comment]
Hey @onekiloparsec, try binding width and height as numeric values, eg:
`<modal v-bind:width="800" v-bind:height="600">`

or a shortcut:

`<modal :width="800" :height="600">`

Check out this doc, it describes the issue you've had:
https://vuejs.org/v2/guide/components.html#Literal-vs-Dynamic

Lemme know if you will have any more questions 😄 👍

**Comment by onekiloparsec** [comment]
Oh, is that so much visible I'm a newbie in Vuejs?... Damn. Thanks a lot for the quick reply!
