### ISSUE TITLE
CSS missing when using SSR?

### ISSUE THREAD

**Issue by abattenburg** [euvl/vue-js-modal#110]
When using the regular distribution (`import VModal from 'vue-js-modal'`) and setting my nuxt.config.js file to not use SSR (`plugins:  { src: '~plugins/vue-js-modal', ssr: false }]`), everything works correctly. 

However when I try to use the SSR distribution `(import VModal from 'vue-js-modal/dist/ssr.index')` none of the CSS is applied. Is there CSS that needs to be included in the nuxt.config?

**Comment by euvl** [comment]
Hey @abattenburg,

It seemed to work when i tested it last time (like 3 month ago, lol). 
I ll take a look, thanks for reporting this 👍

**Comment by abattenburg** [comment]
Hm, I'll try it on a new project myself and see if maybe something on my project is interfering with the CSS? My other plugins seem to be working fine, but if you don't see an issue with how I'm adding the plugin I'll do further testing. Thanks for taking a look at this!

**Comment by euvl** [comment]
Hey, so did you manage to find out what was the problem?

**Comment by abattenburg** [comment]
@euvl, sorry to get back to you late! After testing it on fresh projects, this doesn't seem to be an issue.

I had the issue with three different Nuxt projects of my own, but I was never able to figure out what it is about my projects that causes the issue. Thanks for taking a look and sorry I jumped the gun on posting this. I'll update this if I'm ever able to figure out whats wrong, but for now the regular distribution is working fine for me. Thanks for all your work creating this component!

**Comment by 0pt1m1z3r** [comment]
Hi @euvl. I'll try to explain the problem that I just found.

Styles of vue-js-modal are in the JS file. They are added as a `style` tag after the styles of my project. I need to use "root" class to override vue-js-modal styles: `.App .v--modal-overlay {...}`.

It's a good idea to split js and css into separate files. Then I can add vue-js-modal styles to my css bundle (`css` option in `nuxt.config.js`).

**Comment by euvl** [comment]
@0pt1m1z3r hey, and the problem in using `.App .v--modal-overlay {...}` is..?

**Comment by 0pt1m1z3r** [comment]
@euvl the main problem that I can't put vue-js-modal styles in my css bandle. And of course I want use just `.v--modal-overlay {...}` without `.App`.

**Comment by euvl** [comment]
Did you try just using `classes` prop?

**Comment by 0pt1m1z3r** [comment]
Yes, of course :)
I use custom component-wrapper for modals with `:classes="['v--modal', 'uikit-modal', params.class]"`. In `.uikit-modal` I set custom styles.

When I open page rendered by SSR vue-js-modal add styles after my css bundle and overlaps my 
`.uikit-modal` styles.

```html
<style type="text/css">
/* nuxt css bundle with my styles */
.uikit-modal {...}
</style>

...

<style type="text/css">
/* vue-js-modal styles */
.v--modal-overlay {...}
.v--modal {...}
...
</style>
```

**Comment by euvl** [comment]
Understood, makes sense. I will add a build target with separate js/css target 👍 Thanks for explanation 👍 😄
