### ISSUE TITLE
v-dialog doesn't work with custom componentName

### ISSUE THREAD

**Issue by vesper8** [euvl/vue-js-modal#112]
Since I am already using another modal in my project, I wished to use the componentName to rename it to foo-modal for example

This works well but it doesn't work in combination with dialog: true

I then get this error
```
[Vue warn]: Unknown custom element: <modal> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Dialog> at /Users/yev/Projects/vue/vue-js-modal/src/Dialog.vue
       <Root>
```

On a side note, I never understood why a lot of vue packages include references to the original developer's paths.. yet they still work despite that
`/Users/yev/Projects/vue/vue-js-modal/src/Dialog.vue`

I also want to mention that I was following along the docs and had initially put the wrong `<dialog/>`

In the medium changelog the 1.28 entry mentions `<dialog/>`. I could swear I found this docs somewhere else as well but can't find it now.

In the github docs I saw the real name is `<v-dialog />`

**Comment by euvl** [comment]
Hi @vesper8,

Yes the name is `<v-dialog/>`, i've changed it at some point because `<dialog>` is an actual HTML element name.

**Comment by euvl** [comment]
> On a side note, I never understood why a lot of vue packages include references to the original developer's paths.. yet they still work despite that  /Users/yev/Projects/vue/vue-js-modal/src/Dialog.vue

Thats something webpack does when bundles the code. Have no idea tbh 😄 😄 😄

**Comment by mattwmj** [comment]
Is this bug fixed?

After I add componentName dialog won't work.

main.js:

Vue.use(VModal, {
    componentName: "v-modal",
    dialog: true
})

vue template:
        <v-modal name="update">
            <div style="margin: 5px">
                Test
            </div>
        </v-modal>
        <v-dialog/>

show dialog:

showDialog() {
                this.$modal.show('dialog', {
                    title: 'Alert!',
                    text: 'You are too awesome',
                    buttons: [
                        {
                            title: 'Deal with it',
                            handler: () => {
                                alert('Woot!')
                            }
                        },
                        {
                            title: '',       // Button title
                            default: true,    // Will be triggered by default if 'Enter' pressed.
                            handler: () => {
                            } // Button click handler
                        },
                        {
                            title: 'Close'
                        }
                    ]
                });
            }

**Comment by belgarad** [comment]
this cause usually if you have more then one <v-dialog/> in your page. 

i tried to use it locally in component lvl. In this way i got this name error time to time.

so i moved <v-dialog/> to my root element. this time it works perfectly

**Comment by euvl** [comment]
@belgarad , if you are refering to v-dialog, it's a singleton - you need just one per virtual dom tree.

**Comment by belgarad** [comment]
@euvl yes, it was mistake i didnt notice that earlier. i used it as component level first. but i didnt think those components can join in same dom. in time couple v-dialog was in same dom. that cause name bug problem. so i moved to root. after that your plugin working perfect. its easy to use and flexible.
