### ISSUE TITLE
scrollable with height value other than auto ?

### ISSUE THREAD

**Issue by vesper8** [euvl/vue-js-modal#113]
Trying to get my modal, who's content is very long, to fit in a scrollable modal. Currently the only way I can get this to work is by using scrollable=true and height=auto

what I really want is something like height=70% to give it some breathing room

right now it just stretches the entire page vertically

I was able to make this slightly better by adding a margin: 8em 0; on .v--modal, this creates the breathing space I want at the top and then again at the bottom once you've scrolled all the way to the bottom.

I understand this is a current limitation and as of yet I do not have a PR to propose, but since this seems to be a hot issue I wanted to see if anyone has a good workaround

Thanks

**Comment by euvl** [comment]
Hey @vesper8,

You can try setting `height="70%"` and set `overflow:auto` to your content.

https://www.w3schools.com/cssref/playit.asp?filename=playcss_overflow&preval=auto
