### ISSUE TITLE
Prevent content from reloading?

### ISSUE THREAD

**Issue by Kinosnai** [euvl/vue-js-modal#114]
I was wondering if there is any way to prevent this modal to re-render the content of the box everytime the $modal.show function is called? I mean, make the content persistent so if I reopen (call $modal.show a second time) I dont "lose" the changes I made in the content from the past call?

Thanks for your help :)

**Comment by euvl** [comment]
Hey @Kinosnai,

I am afraid its not possible, component will be destroyed when you do `hide` and "recreated" again when you do `show`. 

A good workaround will be to cache all the information from your modal on `beforeClose` event and restore it on `beforeOpen` event (you can pass params when you do `show`, pretty sure there are some examples in demos 👍 )

**Comment by Kinosnai** [comment]
Thanks Evul, already created a vanilla javascript modal for what I was trying to acomplish. It was simplier than I thought. 
I will use your modal for other things I need to do on the same project anyway ;)

**Comment by euvl** [comment]
Great, thanks for using the plugin 😄 !
