### ISSUE TITLE
slots not working?

### ISSUE THREAD

**Issue by Kinosnai** [euvl/vue-js-modal#115]
Hey again. I dont know if I am doing something wrong here but im following this example and can't get it to work.
```
<modal name="foo">

    <div slot="top-right">
      <button @click="$modal.hide('foo')">
        ❌
      </button>
    </div>

    Hello, ☀️!

</modal>

```
of course I have a button to open the dialog but the X is not showing. Don't know if this might be a "slots" problem.

Any advice on this?

**Comment by euvl** [comment]
Hi @Kinosnai,

Your code looks correct to me, can you take a look in this example which seems to work: 

https://github.com/euvl/vue-js-modal/blob/master/demo/client_side_rendering/src/components/DogProfileModal.vue

It's also on the demo site, if you can't see `HIDE THE DOGGY` button then it's clearly a bug.

**Comment by euvl** [comment]
As no further comment, I assume its all good now
