### ISSUE TITLE
beforeOpen is executed twice when modal is closed ,only in mobile

### ISSUE THREAD

**Issue by ZhiRuYan** [euvl/vue-js-modal#117]
I use the demo 'demo-login'  and I find that:
![image](https://user-images.githubusercontent.com/22111417/32088784-99643a06-bb18-11e7-97fa-58b4dcb4667d.png)
It will only be produced on the mobile side，thanks for your help!

**Comment by arranf** [comment]
This causes `v--modal-block-scroll` to be added to the body even after modal exit.

**Comment by euvl** [comment]
weird.

**Comment by defnull** [comment]
Not only on Mobile. I triggered this (or a similar) bug with Firefox (#122).

**Comment by kezek** [comment]
Can confirm I'm having the same bug as well (on all platforms , Chrome and Firefox). Not doing anything fancy. It's duplicated on both closed and before-close events.

**Comment by euvl** [comment]
yeah, there is some handler that is executed twice. I can't really spot were the bug is >_<

**Comment by euvl** [comment]
I've made some changes that might fix this. 

p.s. demo site currently has older version. test in your projects.

**Comment by giraz82** [comment]
I'm seeing this behavior  still in 1.3.9.
Sequence of logged events, opening and closing a dialog, is:

1. before-open
2. opened
3. before-close
4. closed
5. before-open

In this way `v--modal-block-scroll` is readded to the body.
