### ISSUE TITLE
How do I use the data from beforeOpen in my template?

### ISSUE THREAD

**Issue by matbz** [euvl/vue-js-modal#119]
My modal is located in my parent component

I want to call this modal with dynamic data from child components. How do I use the data I get in beforeOpen in my template like with data/computed properties?

Also it seems the function beforeOpen gets called from the parent component once - even when I don't call the modal.

Thank you for your help!

**Comment by euvl** [comment]
hey, check `ConditionalModal` demo, might be useful, you can use `params` in event.
