### ISSUE TITLE
How to use events?

### ISSUE THREAD

**Issue by hkhandare** [euvl/vue-js-modal#12]

**Comment by euvl** [comment]
Basic example:

```
<modal name="foo" @before-open="beforeOpen" @before-close="beforeClose"/>
...

methods: {
  before-open (event) {
     console.log(event)
  }
}
```

Also take a look in demo pls.

**Comment by hkhandare** [comment]
Thank you very much.
I couldn't find it in the demo or readme though.

**Comment by euvl** [comment]
No problem, I will add an example to readme :) 

Also take a look here: https://github.com/euvl/vue-js-modal/blob/master/demo/src/components/DemoErrorModal.vue

This is an example where "close" event is prevented if the condition is not met.
To quickly see how it works, click "Demo: Error handling" button at http://vue-js-modal.yev.io/

And thanks for using plugin :)

**Comment by hkhandare** [comment]
This was my next question actually :)
Thank you very much once again.
