### ISSUE TITLE
Please add a background-color property

### ISSUE THREAD

**Issue by ianengelbrecht** [euvl/vue-js-modal#121]
The modal background is currently dark grey (probably 50% grey or similar I guess). It would be nice if this could be set as a prop. Sometimes only a very slight grey, or another color, is required.

**Comment by euvl** [comment]
You can do it through css (check docs).

**Comment by euvl** [comment]
https://github.com/euvl/vue-js-modal#overlay-background-color

**Comment by ianengelbrecht** [comment]
Thank you very much, I should have seen it there!

**Comment by euvl** [comment]
No problem 😄
