### ISSUE TITLE
`body.v--modal-block-scroll` not removed after modal is closed.

### ISSUE THREAD

**Issue by defnull** [euvl/vue-js-modal#122]
`body.v--modal-block-scroll` is not removed after a scrollable modal is closed. This prevents scrolling for the entire page (`overflow: hidden` on `body`).

**Comment by euvl** [comment]
hi, send over some code pls. 
seems to work fine on test site.

**Comment by arranf** [comment]
This is this issue https://github.com/euvl/vue-js-modal/issues/117

**Comment by defnull** [comment]
The demo (test) site does not have a scrollable example, so it is not an issue there.

**Comment by euvl** [comment]
I think this one was fixed already
