### ISSUE TITLE
when modal is defined as a child component, events aren't emitted to parent component

### ISSUE THREAD

**Issue by egeersoz** [euvl/vue-js-modal#123]
I have the modal defined in a separate, single-file component:

```
<template>
  <div>
    <modal name="new-task-modal">
      ...stuff
    </modal>
  </div>
</template>

<script>
export default {
  name: 'NewTaskModal',
  // ...
}
</script>
```

The parent component:

```
<template>
  <div>
    <new-task-modal
      @beforeOpen="modalBeforeOpen"
      @opened="modalOpened" />
    <button v-on:click="showNewTaskForm()">New Task</button>
  </div>
</template>

<script>
import NewTaskModal from "../subcomponents/NewTaskModal.vue"
export default {
  components: {
    NewTaskModal
  },
  methods: {
    showNewTaskForm() {
      this.$modal.show('new-task-modal')
    },
    modalOpened(event) {
      console.log("opened)
    },
    modalBeforeOpen(event) {
      console.log("beforeOpen")
    }
  }
}
</script>
```

The `showNewTaskForm()` method correctly displays the modal. However, the events don't trigger. I need them to trigger because I have an `input` element inside the modal that I want to focus when the modal is opened.

**Comment by euvl** [comment]
And they should not, thats how Vue works.

https://github.com/vuejs/vue/issues/3994

**Comment by egeersoz** [comment]
The commenter there says "You'll have to re-emit it in ComponentB."

How/when do I re-emit the event inside my modal component?

**Comment by egeersoz** [comment]
Never mind, I was defining the `@opened` callbacks in the wrong place.
