### ISSUE TITLE
invalid expression when setting with property

### ISSUE THREAD

**Issue by franmadj** [euvl/vue-js-modal#127]
also scrollable dose not seem to do anything

```
      <modal name="showPost" @before-open="beforeOpen" :resizable="true" :scrollable="true" :adaptive="true" :delay="4" :width="50%" >

          <h1>{{modalTitle}}</h1>
          <span >{{modalDate}}</span>
          <p>{{modalContent}}</p>
          <img v-if="modalImage" v-bind:src="modalImage">
      </modal>
```

>   - invalid expression: Unexpected token } in
> 
>     50%
> 
>   Raw expression: :width="50%"

**Comment by euvl** [comment]
It should be either width=“50%” or :width=“‘50%’” - its just how binding in Vue works , nothing to do with the plugin. 

Im pretty sure that scrollable works :DD
