### ISSUE TITLE
Auto height instead of fixed?

### ISSUE THREAD

**Issue by a3020** [euvl/vue-js-modal#13]
Nice plugin. It seems to work well in vue 2.

Question: does it support `auto: height`? I've tried setting the property, but it defaults back to 300.

![auto-height](https://cloud.githubusercontent.com/assets/1431100/25837396/f319878e-348d-11e7-8f27-903dd48638e7.PNG)

**Comment by euvl** [comment]
Currently you must explicitly set `height`, default is 300 (`... :height="200"`). 
Auto height was breaking the positioning and resizing code when i was writing it :)

**Comment by euvl** [comment]
Hey @a3020,

I have finally added `height="auto"` & scrollable content, if you are using the component, please take a look here:

https://github.com/euvl/vue-js-modal#height-auto
