### ISSUE TITLE
Scrollbar width portion blocking modal

### ISSUE THREAD

**Issue by Glidias** [euvl/vue-js-modal#131]
When resize window down, scrollbar width portion blocks modal. It seems the calculated screen width excludes the scrollbar.

**Comment by euvl** [comment]
Can you send a screenshot pls

**Comment by Glidias** [comment]
![image](https://user-images.githubusercontent.com/190195/32887020-813362f0-cafd-11e7-96e1-b9584e301f43.png)

I had to resort to some stuff like

    .v--modal-overlay {
    	width:100% !important;
    }

instead of `100vw` width and force set adapative `v--model` width to `100%` to conform to parent width.

**Comment by euvl** [comment]
Cool, thanks for pointing this out. I will change it in next release.

**Comment by euvl** [comment]
I think this will be fixed by a pull request that i have not published yet, ill let you know when to test 👍  😄

**Comment by euvl** [comment]
hey, it should be fixed in 1.3.7, will publish it tomorrow
