### ISSUE TITLE
Poor documentation?

### ISSUE THREAD

**Issue by ghost** [euvl/vue-js-modal#132]
I might be dumb here but I dont understand the example page at all (http://vue-js-modal.yev.io/)

Where are the code examples? I can't just look at the DOM? 

I'm trying to show a modal from a .vue-file with a custom text message. Nothing more. Should be really easy but can't find any example.

I installed this to make it easy to show a simple modal window but so far it's easier to just implement my own solution. Am I missing something?

**Comment by euvl** [comment]
Emm, write better. 

Code examples are in demos folder obviously, also there is readme. 

```
I installed this to make it easy to show a simple modal window but so far it's easier to just implement my own solution. 
```

Go for it.

**Comment by jzucadi** [comment]
Yea but we are talking about a FREE library of code that SOMEONE ELSE handed to you.

**Comment by RicardoRamirezR** [comment]
PRs are welcome
