### ISSUE TITLE
Overlay is contained inside another component instead of covering the whole screen?

### ISSUE THREAD

**Issue by matbz** [euvl/vue-js-modal#134]
Hi,

I really like this project but I have one problem at the moment. 

I have a two column layout: sidebar, content.

In my content I render table items and on each item you can click and a modal should appear with actions. My problem: The overlay is contained inside the content div and doesn't cover the whole page.

Is there a fix for it? Thanks!

**Comment by matbz** [comment]
The problem was that my container had a higher z-index, sorry about that.

**Comment by npaslaru** [comment]
I also have the same issue. I am a noob to frontend development and I can't figure out what's wrong.

![print-screen](https://user-images.githubusercontent.com/31691171/34882791-5276a036-f7c0-11e7-88b8-7ff40eb239cf.png)
