### ISSUE TITLE
Repo's version is 1.3.5, npm has 1.3.4

### ISSUE THREAD

**Issue by ispal** [euvl/vue-js-modal#136]
Looking for the ESC key support that was added to 1.3.5 I think. Can you publish that?

[https://github.com/euvl/vue-js-modal/commit/7d66dc9d8c2a3f088e36d6daeb3c40159fe729ea](https://github.com/euvl/vue-js-modal/commit/7d66dc9d8c2a3f088e36d6daeb3c40159fe729ea)

**Comment by euvl** [comment]
Will do whenever I'll get my laptop back 😄

**Comment by ispal** [comment]
Sounds interesting 😄

**Comment by euvl** [comment]
done
