### ISSUE TITLE
Modal's styles mess around with page when using scrollable=true

### ISSUE THREAD

**Issue by haffla** [euvl/vue-js-modal#140]
First, thanks for this component. Works great!

But:
When using scrollable=true, everytime I open the modal the content of the page behind jumps a little. In fact the page is wider when the modal is opened and this causes a reflow of the content. It's quite annoying as the opening (and closing) does not look smooth.

Edit: Just noticed that it is because my page is higher than my screen, so there is a scrollbar. When you open the modal the scrollbar disappears and thus the page widens. Seems you are setting overflow: hidden somewhere that effects the page?

**Comment by euvl** [comment]
yes, otherwise "scrollabe" cant be scrollable :)

**Comment by haffla** [comment]
Ah OK I understand the feature now. I'm gonna go for fixed height and scrolling inside the modal then. Thanks!
