### ISSUE TITLE
The modal width prop is not reactive

### ISSUE THREAD

**Issue by catalinbuletin** [euvl/vue-js-modal#141]
Hi,

First of all, thanks for the awesome work.

I got an issue where I try to modify the modal `width` parameter after it has been mounted.

I have a wrapper component on the actual modal where I have a `width` data property. I pass this property on the modal component. I would expect that anytime the width prop changes on the wrapper, to be picked up by the modal as well, and trigger a resize.

My wrapper component in short:

    <template>
        <v-modal :name="name" :width="width">
            <slot></slot>
        </v-modal>
    </template>

    <script>

    export default {
        props: {
            name: {
                type: String,
                required: true
            }
        },

        data() {
            return {
                width: "45%",
          
            }
        },

        methods: {
          
            opened(event) {
                this.resizeHandler()
                window.addEventListener('resize', _.debounce(this.resizeHandler, 50))
                this.$emit('modal-opened', event)
            },

            beforeClose(event) {
                window.removeEventListener('resize', _.debounce(this.resizeHandler, 50))
                this.$emit('before-close', event)
            },

            resizeHandler() {
              
                if ($(window).width() <= App.getResponsiveBreakpoint('sm')) {
                    this.width = '100%'
                }
                if ($(window).width() > App.getResponsiveBreakpoint('sm') && $(window).width() <= App.getResponsiveBreakpoint('md')) {
                    this.width = '65%'
                }
                if ($(window).width() > App.getResponsiveBreakpoint('md')) {
                    this.width = '45%'
                }
            }
        },
    }

    </script> 

Maybe something I'm doing wrong?

Thanks in advance!

**Comment by silrage** [comment]
Hi, this module was very cool. Thank you!
A similar problem when we call the modal window:

In template

`<modals-container class="big-height-container"  />`

When mounted

`this.$modal.show({
  template: <div class="big-height-box">Very big</div>
})`


I tried to throw the parameter height. This only worked this.$parent.modal.height = 500. But this is not reactive :grimacing:

**Comment by catalinbuletin** [comment]
@silrage It looks like the width prop will stay non-reactive. 

@euvl answered to a similar issue a few weeks ago: [#185](https://github.com/euvl/vue-js-modal/issues/185)

**Comment by DelfsEngineering** [comment]
Fix:
This can be simply resolved by ensuring Vue does not reuse the component.
```
<modal 
        :key="componentKey"
        ...

showCardModal: function() {
          this.componentKey++
          ...
```
or you could use a random etc. Basically this changes the key each time it's drawn and triggers the mounted hooks etc to run recalculating numbers.

Thanks for a great component!

**Comment by wtchen** [comment]
> Fix:
> This can be simply resolved by ensuring Vue does not reuse the component.
> 
> ```
> <modal 
>         :key="componentKey"
>         ...
> 
> showCardModal: function() {
>           this.componentKey++
>           ...
> ```
> 
> or you could use a random etc. Basically this changes the key each time it's drawn and triggers the mounted hooks etc to run recalculating numbers.
> 
> Thanks for a great component!

This isn't really a good solution because it causes the modal to rerender, basically closing it

**Comment by kaevupoiss** [comment]
There is a workaround.

Use width for setting the max width you would need and max-width to toggle the actual width changes.
