### ISSUE TITLE
Multiple Modals - Close with escape?

### ISSUE THREAD

**Issue by matbz** [euvl/vue-js-modal#144]
I have multiple modals on a page which gets activated onclick. How can implement a close on Escape for the currently open modal? Thanks!

**Comment by euvl** [comment]
A close on escape should be working in the latest version as far as i know

**Comment by matbz** [comment]
That's great to hear! Could you give me a hint on how to implement this with vue-js-modal? Thanks!

**Comment by euvl** [comment]
it must work out of the box. `clickToClose` is responsible for this feature (i.e. if you can close modal buy clicking background - you can close it by ESC press too)

**Comment by matbz** [comment]
Works, thanks!
