### ISSUE TITLE
Do not use built-in or reserved HTML elements as component id: Dialog

### ISSUE THREAD

**Issue by ItsLhoudini** [euvl/vue-js-modal#149]
Hi,

on browser's error console appears this message. It sounds strange because I haven't set any component with this ID, so maybe the problem is inside the plugin.

VueJS - 2.5.10

**Comment by euvl** [comment]
what error?

**Comment by ItsLhoudini** [comment]
"Do not use built-in or reserved HTML elements as component id: Dialog"

**Comment by euvl** [comment]
Its about component name. 

The plugin's components called `<v-dialog/> and <modal/>`.
I don't use `dialog` anywhere as far as it is reserved word by HTML's dialog component. 

Check your code for `<dialog/>`

**Comment by ItsLhoudini** [comment]
The problem arrives when using the "dialog: true" option, and there's no custom component name to call (as you correctly said).

My code is simple:

Blade.php
`
<v-dialog></v-dialog>
`

App.js
`
import VModal from 'vue-js-modal'
Vue.use(VModal, {dialog: true});
`

Template.vue
`
this.$modal.show('dialog', {
  text: 'It works',
})
`

If I open VueDevTools on Chrome, the <Dialog> component is present:

 
![image](https://user-images.githubusercontent.com/1861349/34051645-b8397c5c-e1bf-11e7-990d-b725fe634345.png)

Maybe the "naming" problem is this.

**Comment by smelyakov** [comment]
It's definitely component name issue. @euvl do you think we could have the PR merged in?

**Comment by euvl** [comment]
Awesome, thanks @smelyakov 👍
