### ISSUE TITLE
Dynamically set modal width based on client browser resolution

### ISSUE THREAD

**Issue by de-soul** [euvl/vue-js-modal#150]
Hello, i can't set modal width based on client browser resolution.
Here is my code:

```
data() {
 return {
  modalWidth: ''
 }
},
mounted:{
 window.addEventListener('load', this.handleWindowResize)
 window.addEventListener('resize', this.handleWindowResize)
},
methods: {
  handleWindowResize(event) {
    var vm = this
    var windowWidth = event.currentTarget.innerWidth
    var math
    switch (true) {
      case windowWidth > 1280:
        math = windowWidth*40/100
        vm.modalWidth = windowWidth - math
        break
      case windowWidth > 780 && windowWidth < 1280:
        math = windowWidth*30/100
        vm.modalWidth = windowWidth - math
        break
      case windowWidth < 780:
        math = windowWidth*5/100
        vm.modalWidth = windowWidth - math
        break
      }
  },
```

in modal template i binding my calculate value (value calculating correct) that way:

`<modal name="validate-datafile" :width="modalWidth" height="auto" :scrollable="true" :clickToClose="false">`

But in console i see next error:

`[Vue warn]: Invalid prop: custom validator check failed for prop "width".`

This happens because on rendering variable modalWidth no have value. If i set it, no error happens, but on browser resize modal width not applies and modal width not changes.

**Comment by euvl** [comment]
so what stops you from giving it default value? 
ps. why  do you initialise it as a String with '' but then use Numbers? 
pss also if you will take a look in readme - you can use '%'  for width and height.

**Comment by de-soul** [comment]
This is responsible design requirements. In desktop version the modal showns pretty good with % or px width, but in mobile version i cant use the plugin. For example, desktop version looks pretty with 60-70% width. But for mobile version this width is unusable and needed 80-90% as minimum.

**Comment by euvl** [comment]
check this example https://github.com/euvl/vue-js-modal/blob/master/demo/client_side_rendering/src/components/DemoLoginModal.vue

**Comment by joshualyon** [comment]
Since the project structure has changed slightly and euvl's link is no longer valid, here's a commit specific link that might be helpful as a reference (assuming this is what @euvl was referring to):
https://github.com/euvl/vue-js-modal/blob/c8df4a3d3ca608c2d3d08277d0d3a3138eae7a60/demo/client_side_rendering/src/components/modals/DemoLoginModal.vue#L50

**Comment by DenniLa2** [comment]
> Which is dynamically adjusted as needed:
> https://github.com/euvl/vue-js-modal/blob/c8df4a3d3ca608c2d3d08277d0d3a3138eae7a60/demo/client_side_rendering/src/components/modals/DemoLoginModal.vue#L50

if add in created hook code:
`
setTimeout(() => this.modalWidth = 200, 5000)
`
width of modal can't changed. 
So the question remains: how to dynamically change the width of a modal window?

**Comment by zeitlerquintet** [comment]
You can use a dynamic class for classes option to adjust the width dynamically. See example below:

`
<style type="text/css">
.v--modal-overlay[data-modal="search-modal"] .v--modal-box.wide {
        width: 95% !important;
        left: 2.5% !important;
</style>
`

`
<modal height="auto" width="70%" ref="modal-search"
               @opened="afterOpen"
               @before-close="beforeClose" :classes="responsive?'wide':''">
`
`
<script>
...
methods: {
      afterOpen(e) {
                this.calculateWidth();
                window.addEventListener("resize", this.calculateWidth);
        },
       beforeClose() {
                window.removeEventListener("resize", this.calculateWidth);
       },
       calculateWidth(e) {
                this.responsive = window.innerWidth <= 768;
       },
}
...
</script>
`
