### ISSUE TITLE
modal position changing is not smooth

### ISSUE THREAD

**Issue by agoretsky** [euvl/vue-js-modal#151]
Hi,
I have modal with height="auto". I am changing the max-height property of div inside with transition, so modal changing the height too, top-left position of modal updates irregularly and it looks is not good for user. How can I fix it?
Thanks

**Comment by euvl** [comment]
I am afraid browsers do not work like that. 

You are trying to change the value in css , make browser redraw it smoothly. On the other hand - you are saying that javascript library (ie. vue, which is a huge framework itself) mustreact to these changes as quick as the css transition itself...Thats not gonna work. You will have to come up with another solution to your problem.

Have a nice day :)

**Comment by agoretsky** [comment]
@euvl thank you for answer, then it would nice to have option to disable default position control
