### ISSUE TITLE
trouble getting custom transition to work on modal.hide

### ISSUE THREAD

**Issue by vesper8** [euvl/vue-js-modal#154]
So it took me a while to figure out how to get the transitions to work, finally looking inside the Modal.vue revealed the naming used

My custom transition is called "ns-modal-fade" now and it looks like this

```
    .ns-modal-fade-enter {
        -webkit-transform: translate3d(0, -25%, 0);
        transform: translate3d(0, -25%, 0);
    }
    .ns-modal-fade-enter-active {
        -webkit-transition: -webkit-transform .3s ease-out;
        -o-transition:      -o-transform .3s ease-out;
        transition:         transform .3s ease-out;
    }
    .ns-modal-fade-leave-active {
        -webkit-transform: translate3d(0, 0, 0);
        transform: translate3d(0, 0, 0);

        opacity: 0;
        -webkit-transition: opacity .15s linear;
        -o-transition: opacity .15s linear;
        transition: opacity .15s linear;
    }
```

This causes the modal to appear the way I want when you $modal.show(). It slides down from the top and fades in at the same time. Great

But I would like it to do the reverse animation when I close the modal, either with a button or by clicking the overlay.

But it seems no matter what I add, when I close the modal is just fades out and doesn't perform any animation.

Any chance you could clarify how to add a "leaving" animation please?

**Comment by euvl** [comment]
not sure why it used you a lot of time. plugin uses standard vue transitions, nothing new here. 

for clarification go to vuejs documentation...

**Comment by gaetansenn** [comment]
Hi,

@vesper8 @euvl 

I just discovered that the overlay animation need to have the same time as your custom animation.

If you look inside the Modal.vue code you can see that the overlay transition is the parent of the modal transition so if the parent transition is finished before the child transition it will remove the child from the dom before it is finished. You will only see this happen during the leaving transition.

**Comment by pietromanneschi** [comment]
Hello,
resurrecting this post as i'm having the same issue. As @gaetansenn said, the transition on the child part of the modal gets cut because the overlay has this code:

 ```
 <transition name="overlay-fade">
    <div v-if="visibility.overlay"
```

and overlay-fade is defined directly in the single file component Modal.vue :
```
.overlay-fade-enter-active,
.overlay-fade-leave-active {
  transition: all 0.2s;
}

.overlay-fade-enter,
.overlay-fade-leave-active {
  opacity: 0;
}
```
so i can't apply transitions that are longer than 0.2s. Any idea how can i overwrite this without branching the repo?

**Comment by euvl** [comment]
I am locking this thread as the issue was identified, please follow up in #294 for updates.
