### ISSUE TITLE
Draggable form and android

### ISSUE THREAD

**Issue by mgholam** [euvl/vue-js-modal#156]
Hi,

On mobile android browser like chrome with dragable forms, I can't click on buttons (the move seems to override the click).

**Comment by euvl** [comment]
Yeah, i think touch events are stoped & not handled gracefully. I will see what i can do with it

Thanks for reporting this

**Comment by euvl** [comment]
#188

**Comment by euvl** [comment]
#186

**Comment by euvl** [comment]
Should be fixed now.
