### ISSUE TITLE
Draggable modal fire drag event when I am interacting with the element inside the modal

### ISSUE THREAD

**Issue by mannok** [euvl/vue-js-modal#157]
I put a map with scale slider in the draggable modal. However, the modal keep moving with my pointer with I am dragging the scale slider.

Any solution to mute the dragging event when I am dragging in the content within the modal but the modal itself?

**Comment by euvl** [comment]
my guess is you will have to stop event propagation on your map (prob. for `mousemove` event).

**Comment by euvl** [comment]
also you could make only one part of the modal draggable (for example header, see docs how to do that)

**Comment by mannok** [comment]
Fuck damn right man!   I keep trying to stop propagation from mousedown event!!!

I haven't try yet. Let me try tmr and update you. Thanks!!!

**Comment by euvl** [comment]
No worries at all

**Comment by mannok** [comment]
Success!!! Thanks!!!

**Comment by euvl** [comment]
👍
