### ISSUE TITLE
adaptive modal with margin

### ISSUE THREAD

**Issue by nkwinder** [euvl/vue-js-modal#158]
I have a modal with a specific width (not percentage) and i also set adaptive = true. 
Is there any way to have left and right margins when the modal is shown in smaller screens, instead of sticking at the edges? If i add a margin with css, then calculations of modal position and size are off.

i tried to use 90% width in modal prop, and set a max-width in css, but this also is not working (calculated left position is wrong)

thanks

**Comment by euvl** [comment]
Hey , i've added maxWidth and maxHeight props. Check if they will fix your issue.
Otherwise you can make background of the modal transparent, put your margins and then render a div with white background and shadow - will look the same:)
