### ISSUE TITLE
beforeOpen event is fired after beforeClose if click-to-close is true (on devices not desktop)

### ISSUE THREAD

**Issue by d3bgger** [euvl/vue-js-modal#159]
This happens on devices (or device preview in chrome dev tools).

A modal with beforeOpen and beforeClose events (with a simple console log 'open' and 'close' inside them).

When clicking outside of the modal, the modal is closed (UI is ok) but the output of the events:

expected output: 
open
close

output:
open
close
open

When closing with hide() the events are ok.

**Comment by euvl** [comment]
yeah, there is some weird race condition , also there is some use of `observers` that makes things even more weirder.

**Comment by tarslangil** [comment]
I have the same issue but solved with using 'opened' and 'closed' instead of 'beforeOpen' and 'beforeClose'

**Comment by euvl** [comment]
THis should be fixed now as events fire based on transition now.
