### ISSUE TITLE
beforeOpen() callback triggers before modal dialog has been added to DOM

### ISSUE THREAD

**Issue by mkpaz** [euvl/vue-js-modal#161]
Documentation states that "before-open | Emits while modal is still invisible, but **was added to the DOM**", but why it's impossible to use document selectors inside it...

```
<template>
  <modal name="dialog" open="beforeOpen" @opened="opened"><!-- tons of content --></modal>
</template>

beforeOpen() {
  console.log('beforeOpen', document.querySelectorAll('.v--modal').length); // << beforeOpen 0
},
opened() {
  console.log('opened', document.querySelectorAll('.v--modal').length); // << opened 1
}
```

I've just tried to apply [autosize](http://www.jacklmoore.com/autosize/) script to textarea inside modal component.

**Comment by euvl** [comment]
HI @mkpaz.  

Yep, looks like it is triggered straight after $show. Plugin is getting older and some docs become redundant/wrong.  Feel free to make corresponding changes.

You can prob. use MutationObserver to track when modal becomes visible or feel free to create PR with mentioned event handler. I will be happy to review it.

👍
