### ISSUE TITLE
Is there a max-width property or similiar ?

### ISSUE THREAD

**Issue by leonardo-sj** [euvl/vue-js-modal#163]
I am using percents (70%) in width attribute to keep the component responsive, and works fine.
But in desktop, the modal is bigger than necessary. 
Is there a way to limit the width of the modal in bigger screen ?

**Comment by euvl** [comment]
Hey, good point about bigger screens, I've added properties max-width and max-height, should be there in latest version.

**Comment by xahy** [comment]
For me maxWidth is not working. Using the latest version. 
The properties of my modal are as follows: 

`:maxWidth="1140" width="90%" height="auto" :scrollable="true" :pivotY="0.25"`
