### ISSUE TITLE
this.$modal.show('add-question') not opening modal

### ISSUE THREAD

**Issue by onsombal** [euvl/vue-js-modal#169]
I have a single modal.vue file that has two modals in it. Each of these modals will open perfectly when triggered in one component view while neither will open when triggered in the second component view. I've exhausted every variation I can imagine, but I'm truly at a loss since the exact same code works in one component view, but not the other component view.

Thoughts?

**Comment by onsombal** [comment]
I fixed this issue by locating the other modals inside the vue that calls them rather than separating them inside a common "modals.vue" for all my modals. The one modal that still resides in the separate "modals.vue" component works perfectly when called from another modal.

**Comment by shozayen** [comment]
@onsombal I had an issue when I am trying to show modal from within the component, and it wasn't showing till I have used the following:

```
this.$nextTick(() => {
        this.$modal.show('example')
      })
```
