### ISSUE TITLE
Fail to update new version 1.3.9

### ISSUE THREAD

**Issue by Gnoc** [euvl/vue-js-modal#170]
Hi,
I think there is some weird! Latest version of vuejs is 2.5.13
![image](https://user-images.githubusercontent.com/10009897/35954240-28d7cef2-0cbb-11e8-9296-e93ab694ba97.png)

**Comment by euvl** [comment]
yeah and it says that you need at least 2.2.6+ to use a plugin. whats weird about that? O_o
