### ISSUE TITLE
Runtime Dynamic Modals

### ISSUE THREAD

**Issue by NoelDeMartin** [euvl/vue-js-modal#173]
In my projects I have been implementing the Modal funcionality from scratch, and looking at this plugin I found something interesting. Because I have a lot of modals in my project, I prefer to declare them at runtime instead of doing it in templates, so that I don't need to have all my modals declared and make it more dynamic. I also think it makes more sense. I use Typescript so maybe that has something to do with it, but I don't think it can be limited to that. To illustrate what I mean, this is the current approach:

```
    // Template
    <modal name="foobar">
        {{ text }}
    </modal>

    // Controller
    this.$modal.show('foobar', { text: 'hello' });
```

And this is what I usually do:

```
    // Template - only declared once
    <modals-container></modals-container>

    // Controller
    import FoobarModal from 'foobar-modal.vue'

    this.$modal.show(FoobarModal, { text: 'hello' });
```

This may only make sense for an SPA, since you need to have this modals container. Inside, it is using the [dynamic component](https://vuejs.org/v2/guide/components.html#Dynamic-Components) functionality to show active modals.

Do you think it'd make sense to include this on this package? I am willing to implement it myself and do a pull request, but I'd like to see the maintainer's opinion on this before going ahead :D

**Comment by euvl** [comment]
Hey, sounds interesting. I would rather stick to declarative approach

**Comment by NoelDeMartin** [comment]
@euvl My proposal is to make it a complimentary approach, so all the current functionality would still remain intact, but if anyone wanted they could do it like I mention. Do you think it'd make sense to have both approaches?

**Comment by euvl** [comment]
👍 No, yeah, sounds good to me 😄 

Have you looked into dialog component, i've realised that it is similar to what you've described. 
You put it once and can dynamically generate title + text + buttons modals.

**Comment by NoelDeMartin** [comment]
Yeah I saw that, but even though it can render HTML, it's kind of awkard to use if you want to have reactivity or something more complex. Another advantage of doing this instead of using v-dialog, is that you can stack modals on top (not saying it's good UX or anything, but if someone wants to do it with v-dialog, it's not possible as far as I understand).

Ok cool, when I have the time I'll work on this and I'll do a PR with something less abstract. Thank you :D.

**Comment by euvl** [comment]
Awesome, sounds good. Thanks 👍

**Comment by euvl** [comment]
Nice, merged 👍

**Comment by NoelDeMartin** [comment]
Cool, thank you for your responsiveness :D.
