### ISSUE TITLE
Modal with vuetify grid

### ISSUE THREAD

**Issue by Rchristo** [euvl/vue-js-modal#183]
Trying to create a modal with the vuetify grid layout. But the modal components are hidden and not fully visible:

![unbenannt](https://user-images.githubusercontent.com/9079205/36502188-6d5de14a-1749-11e8-83cc-d2a685839098.JPG)

My code look like this:

`    <modal name="post-modal" width="1200" height="700">
      <v-container fluid>
        <v-layout row flex class="modal">
            <v-flex xs7>
                <v-card height="100%" color="light">
                  <v-card-media height="100%" contain src="/static/login1.jpeg"></v-card-media>
                </v-card>
             </v-flex>
           <v-flex xs5>
             <v-card color="light">
                 <v-list two-line>
                   <template>
                     <v-subheader>Comments</v-subheader>
                     <v-divider></v-divider>
                     <v-list-tile>
                       <v-list-tile-avatar>
                         <img src="http://equifyllc.com/wp-content/uploads/2016/09/round-placeholder.png">
                       </v-list-tile-avatar>
                       <v-list-tile-content>
                         <v-list-tile-title>test1</v-list-tile-title>
                         <v-list-tile-sub-title>yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy</v-list-tile-sub-title>
                       </v-list-tile-content>
                     </v-list-tile>
                     <v-divider></v-divider>
                     <v-list-tile>
                       <v-list-tile-avatar>
                         <img src="http://equifyllc.com/wp-content/uploads/2016/09/round-placeholder.png">
                       </v-list-tile-avatar>
                       <v-list-tile-content>
                         <v-list-tile-title>test2</v-list-tile-title>
                         <v-list-tile-sub-title>yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy</v-list-tile-sub-title>
                       </v-list-tile-content>
                     </v-list-tile>
                     <v-divider></v-divider>
                     <v-list-tile>
                       <v-list-tile-avatar>
                         <img src="http://equifyllc.com/wp-content/uploads/2016/09/round-placeholder.png">
                       </v-list-tile-avatar>
                       <v-list-tile-content>
                         <v-list-tile-title>test3</v-list-tile-title>
                         <v-list-tile-sub-title>yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy</v-list-tile-sub-title>
                       </v-list-tile-content>
                     </v-list-tile>
                     <v-divider></v-divider>
                     <v-list-tile>
                       <v-list-tile-avatar>
                         <img src="http://equifyllc.com/wp-content/uploads/2016/09/round-placeholder.png">
                       </v-list-tile-avatar>
                       <v-list-tile-content>
                         <v-list-tile-title>test4</v-list-tile-title>
                         <v-list-tile-sub-title>yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy</v-list-tile-sub-title>
                       </v-list-tile-content>
                     </v-list-tile>
                     <v-divider></v-divider>
                     <v-list-tile>
                       <v-list-tile-avatar>
                         <img src="http://equifyllc.com/wp-content/uploads/2016/09/round-placeholder.png">
                       </v-list-tile-avatar>
                       <v-list-tile-content>
                         <v-list-tile-title>test5</v-list-tile-title>
                         <v-list-tile-sub-title>yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy</v-list-tile-sub-title>
                       </v-list-tile-content>
                     </v-list-tile>
                     <v-divider></v-divider>
                     <v-list-tile>
                       <v-list-tile-avatar>
                         <img src="http://equifyllc.com/wp-content/uploads/2016/09/round-placeholder.png">
                       </v-list-tile-avatar>
                       <v-list-tile-content>
                         <v-list-tile-title>test6</v-list-tile-title>
                         <v-list-tile-sub-title>yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy</v-list-tile-sub-title>
                       </v-list-tile-content>
                     </v-list-tile>
                     <v-divider></v-divider>
                     <v-list-tile>
                       <v-list-tile-avatar>
                         <img src="http://equifyllc.com/wp-content/uploads/2016/09/round-placeholder.png">
                       </v-list-tile-avatar>
                       <v-list-tile-content>
                         <v-list-tile-title>test6</v-list-tile-title>
                         <v-list-tile-sub-title>yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy</v-list-tile-sub-title>
                       </v-list-tile-content>
                     </v-list-tile>
                     <v-divider></v-divider>
                     <v-list-tile>
                       <v-list-tile-avatar>
                         <img src="http://equifyllc.com/wp-content/uploads/2016/09/round-placeholder.png">
                       </v-list-tile-avatar>
                       <v-list-tile-content>
                         <v-list-tile-title>test6</v-list-tile-title>
                         <v-list-tile-sub-title>yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy</v-list-tile-sub-title>
                       </v-list-tile-content>
                     </v-list-tile>
                     <v-divider></v-divider>
                     <v-list-tile>
                       <v-list-tile-avatar>
                         <img src="http://equifyllc.com/wp-content/uploads/2016/09/round-placeholder.png">
                       </v-list-tile-avatar>
                       <v-list-tile-content>
                         <v-list-tile-title>test6</v-list-tile-title>
                         <v-list-tile-sub-title>yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy</v-list-tile-sub-title>
                       </v-list-tile-content>
                     </v-list-tile>
                     <v-divider></v-divider>
                     <v-list-tile>
                       <v-list-tile-avatar>
                         <img src="http://equifyllc.com/wp-content/uploads/2016/09/round-placeholder.png">
                       </v-list-tile-avatar>
                       <v-list-tile-content>
                         <v-list-tile-title>test6</v-list-tile-title>
                         <v-list-tile-sub-title>yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy</v-list-tile-sub-title>
                       </v-list-tile-content>
                     </v-list-tile>
                   </template>
                 </v-list>
               </v-card>
            </v-flex>
        </v-layout>
      </v-container>
    </modal>`

**Comment by euvl** [comment]
this looks crazy, and been open for 25 days, closing.
