### ISSUE TITLE
Dynamic modal not closed if I emit 'close' event from my component

### ISSUE THREAD

**Issue by molobala** [euvl/vue-js-modal#184]
When I emit `close` event from my dynamic modal component , nothing happens !

**Comment by euvl** [comment]
oh no!

**Comment by molobala** [comment]
Same that the update has not the functionnality , I checked the code and did not find `@close="..."` on component in modals-container component

**Comment by euvl** [comment]
it is not published yet

**Comment by euvl** [comment]
Published 👍
