### ISSUE TITLE
Width is not a reactive property

### ISSUE THREAD

**Issue by kaptk2** [euvl/vue-js-modal#185]
A modal width can't be changed. I setup a simple component to test. When opening the modal like this:
```
<button @click="show('hello-world2', {width: '90%', pivotY: 0.4})">Open Modal</button>
```
I expected the window to open with a width of 90% however the resulting window is 100% wide. The pivotY can be changed.

Here is my component:
```
<template>
  <modal name="hello-world"
    @before-open="beforeOpen"
    :pivotY='modalPivotY'
    :width="modalWidth">
    <p>Hello World</p>
  </modal>
</template>

<script>
  export default {
    data () {
      return {
        modalWidth: '100%',
        modalPivotY: 0.5
      }
    },
    methods: {
      show(name, params) {
        this.$modal.show(name, params);
      },
      beforeOpen(event) {
        this.modalWidth = event.params.width
        this.modalPivotY = event.params.pivotY
      }
    }
  }
</script>
```
This might be related to issue #141

**Comment by euvl** [comment]
Hey @kaptk2, thanks for your issue. Yes, width is not reactive, partly because there are a lot of calculations involved for width and height (take a look into the code), partly it was done on purpose, to make sure that developers would not be able to fuck things up in any way.

**Comment by kaptk2** [comment]
Hi @euvl 

I see all the calculations involved, however having the width be reactive would be amazing. I'm not sure how to go about enabling this.

**Comment by euvl** [comment]
i dont know either

**Comment by kaptk2** [comment]
I have tried doing this on my own but am stuck. Seems like most of the pieces are there to make this happen, especially since it can be resized using Resizer. I have tried adding a updateRenderedWidth function to Modal.vue but when the width property changes nothing happens. Do you have any hints for me about where I should look next?

**Comment by euvl** [comment]
Hey @kaptk2 , i am afraid i don't really have any hints. I was building all features over time and it took ages to put all pieces together for it to work reliably.

**Comment by kaptk2** [comment]
Hi @euvl that's okay. Thanks for the nice library!

**Comment by amadoalmex** [comment]
I had a similar issue with the height property. I solved reactiveness with a v-if to recreate the modal component based on the width (height in my case.)

```
<template>
  <modal name="hello-world"
    @before-open="beforeOpen" @closed="modalWidth=0"
    :pivotY='modalPivotY'
    :width="modalWidth" v-if="modalWidth">
    <p>Hello World</p>
  </modal>
</template>

<script>
  export default {
    data () {
      return {
        modalWidth: 0,
        modalPivotY: 0.5
      }
    },
    methods: {
    open(width, pivotY){
// initialize component parameters
  this.modalPivotY = pivotY; this.modalWidth = width;
// show modal
this.$modal.show('hello-world');
}
    }
  }
</script>
```

**Comment by kaptk2** [comment]
I'm trying to get this to work but I'm not having much luck. How are you calling your modal to show? Is the method open supposed to be beforeOpen?

**Comment by amadoalmex** [comment]
You have to call this.open(width, pivotY) with the new parameters each time, you could have two buttons that opens the modal with different widths and pivot on each event.

**Comment by euvl** [comment]
Yeah sorry for this, width is a tricky one, it is not reactive yet
