### ISSUE TITLE
Mousedown and touchdown events don't propagate

### ISSUE THREAD

**Issue by tonila** [euvl/vue-js-modal#186]
There is a problem with vue-js-modal stopping event propagation onBackgroundClick.

E.g. Bootstrap datepicker listens documents mousedown and touchstart events.
Now, when datepicker is placed inside modal, it never closes, because modal stops events from propagating.

I think it should not be components decision to stop propagation. And at least it shoud not stop propagation by default if it is set configurable.
https://css-tricks.com/dangers-stopping-event-propagation/

See
https://github.com/euvl/vue-js-modal/blob/master/src/Modal.vue

```
@mousedown.stop="onBackgroundClick"
@touchstart.stop="onBackgroundClick"
```

**Comment by euvl** [comment]
Hey thanks for an issue

If you will come up with better solution how not to close modal when you click on it (because it is in overlay, and overlay has it's onclick handler) i will be happy to review the PR 😄 

Other than that, I don't really know how i can fix this.

**Comment by tonila** [comment]
Hi, and thanks for a quick response!
I don't think I know a solution. Just reporting... :'(

**Comment by euvl** [comment]
yeah

**Comment by euvl** [comment]
If anyone has any ideas how this can be fixed, please post it here, thanks 👍

**Comment by darrylhein** [comment]
Here's what I've done, though it's not ideal (I'm using Flatpickr):

On my element that's goes into the default slot, I add a click handler. In the handler/method, if the event target is not the date picker element then close the date picker.

```javascript
wrapClicked (e) {
    if (e.target !== this.flatpickr.input) {
        this.flatpickr.close();
    }
},
```

This isn't ideal and I'm sure I'm going to find a bug at some point, but it appears to work for now. If anyone has an ideas or improvements, let me know.

**Comment by andremiguelaa** [comment]
I'm not proud of this but... for multiple flatpickrs:

```javascript
closeDatepickers(e) {
    this.$children[0].$children.forEach(element => {
        if (e.target.parentNode !== element.fp.input.parentNode) {
            element.fp.close();
        }
    });
},
```

**Comment by Kylexii** [comment]
maybe the event binding modifier .self can resolve the problem?

**Comment by euvl** [comment]
Fixed
