### ISSUE TITLE
Use beforeOpen beforeClose event with modals-container 

### ISSUE THREAD

**Issue by GMounir** [euvl/vue-js-modal#187]
Hello Thank you for your amazing work...
i just wondering how to use beforeClose and beforeOpen events with dynamic template importing from another path thank you again.

**Comment by euvl** [comment]
hey i am afraid you cant use any lifecycle events when you use dynamic modals 😞

**Comment by GMounir** [comment]
Ahhh ok thank you for your responding :)

**Comment by lucadegasperi** [comment]
@euvl is there any chance this will be implemented for the dynamic modals? I find myself in the same situation as I need to prevent the dynamic modal from closing on certain conditions. Or could you point me at least in the right direction to implement this?

**Comment by euvl** [comment]
Hey, I didn't look into dynamics modals recently, as i don't have enough time. You can look into here: https://github.com/euvl/vue-js-modal/blob/master/src/ModalsContainer.vue , see how you can pass event handlers, etc.

**Comment by euvl** [comment]
Actually where we have `v-bind="modal.config"` , you can do the same for `v-on` and bubble up all events from the modal, just think how make it work nicely :)
