### ISSUE TITLE
How to add a close button to a dynamic modal

### ISSUE THREAD

**Issue by mcicolella** [euvl/vue-js-modal#189]
Hi,
I'm using the following code to show a dynamic modal
```
showDynamicComponentModal () {
      this.$modal.show(AddAutomation, {
        text: 'This text is passed as a property'
      },
        { draggable: true,
          adaptive: true,
          resizable: true,
          clickToClose: false,
          width: '65%',
          height: '40%'
        })
    }
```
How can add a close button?

**Comment by nlien** [comment]
Pass a `name` property:
`this.$modal.show(AddAutomation, null, {name: 'myModal'})`
Call `this.$modal.hide('myModal')` in `AddAutomation`
Or emit the close event:
`<button @click="$emit('close')">Close</button>`
I believe this is documented here:
https://github.com/euvl/vue-js-modal#dynamic-modals
