### ISSUE TITLE
Add dialog box wrapper

### ISSUE THREAD

**Issue by euvl** [euvl/vue-js-modal#19]
Add a dialog box wrapper for simplified modals. 
Current version looks like this: 

<img width="509" alt="screen shot 2017-05-12 at 10 38 41" src="https://cloud.githubusercontent.com/assets/1577802/25992668/36daba74-36ff-11e7-8836-a9fc44fd75b6.png">

Extra props can be:
```
:labels - Array / (List of buttons)
```

Extra events can be: 
```
@cancel
@agree
```

**Comment by TomKaltz** [comment]
wontfix?

**Comment by euvl** [comment]
@TomKaltz sorry? You dont like how i tag my issues?

**Comment by TomKaltz** [comment]
There is some missing context/metadata in this thread.  Wondering why this
was going to be a feature but then you decided to abandon.

**Comment by euvl** [comment]
As you can see from the screenshot, I have it done already.The component is in my other project, I just have to move it into this repo.

**Comment by euvl** [comment]
Hey @TomKaltz,
I've pushed the change for enhanced `<Dialog/>` component and updated docs 👍
