### ISSUE TITLE
maxWidth not working

### ISSUE THREAD

**Issue by conradolk** [euvl/vue-js-modal#191]
Hello there, great plugin! I'm trying to set the width of the modal to the 100% so in mobile it covers the full screen but i want to limit it for desktop usage at 800px. It´s not working, the maxWidth prop is not being applied.

`<modal width="100%" height="auto" maxWidth="800" :scrollable="true" :adaptative="true" name="new-timeline-event">`

Am i missing something here? Thanks for reading!

**Comment by euvl** [comment]
Hey, can you try `:max-width="800"` instead of `maxWIdth="800"` ?

**Comment by conradolk** [comment]
Unfortunatly it is still not working, if set to `width="100%` and `:max-width="400"` the modal will be 100% of the screen
`<modal width="100%"
           height="auto"
           :max-width="800"
           :scrollable="true"
           :adaptative="true"
           name="new-timeline-event">`

**Comment by nlien** [comment]
@conradolk Just want to point out that the `adaptive` property is misspelled in your example. It may not be a connection with your problem, just sayin'...

**Comment by callumisitt** [comment]
I was having the same problem and setting adaptive to true fixed it

**Comment by conradolk** [comment]
Thanks both, setting `adaptive ` to true fixed it! And thanks to euvl for the _awesome_ plugin.

**Comment by euvl** [comment]
👍 THanks!

**Comment by nitwhiz** [comment]
max-width will be ignored if height is set to auto. my setup:
```
transition="ease"
width="80%"
height="60%"
:pivot-y="0.1"
:min-height="64"
:reset="true"
:adaptive="true"
:max-width="1280"
```

**Comment by RobertCordes** [comment]
The following still doesn't work for me:

`<v-dialog width="90%" :max-width="500" :adaptive="true" />`
