### ISSUE TITLE
Source code of “Dialog: title” example wanted

### ISSUE THREAD

**Issue by sergeynilov** [euvl/vue-js-modal#193]
Hello,
I reviewed examples here
http://vue-js-modal.yev.io/
I installed it and I try to implement “Dialog: title” example, but that seems difficult for me.
If there is a source code of this example? maybe on fiddle ?

Thanks!

**Comment by euvl** [comment]
yes, it is in "demo" folder.

**Comment by sergeynilov** [comment]
Do you mean file vue-js-modal-master.zip (1.4 MIB). Demo directory has 2 subdirectories client_side_rendering and server_side_rendering. I suppose the first ?

**Comment by euvl** [comment]
Yes
