### ISSUE TITLE
Modal property

### ISSUE THREAD

**Issue by Jeroendedoem** [euvl/vue-js-modal#194]
Hi, i love the package but just a small thing I stumbled upon while using the readme.
I noticed it while using the :height property, but this is probably the case for more. If you use `:height="auto"` you get a vue error, this is easy to fix by using `:height="'auto'"` but in the readme it doesn't mention this. It even says you should use only the double quotes: `Height in pixels or percents (e.g. 50 or "50px", "50%") or "auto"`. Maybe you could alter this to save the hassle for future users.
![image](https://user-images.githubusercontent.com/5631345/37225617-76b20894-23d7-11e8-8bac-17543e9cb2b4.png)

**Comment by euvl** [comment]
Hey, it's just how vue works. if you bind something, you need to bind to the value. IF you do :heigth="auto" it means that you are binding to the value in variable named "auto". 

I don't think it should be part of the readme, for more inormation how binding works, go here: https://vuejs.org/v2/api/#v-bind
