### ISSUE TITLE
horiz scroll when scrollable=true

### ISSUE THREAD

**Issue by fly1ted** [euvl/vue-js-modal#196]
I have horizontal scroll on a page with vertical scroll (desktop) with these options

```
name="add"
width="800px"
height="auto"
scrollable=true
adaptive=true
```

It helps setting
```
.v--modal-block-scroll{
  max-width: 100%;
}
```

**Comment by euvl** [comment]
cool, so your usecase works with adding a line of css 👍 well done 👍

**Comment by fly1ted** [comment]
I think it's a more general case though. Basically anyone with such common settings will get this. It happens because of 100vw behavior explained here https://www.sitepoint.com/community/t/100vw-and-scrollbars/196480.

**Comment by cirokd** [comment]
I have the same issue, and that CSS one-liner did not fix it. @fly1ted do you have any other suggestions for working around the 100vw issue?
