### ISSUE TITLE
How call Dialog in Modal

### ISSUE THREAD

**Issue by denzel94** [euvl/vue-js-modal#198]
Hi! When im trying call Dialog for tell user about not valid fields Dialog showing but under Modal. How i can do it corretcly? 

`<v-dialog/>
        <modal name="edit_modal" height="auto" :clickToClose="editChannelModal.isValid">
            <div class="modal_inner" v-if="channel.hasOwnProperty('properties')">
                <div class="modal_title">
                    <strong>Edit Channel</strong>

                    <div class="close_modal"  @click="hide('edit_modal')">
                        ×
                    </div>
                </div>
                <div class="modal_body">
                    <div class="modal_inputs">
                        <div class="input">
                            <label for="channel_title">Title</label>
                            <input
                                type="text"
                                id="channel_title"
                                v-model="editChannelModal.title.nowTitle"
                                placeholder="Channel Title"
                                @change="validateChannelModal"
                                @input="validateChannelModal"
                                :class="{ not_valid: editChannelModal.title.notValid }"
                            >
                        </div>
                        <div class="input">
                            <label for="channel_thubmnail_url">Thumbnail</label>
                            <input
                                type="url"
                                id="channel_thubmnail_url"
                                placeholder="Channel Thumbnail URL"
                                v-model="editChannelModal.thumbnail.nowThumbnail"
                                @change="validateChannelModal"
                                @input="validateChannelModal"
                                :class="{ not_valid: editChannelModal.thumbnail.notValid }"
                            >
                        </div>
                        <div class="input">
                            <label for="channel_remote_id">Remote id</label>
                            <input
                                type="text"
                                id="channel_remote_id"
                                :value="channel.properties.remote_id"
                                placeholder="Channel Remote Id"
                                disabled
                            >
                        </div>
                    </div>
                    <div class="modal_item_id">
                        id: {{ channel.id }}
                    </div>
                </div>

                <div class="modal_controls one_item">
                    <div class="modal_controls_item">
                        <button class="light_red_button" @click="hide('edit_modal')">
                            <i class="fas fa-arrow-left"></i> Cancel
                        </button>
                        <button class="blue_button" @click="saveEditChannelModal"><i class="far fa-save"></i> Save</button>
                    </div>
                </div>
            </div>
        </modal>`

`saveEditChannelModal () {
    console.log('sdfsdf');
    this.$modal.show('dialog', {
        text: 'I am a tiny dialog box.<br/>And I render <b>HTML!</b>'
    })
}`

**Comment by euvl** [comment]
i generally find it a bad ux if you nave modal over modal
