### ISSUE TITLE
Listening on the resize event for the dynamic modal. 

### ISSUE THREAD

**Issue by negiDharmendra** [euvl/vue-js-modal#199]
We are using CKEditor inside the dynamic modal. We would like to resize the editor as the user resizes the modal. 
What would be the best way to figure out that modal is being resized?

**Comment by euvl** [comment]
i don't think it's plugins issue, you can use stackoverflow for these types of questions, for example you could use observables or implement some resize event listeners on top of existing ones.

**Comment by nathanboktae** [comment]
Honestly the better answer is to use flexbox, and if `vue-js-modal` would just use it natively it wouldn't need it or things like `height="auto"`. Here's my CSS (stylus) to ignore all sizing and just use flexbox for modal positioning.

```styl
.v--modal-overlay
  display flex
  justify-content center
  align-items center
.v--modal-box.v--modal
  top initial !important
  left initial !important
  width auto !important
  height auto !important
```

I also have

```styl
.v--modal-box.v--modal
  max-width 95vw // or some other sensible default for some side margins
  display flex
  flex-direction column
```

and use flexbox styling throughout my app and modals, but that's up to you.

**Comment by negiDharmendra** [comment]
@euvl  Thanks for the reply. I have figured it out. The solution was to use modal instead of dynamic modal. As dynamic modal would not propagate the resize event emitted by modal, so was not able to bind a resize event listener.
