### ISSUE TITLE
Hi! 

### ISSUE THREAD

**Issue by CinemasSources** [euvl/vue-js-modal#20]
It took a long time to understand what the problem was, but my colleagues helped me figure it out.
In the description there is an error.
`methods: {
  show () {
    this.$modal.show('hello-word'); // need "hello-world".. 
  },
  hide () {
    this.$modal.hide('hello-world');
  }
}`

**Comment by euvl** [comment]
Hey, thanks a lot for pointing it out 👍 😄 
Will correct it asap

**Comment by euvl** [comment]
Also if you will need more examples, check out demo folder :)

**Comment by CinemasSources** [comment]
Hey, thank you! i see
