### ISSUE TITLE
The select element does not respond to mouse (and v-touch) 

### ISSUE THREAD

**Issue by zeusfly-spb** [euvl/vue-js-modal#202]
Hi! The select element (inside modal) does not respond to mouse (and v-touch) events when I open a page from my smartphone. How can I solve this problem?

**Comment by euvl** [comment]
#186

**Comment by zeusfly-spb** [comment]
euvl Thank You! I've already dealt with the problem. It turned out that the problem was that I had not identified class is available as a hook to drag. Everything is already cool!

**Comment by euvl** [comment]
cool, thats kind of an issue though, but  we will keep track of it in n186 👍 👍
