### ISSUE TITLE
vue-js-modal + Nuxt + runtime-only build

### ISSUE THREAD

**Issue by johnRivs** [euvl/vue-js-modal#207]
Is there a way to make this package (^1.3.12) and Nuxt (^1.2.1) work together nicely when using the runtime-only build? I'm trying to use dynamic modals, in case that's relevant.

### plugins/vue-js-modal.js
```js
import Vue from 'vue';
import VModal from 'vue-js-modal/dist/ssr.index';

Vue.use(VModal, { dynamic: true });
```

### nuxt.config.js
```js
module.exports = {
  build: {
    vendor: {
      'vue-js-modal/dist/ssr.index.js'
    }
  },
  plugins: ['~/plugins/vue-js-modal']
}
```

### Console warning
```
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <Anonymous>
       <VueJsModal> at D:\Projects\vue\vue-js-modal\src\Modal.vue
         <ModalsContainer> at D:\Projects\vue\vue-js-modal\src\ModalsContainer.vue
           <Anonymous>
             <Root>
```

**Comment by euvl** [comment]
Just use full version of vue library, if you want to compile templates in runtime, you need it.

**Comment by johnRivs** [comment]
Right.. but there's nothing else in my app that requires the full version of Vue. Is there absolutely no way to get this package working with the runtime-only build?

**Comment by euvl** [comment]
You are trying to use dynamic modals, the only purpose of those is to compile template in runtime and show it.

**Comment by johnRivs** [comment]
Ahh I see. If I try without dynamic modals, it should work just fine with the runtime-only build, right?

**Comment by euvl** [comment]
yea, i think it should be fine

**Comment by johnRivs** [comment]
Thanks for your time.

For anybody in the same situation, you can use [portal-vue](https://github.com/LinusBorg/portal-vue) to imitate dynamic modals by binding the name to a variable. However, you'll have to write all the logic to open modals, close, etc..
