### ISSUE TITLE
Vuejs loaded twice

### ISSUE THREAD

**Issue by a3020** [euvl/vue-js-modal#21]
dist/index.js contains vuejs 2.2.6.

If I use `import vmodal from 'vue-js-modal';` in an existing vuejs project, vuejs is loaded twice because my main application uses version 2.3.3. 

What is the general approach to overcome this? I am a ES6 noob, so sorry if this is dumb question :)

**Comment by euvl** [comment]
It is pretty good question, thanks for noticing it. 
I think i should remove it from `dependencies`.

But i will need a help of webpack gugu to figure out how correctly package it without vuejs.

**Comment by a3020** [comment]
Yeah, I don't think it's common to have it included in dist. From what I read you need to use `path.resolve`. See e.g. https://github.com/webpack/webpack/issues/2134#issuecomment-192579511 and http://stackoverflow.com/questions/31169760/how-to-avoid-react-loading-twice-with-webpack-when-developing.

**Comment by euvl** [comment]
Hey @a3020, I think I've done it 😄 
If you will check the latest master, it has a ±30 kb `dist/index.js` (instead of a bloody ±300kb) and it seems to work as it used in the demos. 

Would you have time to test whether it works for your project? 
(keep in mind its not on npm yet, only on github)

**Comment by a3020** [comment]
I used `npm install --save-dev git+ssh://git@github.com/euvl/vue-js-modal` to install directly from the Github repo. I then ran webpack. All still works and vue-js is only loaded once. So yes, I think you nailed it 👍

**Comment by euvl** [comment]
Great, thanks a lot for your help! 👍  🥇
Will do a new release now!
