### ISSUE TITLE
Is there a way to add some code to every hook in vue-js-modal component?

### ISSUE THREAD

**Issue by heyas** [euvl/vue-js-modal#210]
I need to do some stuff on every closed() hook - how i can do that? Without change main code of vue-js-modal ofc. 

```
const hide = vm.$modal.hide
vm.$modal.hide = function (...args) {
  console.log('FROM HIDE', args)
  hide(...args)
}
```
This works fine but only for explicit call of hide() function, or for ESC press, but not for click outside the modal window.

**Comment by heyas** [comment]
How i can do that for all modals?

**Comment by euvl** [comment]
<mySuperModal> 
  <modal @before-open="my_function_xxxx" v-bind="$attrs"  v-on="$listeners">
    <slot/>
  </ modal>
</mySuperModal>

**Comment by heyas** [comment]
I meant one time for all modals in my app. Maje it once and then extends from one elemenr - is that a goid idea?

**Comment by euvl** [comment]
sorry, i didnt understand the question
