### ISSUE TITLE
Error Vue-router

### ISSUE THREAD

**Issue by viciotec** [euvl/vue-js-modal#216]
#### Problem: 

...When you have vue-router installed and you pass between pages, the pile of manners you handle is not restarting or it may be that your delete function is not working

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Hey @viciotec , what does "the pile of manners " mean? Thanks.

**Comment by viciotec** [comment]
I'm sorry it was my mistake

**Comment by euvl** [comment]
No problem
