### ISSUE TITLE
100vh on v--modal-overlay doesn't prevent CHrome address bar causing Jank.

### ISSUE THREAD

**Issue by trusktr** [euvl/vue-js-modal#217]
To prevent Chrome from being Jank, I had to override the modal style in my component like this:

```html
<!-- unscoped style for the modal, because scoped style can not otherwise reach
    into the modal component style -->
<style lang="stylus">
    .MobileMenuModalWrapper {
        .v--modal-box {
            width: 100% !important;
            height: 100vh !important;
            top: 0 !important;
            left: 0 !important;
        }
    }
</style>
```

If I use the API (`width` and `height` props), I can not achieve this. Looks like the parser only accepts `%` and `px` units,

https://github.com/euvl/vue-js-modal/blob/master/src/parser.js#L3

Maybe it needs also `vh` and other units there.

**Comment by euvl** [comment]
You are free to extend parser
