### ISSUE TITLE
Question: can i use plugin without "npm install vue-js-modal --save"?

### ISSUE THREAD

**Issue by boomsya** [euvl/vue-js-modal#219]
hi, at now i try to learn vue.js
can i copy-paste files to project folder and only include some files to HTML or JS without running "npm install vue-js-modal --save" ?

at now i create file imports.js:
```
import VModal from '/vue-js-modal'
Vue.use(VModal);
```
and include this to index.html
```
<head>
  <script src="js/vue.min.js"></script>
 <script src="js/imports.js" type="module"></script>
</head>
<body>
<div id="app">
<button class="btn green" @click="show()">test</button>
<modal name="hello-world">
			hello, world!
		</modal>
	</div>
```

and app.js is:
```
var app = new Vue({
	el: '#app',
    methods:{
		show () {
			this.$modal.show('hello-world');
		},
		hide () {
			this.$modal.hide('hello-world');
		}
	}
});
```
but when i open page i see text "hello, world!" and when click button "test" browser output in console:
`TypeError: this.$modal is undefined` on line `this.$modal.show('hello-world');`

**Comment by euvl** [comment]
no you cannot use it without npm

**Comment by boomsya** [comment]
ok. at now i understand this. i was installed node.js to run npm.
demo project vue-js-modal works fine with command "npm run dev" 
but i want to run project with apache+php +mysql
and lines like:
```
import Modal from './Modal.vue'
import Dialog from './Dialog.vue'
import ModalsContainer from './ModalsContainer.vue'
```
leads to errors:
Firefox: SyntaxError: import declarations may only appear at top level of a module
Chrome: Uncaught SyntaxError: Unexpected identifier

can one explain to me how to run projects on apache?

**Comment by boomsya** [comment]
i think i wsa found answer to my question:

https://medium.com/@alvarez.michael.joseph/how-to-deploy-a-vue-js-webpack-application-to-apache-tomcat-7770ad609f1f
https://forum.vuejs.org/t/getting-problem-on-deploying-vue-2-and-webpack-in-my-apache-server/4745
