### ISSUE TITLE
how can I fix top position like the demo of auto height?

### ISSUE THREAD

**Issue by wasichris** [euvl/vue-js-modal#220]
#### Problem: 
I put tabs in a modal but they have different heights, I hope to fix the top position so that user will not feel modal is jumping during switching tabs.

I have used the same settings as the demo-size-modal you made, but I still can't make it. I'm wondering if there is something like a flag to decide fixed top position or not.

![image](https://user-images.githubusercontent.com/12275870/39081525-f15cd790-4574-11e8-88b4-edad4e27079f.png)

#### Example & screenshots:
![watch 100](https://user-images.githubusercontent.com/12275870/39081505-ae95b2ce-4574-11e8-986a-fc88ef78f716.gif)

**Comment by euvl** [comment]
First of all, thanks for well presented issue 👍  I don`t think its possible to do that, you can try changing pivot-y, mb it will help. Also you could simply try to make modal's height static (max height out of all your tabs) in case you know in advance what's your tabs' heights will be. I'll give it a thought, mb i will be able to come up with something 👍

**Comment by wasichris** [comment]
Thanks for your reply and suggestions. I noticed the demo as below probably can meet my requirements. Is it still working with the latest version(1.3.13)? I still can't get the same result as yours.


![watch 101](https://user-images.githubusercontent.com/12275870/39108554-583b7b1a-46fb-11e8-8eda-8c05d8168b9d.gif)

**Comment by euvl** [comment]
Strange, i think the demo is actually pretty outdated, there might be some regression in the current version.

**Comment by kdekooter** [comment]
Opening bot here. Still curious about the solution! Especially on mobile with a virtual keyboard popping up a relative top position causes the dialog to move up.
