### ISSUE TITLE
Little mistake in the id '#modals-container'

### ISSUE THREAD

**Issue by laurentjassaud** [euvl/vue-js-modal#221]
#### Problem: 

Mistake in the 'id' name lign 2 in src/ModalsContainer.vue
...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Hey @laurentjassaud, nicely spotted, thanks 👍

**Comment by euvl** [comment]
Will publish it with next release
