### ISSUE TITLE
Question: How can I hide modal, if I do not know their "name"?

### ISSUE THREAD

**Issue by sergei97k** [euvl/vue-js-modal#222]
#### Problem: 

Hi. I have some logic in my application, and I have a lot of modals in different components. I need to hide current opened modal, but I can not know which one will be opened, and I can not know their name.

**Question**: Can I hide the modal without knowing their name?

P.S. I remember that I can save the name of the current modal when it opens (using the `beforeOpen` method), but it will not be very convenient, since I have a large number of modals.

**Comment by euvl** [comment]
In older incarnation, if you call hide/close without name it would close everything, i will take a look if this is still the case

**Comment by euvl** [comment]
@Nfinished You can look into the code and implement this feature, no need to stay frustrated 😄 👍

**Comment by sergei97k** [comment]
@euvl If I have enough time and experience - I can add this functionality. I will try to do it in the near future.

**Comment by christophwolff** [comment]
bummer... :-(

**Comment by christophwolff** [comment]
oh this was easy. Just emit a close event with a button or something in your Modal:
`@click="$emit('close')"`

**Comment by euvl** [comment]
No probs, thanks 👍  I will prob. make it more visible in the docs. Clearly it is confusing and/or not evident

**Comment by lmj0011** [comment]
>In older incarnation, if you call hide/close without name it would close everything, i will take a look if this is still the case

this is not the case as v1.3.26

This PR should solve a relatable problem though (ie. multiple modals being opened at once)

https://github.com/euvl/vue-js-modal/pull/347
