### ISSUE TITLE
iOS Safari: Scrollable modal scrolls background instead

### ISSUE THREAD

**Issue by rbvea** [euvl/vue-js-modal#223]
#### Problem: 

Tested in iOS 11: if a modal is `scrollable="true"` and the content is greater than the viewport height, the modal opens but trying to scroll down results in the body being scrolled instead of the modal content.

#### Example & screenshots:

**Site:** https://vue-js-modal-repro.firebaseapp.com/
**Github repo:** https://github.com/rbvea/vue-js-modal-repro
**GIF** tested on BrowserStack

![kapture 2018-04-30 at 13 49 21](https://user-images.githubusercontent.com/949055/39455733-d21da1ba-4c7d-11e8-9c84-525554615284.gif)
 
I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
That's not good, i will take a look 👍

**Comment by rbvea** [comment]
I've used this library and it seems to work pretty well: https://github.com/willmcpo/body-scroll-lock

**Comment by euvl** [comment]
Merged your PR, hopefully next release will fix an issue.

**Comment by rbvea** [comment]
Thanks!
