### ISSUE TITLE
Modal no longer adaptive

### ISSUE THREAD

**Issue by JonathanTroyer** [euvl/vue-js-modal#224]
#### Problem: 
Normally setting adaptive to true results in an adaptive modal. However, this is no longer the case in release 1.3.13.
...

#### Example & screenshots:
![screenshot_20180502_174014](https://user-images.githubusercontent.com/15098499/39552719-0059c140-4e30-11e8-9a24-9dd3dcc35079.png)
![screenshot_20180502_174042](https://user-images.githubusercontent.com/15098499/39552720-00696578-4e30-11e8-9749-822f21b8cc85.png)
...

I have checked stackoverflow for solutions and 100% sure that issue not in my code, as the only thing that has changed is the version.

**Comment by euvl** [comment]
Feels like some regression issue. Need to be looked at, thanks for reporting @JonathanTroyer  👍 👍

**Comment by VictorCazanave** [comment]
@JonathanTroyer does this bug still exist in the last version (1.3.26)?

**Comment by JonathanTroyer** [comment]
@VictorCazanave it most certainly does unfortunately. Tested in Chrome 69.

**Comment by euvl** [comment]
Thanks, i finally have time to look into it

**Comment by madebycaliper** [comment]
Hi any update on this? I'm experiencing the same issue.
