### ISSUE TITLE
Iexplorer 11 TypeError: Object doesn't support property or method 'blur'

### ISSUE THREAD

**Issue by simllll** [euvl/vue-js-modal#226]
#### Problem: 
Internet Explorer 11 and lower sometimes throw TypeError: Object doesn't support property or method 'blur'. To fix this, the library should check if the method exists, before calling it.

#### Example & screenshots:
Exception
TypeError: Object doesn't support property or method 'blur'
  at e.default.methods.toggle (/_nuxt/vendor.27bb26120d5012bea2d3.js:2:101814)
  at Anonymous function (/_nuxt/vendor.27bb26120d5012bea2d3.js:2:99026)
  at t.prototype.$emit (/_nuxt/vendor.27bb26120d5012bea2d3.js:2:33201)
  at t.prototype.$modal.show (/_nuxt/vendor.27bb26120d5012bea2d3.js:2:93869)

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

You check already for document.activeElement.
Therefore I prupose following changes in:
Modal.vue line 459:
`if (document.activeElement && typeof document.activeElement.blur === 'function') {
`

regards
Simon

**Comment by euvl** [comment]
Thanks for a PR 👍 👍 👍

**Comment by joshuafranks** [comment]
I too am having this issue, but the proposed solution does not work for me.

**Comment by euvl** [comment]
I do not think it is published yet.

**Comment by joshuafranks** [comment]
My mistake, I implemented this locally but ended up being thrown a new error instead involving 'assign'. A polyfill resolved it. This solution is fine.
