### ISSUE TITLE
Fail to change .v--modal background color in scoped style

### ISSUE THREAD

**Issue by CaliosD** [euvl/vue-js-modal#228]
#### Problem: 
I tried to change background color by overriding `.v--modal` in my scoped style.
```
<style lang="stylus" scoped>
  .v--modal-overlay
    background-color rgba(90, 90, 90, .6)    // this line works, just used to test whether changing attribute directly in scoped style will work or not
  .v--modal
    background-color yellow    // this line doesn't works and the color remains white
</style>
```
However, when I put this segment into a global .css file, everything works fine.

I wonder why it failed, and how to fix it if I want to set it in a scoped style part.

Thanks for any suggestion in advance. :)
...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Just add a class please with your style to classes. THanks

**Comment by CaliosD** [comment]
Thanks for replying. I figured out that later... and forgot to close this issue.
