### ISSUE TITLE
has a problem in nuxt.js(ssr),can support it?

### ISSUE THREAD

**Issue by SzHeJason** [euvl/vue-js-modal#23]
make vue directive or ??
![image](https://cloud.githubusercontent.com/assets/20609396/26275707/9827402c-3d99-11e7-982f-e8e68b7ed69c.png)

**Comment by euvl** [comment]
I never used `nuxt.js` but i will take a look, all help is welcomed

**Comment by SzHeJason** [comment]
@euvl thank，maybe i can prodive some plugins of support ssr ，hope these would be helpful for you。
[vue-lazyload](https://github.com/hilongjw/vue-lazyload)
[vue-video-player](https://github.com/surmon-china/vue-video-player)

**Comment by euvl** [comment]
Coolio, ty
