### ISSUE TITLE
How do I add content to top-right slot when using dynamic modals?

### ISSUE THREAD

**Issue by AlMod90** [euvl/vue-js-modal#230]
It is required to add ```<modal></modal>``` to a template to be able to write to vuejs slots. With dynamic modals I can't get it to work, because it's required that my ```.vue``` component not to have ```<modal></modal>```. (Modal is rendered blank if it does)

**So the question is:** Is it possible or not to add the ```x``` close button to VModal's top-right slot or not when using dynamic modals

P.S. Yes, surely i can add close button to my component's template, but i want it to be placed where it should be, not in modal's body content

**Comment by pmochine** [comment]
Would love to know it as well!

**Comment by samwhiteiv** [comment]
would also like to know please

**Comment by jasonbarrows** [comment]
It would be great if this were possible.
