### ISSUE TITLE
can we add any custom event handler?

### ISSUE THREAD

**Issue by rebotak** [euvl/vue-js-modal#231]
#### Problem: 

so I want to emit multiple event handler, or passing parameters on close, is it possible? 

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by akarelas** [comment]
I agree, I really need this feature. In partticular, I'd like to be able to $emit custom events from inside a Dynamic Modal, and receive them on the component that contains `<modals-container @my-custom-event="..." />` Otherwise I have no way of knowing what happened in the modal. Thanks!
