### ISSUE TITLE
Bug oveflow:hidden on the new version 1.3.14

### ISSUE THREAD

**Issue by nghiepit** [euvl/vue-js-modal#235]
Hi guys,

I just upgraded to 1.3.14 and I have an error with `overflow: hidden`. The body tag cannot restore scrollbar default after closed modal.

Thanks.

**Comment by euvl** [comment]
Looks like there is a bug in scroll library that someone introduced. I will take a look and if i will not be able to fix it i will revert to the previous version.

**Comment by euvl** [comment]
I've reverted changes as seems that that library does not "clean" after itself and their `enableBodyScroll` didnt work. 

1.3.15 should have the changes,
