### ISSUE TITLE
beforeOpen and beforeClose events are stacking

### ISSUE THREAD

**Issue by Cobs** [euvl/vue-js-modal#236]
Hi,
I'm used to encapsulate the modals into my own components to use them. But when I destroy one this component and mount it again later, it causes the events "before-open" and "before-close" to be emited multiple times. ( if i recreated my component 3 times, the events will be called 3 times ).
This only occur when the modal is recreated with the same name.

I watched the sources, and I think it's because the global listener on 'toogle' defined in the method beforeMount() in Modal.vue is not removed when the component is destroyed.

**Comment by sergomet** [comment]
Hi, I am facing same problem, any solution?

**Comment by Cobs** [comment]
I didn't find a elegant way to remove the listener from the document.
A lazy solution however is to use a randomly generated name for the modal name.

**Comment by sergomet** [comment]
Still not a solution, because I use the modal for some couple of tables filter (>10) and emitted events are increasing to much.

> A lazy solution however is to use a randomly generated name for the modal name.

@Cobs how do u open then the modal ? can u write a sample ? Thanks.

@euvl any solution? Thanks

**Comment by euvl** [comment]
Nope, I assumed someone would fix it. I'm afraid i don't have enough time to do it right now
