### ISSUE TITLE
Client version without CSS

### ISSUE THREAD

**Issue by kuhma** [euvl/vue-js-modal#240]
Hi,

Currently only SSR has a version with separated CSS.

It would be great to also have a client version without integrated CSS when using into an app:
* allows custom browser support
* styles could be properly overloaded
* global size would be reduced

Regards

**Comment by euvl** [comment]
So what is the difference between client and ssr versions without css? Have you tried ssr version?

**Comment by kuhma** [comment]
Hi,

I never tried this one before as it is flagged as "SSR".
I just tested and it looks good to me.

Thank you!
