### ISSUE TITLE
Best approach for pinning modal to top of viewport

### ISSUE THREAD

**Issue by cicsolutions** [euvl/vue-js-modal#241]
#### Problem: 
Would like to have the .v--modal container position:absolute, top: 0 always, but I'm not sure how to properly configure the modal to achieve this. 
...

#### Example & screenshots:
Initially, i thought this could be achieved by setting pivotY: 0 in the modal params, but depending on the height of the modal, on smaller screens having pivotY set to zero pushes the v--modal container up past the viewport.

Here's an example:
```
    <modal name="modal-name" adaptive width="100%" :maxWidth="900" :minHeight="700" :pivotY="0">

            <h1>Modal Heading</h1>

    </modal>
```

If you resize the height of your browser window with the modal open, eventually you will see the Modal Heading text slide up out of view.  I think this is because the pivotY is using percentages and eventually the modalStyle computed property will return top: with a negative value.  

Is there a way to avoid this behavior and just keep the v--modal container pinned to the top of the page/viewport?  If not, perhaps having modal params for pinTop and pinBottom would be good features to have.

Please let me know your thoughts and if I can help!  Thanks for making such a great tool!

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by 555ea** [comment]
I'm having the same issue with mobile devices when keyboard is shown
