### ISSUE TITLE
logo for vue-js-modal

### ISSUE THREAD

**Issue by worlwide** [euvl/vue-js-modal#243]
Hello there. I design a logo in my free time. I want to design a logo for you. What do you think ? I want to contribute you. Do you have an idea ?

**Comment by euvl** [comment]
Sure, feel free to give it a go 😄

**Comment by worlwide** [comment]
Could you give me information about vue-js-modal ? Or do you have an idea?

**Comment by euvl** [comment]
Seems like this is not happening
