### ISSUE TITLE
Modal width = "initial"

### ISSUE THREAD

**Issue by Sequoya42** [euvl/vue-js-modal#244]
#### Problem: 
There's a default style applied 
[Modal.vue]
` :style="modalStyle"`

```top: 0px; left: 0px; width: 600px; height: 300px;```

Width can be passed as props, but only as a number.

The validator is as follow: 

```export const validateNumber = (value) => {
  if (typeof value === 'string') {
    let _value = parseNumber(value)
    return (_value.type === '%' || _value.type === 'px') && _value.value > 0
  }
```

Which causes trouble, when I want to apply a `width="initial"`

...

#### Example & screenshots:

``` Invalid prop: custom validator check failed for prop "width". ```

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Modal **does not use css** classes for positioning & sizing. The fact that it supports anything except px is slightly taken for granted. Please use px / % / 'auto' .

**Comment by adamreisnz** [comment]
Curious why it doesn't support any other units.

Clearly at some point it's setting the style of the modal to the inputted width, so why not support `initial`, `auto`, `rem`, or `vw` units? Not very flexible at the moment.

**Comment by euvl** [comment]
Following your previous message @adamreisnz , and the 👎 , you are free to implement other units and i would be happy to review your PR. Personally, I find it super motivation when people just demand things without making a tiny bit of effort. Happy codding

**Comment by adamreisnz** [comment]
Thanks, yes I'm well aware of the fact that I can write code to fix a plugin that is missing features. I myself find it super motivating (not) when package maintainers tell everyone who raises a valid issue that they should go and make a PR. Not everyone has free time to spare to submit PR's for every single issue they encounter in 3rd party packages.

If you don't want to maintain the package yourself anymore and you can't be bothered to take feedback on board, that's fine, just mention that and we won't raise issues anymore.
