### ISSUE TITLE
How to responsive width ?

### ISSUE THREAD

**Issue by VCodepp** [euvl/vue-js-modal#247]
how to change modal width with window size 992px 768px and 480px  ?

**Comment by Rosinnovacii** [comment]
as for me i've just preffered to use relative witdh size
`width="80%" :maxWidth="480" :adaptive="true"`

**Comment by cooltolia** [comment]
as for me i've just preffered to use relative witdh size
`width="80%" :maxWidth="480" :adaptive="true"`
