### ISSUE TITLE
Add example showing passing values to a model via component

### ISSUE THREAD

**Issue by falconair** [euvl/vue-js-modal#248]
#### Problem: 
Can we please get an example geared toward novice Vue users.
For example, since most tutorials recommend .vue file based components, I'd like to encapsulate my modal in a .vue file as well.
I would like to pass a variable to this modal and inside the template, I'll use this parameter to adjust the fields in my form.

Currently I'm having trouble with how values are passed to the modal (via  `this.$modal.show('ModalName', {parameter: 'value'}`) vs passing properties to a component the vuejs way.

A simple two file example, one .vue containing modal template and a main.vue file which calls this modal will be extremely helpful.

**Comment by euvl** [comment]
There are 7 examples in the examples folder https://github.com/euvl/vue-js-modal/tree/master/demo/client_side_rendering/src/components/modals

```
this.$modal.show('ModalName', {parameter: 'value'})
```
This does not look like anything documented in README. Please use Readme for documentation.
