### ISSUE TITLE
overflow hidden on the modal box causes issues with dropdown menus on forms

### ISSUE THREAD

**Issue by corbosman** [euvl/vue-js-modal#250]
#### Problem: 

If you have a relatively small modal with a select box that has a dropdown, the dropdown will be cut off.

#### Example & screenshots:

![](http://shot.ter.net/img/2018/201806261236-79f4e46b2ad73d7916974eec886132e2.png)

The problem is caused by an overflow:hidden on the modal box. If I override that with visible it's fine.

**Comment by NguyenTheSon** [comment]
same issue

**Comment by euvl** [comment]
Hey, try removing overflow through CSS. it's is used for "draggable/resizable" features, but if you don't use those it should be fine.

**Comment by corbosman** [comment]
I said in my original issue that it's fine if I override overflow: hidden, so your question has been answered, you can fix this issue by overriding the css.

**Comment by euvl** [comment]
Cool 👍
