### ISSUE TITLE
strange timing/reactivity edge case

### ISSUE THREAD

**Issue by corbosman** [euvl/vue-js-modal#252]
#### Problem: 

I have a modal that does a vuex action. That action returns a promise that does an async api call, and a vuex state commit with the returned data. Then in the component with the modal I wait for the promise, and on success I hide the modal. All pretty standard stuff. 

The problem is, in this specific scenario, the modal and the overlay are no longer timed the same. The overlay fades much later than the modal, like a second or so later. Enough to make it look weird.  I tried to find a more minimal set of circumstances, but I cant really reproduce it with fewer steps involved.  It's something in this code:

```
        setTimeout(() => {
          this.visibility.overlay = false
          this.$nextTick(() => {
            this.removeDraggableListeners()
            this.callAfterEvent(false)
          })
        }, this.delay)
```
If I set the overlay visibility to false outside of the setTimeout, the problem disappears. The delay is set to 0, which i even double checked with a console.log. It think setTimeout puts the whole loop on the queue for the nextTick, then vue updates the state with my returned data, and the dom updates just take long enough for the overlay to seem "late" to disappear. I dont know what else it could be. 

I hotfixed this by just setting the visibility right in the component itself instead of calling hide on the modal.

```
                this.$refs.modal.visibility.modal = false
                this.$refs.modal.visibility.overlay = false
```

**Comment by euvl** [comment]
Sounds strange, let me know if you will be able to narrow down a problem.
