### ISSUE TITLE
Bug: Never goes to min-width

### ISSUE THREAD

**Issue by pmochine** [euvl/vue-js-modal#253]
#### Problem: 
My modal is set to these parameters.

    <modal 
         :width="'35%'" 
	:minWidth="425"
	:maxWidth="500"
	:adaptive="true"
	height="auto"
	:scrollable="true">

But it just does not matter if I set width to 1% it still goes to max-width of 500. That should not be the case it should go to 425. I think that should be a bug.

**Comment by euvl** [comment]
You should set it as `min-width` and `max-width` in vue.js
