### ISSUE TITLE
Question: How to open modal in external js file

### ISSUE THREAD

**Issue by kdankert** [euvl/vue-js-modal#255]
#### Problem: 
I have the problem that I built a front end user interface connecting to a rest API, I use Express and Passport.js with jsonwebtokens for that. In my external js file are the axios methods for sending request to the rest API. At this time when axios is getting a 401 request it should open the vue modal, I've created. It is an single component modal defined in App.vue. I've I import the App.vue in my js file `App.$modal.show(<nameOfTheModal>)`  I'll get the error:

> Failed to load resource: the server responded with a status of 401 (Unauthorized)
Auth.js?d1dd:13 Uncaught (in promise) TypeError: Cannot read property 'show' of undefined
    at redirectLogin

If I export the Vue instance in my file `Vue.$modal.show('demo-login')` the error 

> Uncaught (in promise) TypeError: Cannot read property '$modal' of undefined
    at redirectLogin
is shown up. 
I searched for solving that quite  while but haven't found anything, so I decided to ask you, if you know how to do that, as you created this plugin.

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
I don't think you can do it now, in nearest future `Vue.$modal.show('demo-login')`  will work.

**Comment by Max-LAB** [comment]
Hi all, I find this issue #255 from 2018. I also need this feature, but I really don't know if this is solved or not. If it is how to properly use it? 

In my project, I have error handling and I want to show error messages in modal. That is one use case, I also tried `Vue.$modal.show` but $modal is undefined
