### ISSUE TITLE
Changing the width not working as i want

### ISSUE THREAD

**Issue by Katerou22** [euvl/vue-js-modal#256]
I use dynamic modal like this: 

`<modals-container width="800" />`

And calling modal like this:

```
import createModal from './CreateModal.vue'
components: {createModal},this.$modal.show(createModal)
```

But width its 600!

**Comment by euvl** [comment]
I love the title of the issue 👍

**Comment by Katerou22** [comment]
Can u told me why it not changing?!

**Comment by Katerou22** [comment]
![gnome-shell-screenshot-egyulz](https://user-images.githubusercontent.com/21346372/42488850-ef1fd95a-841c-11e8-8d51-b36faccea796.png)
What is this?!

**Comment by euvl** [comment]
Learn to talk to people first.
