### ISSUE TITLE
Please add a separate escapeToClose option

### ISSUE THREAD

**Issue by jdmichel** [euvl/vue-js-modal#257]
Currently clickToClose controls two separate things, but often (always?) I would prefer to use clickToClose=false and escapeToClose=true, because it's too easy to accidentally lose all your work by accidentally clicking the background, but also annoying for many users to have to use the mouse to close the dialog.

**Comment by euvl** [comment]
Sorry, this will not happen. You can block "closing by clicking background" (look examples) and putting every tiny feature under flag seems wrong to me.
