### ISSUE TITLE
Not Nuxt SSR

### ISSUE THREAD

**Issue by mr-koww** [euvl/vue-js-modal#258]
How I can use this wonderful plugin with classic Vue SSR (https://ssr.vuejs.org) ?

**Comment by euvl** [comment]
Hey, take a look in readme pls 👍

**Comment by mr-koww** [comment]
Thank you @euvl 
I don't understand firstly
Works fine!

**Comment by euvl** [comment]
Awesome 👍 Happy to help 😄
