### ISSUE TITLE
height="auto" works but shows a warning

### ISSUE THREAD

**Issue by jmaister** [euvl/vue-js-modal#26]
I would like to use 'auto' for the height and it works. However, Vue shows a warning.

    [Vue warn]: Invalid prop: type check failed for prop "height". Expected Number, got String.
    found in
    ---> <VueJsModal>

**Comment by euvl** [comment]
Currently height and width should be numbers as far as "auto" will break resizing, dragging and positioning features.

**Comment by jmaister** [comment]
OK, I understand that.

I'll try this:
* Set height to auto.
* Measure hight with document.getElementsByClassName('v--modal-box')[0].offsetHeight
* Set the measurement as a Number

**Comment by jmaister** [comment]
It works!

```javascript
                // Set the height to auto and come back to number
                var self = this;
                setTimeout(function() {
                    const modalDiv = document.querySelectorAll('[data-modal="'+ self.name +'"] div.v--modal-box')[0];
                    modalDiv.style.height = 'auto';
                    const currentHeight = modalDiv.offsetHeight;
                    modalDiv.style.height = parseInt(currentHeight) + "px";
                }, 100);
```
