### ISSUE TITLE
Focus not being kept inside of modal

### ISSUE THREAD

**Issue by johnrossporter** [euvl/vue-js-modal#260]
#### Problem: 
The element focus can break outside of the modal for example by keyboard navigation. As can be seen in the example page, pressing tab or shift-tab enough and the focus will be outside of the modal. The expected behavior is that the focus should be contained within the modal(so the last focusable item wraps to the first and vice versa going backwards)

See the w3 example - https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

**Comment by euvl** [comment]
Thanks @johnrossporter, do you think you can create a PR with these accessibility improvements?

**Comment by trandaison** [comment]
Any idea for this?

Focusing outside the modal causes modals overleap and redirect while the modal is showing.
