### ISSUE TITLE
Allow multiple (named) dynamicContainers

### ISSUE THREAD

**Issue by akarelas** [euvl/vue-js-modal#262]
#### Problem: 

I have 2 modals as individual SFC component files that I want to show at different times (therefore must use this.$modal.show). Both have events I want to attach listeners to, therefore I must use different <modals-container @...> elements.

Problem is when the second such <modals-container> appears in the DOM, then Plugin.dynamicContainer gets set to the second one, and when the second such component disappearas, the first one doesn't become active again. So when I try to open the first modal it doesn't open at all.

Solution is not to create a stack of dynamicContainers and just choose the last one, because that would mean the user doesn't have the ability to choose which of the two modals to open.

The solution (to me) seems to be to create an object dynamicContainers, which map names to <modal-container name="..."> components. When the user tries to launch a modal without a name, dynamicContainer will be used. When they try to launch a modal with a name, then dynamicContainers[name] will be used.

I can provide patch if you need it.

...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by akarelas** [comment]
Maybe an even better solution would be to have only one modals-container element, without any @custom_event handles defined on the element, and where you'll be able to set custom event handlers like this:

```
this.$modal.show(
...
{
    modalEvents: {
        my_custom_event: x => this.doIt(x),
        another_event: x => this.doAnother(x),
    }
}
);
```

**Comment by euvl** [comment]
`modals-container`is just a container (like provider components in react). You need one per application so that plugin knew where to inject modals. 

I feel like you've misunderstood how this library works or I've misunderstood your use-case but why not to use just 2 normal (not dynamic, etc) modals?

**Comment by akarelas** [comment]
You asked "why..."

Because I want to have the modal window as a separate component... i.e. in a separate file, enclosed with its own HTML, CSS and JS.

Can your normal modals Inot dynamic, etc) do that?

**Comment by akarelas** [comment]
I will check in the evening.
