### ISSUE TITLE
Problem with multiple modals and sub-components

### ISSUE THREAD

**Issue by fusionsquare** [euvl/vue-js-modal#264]
First of all: Thanks for the great modal plugin. Long times searched for this! 

#### Problem: 

I created a project with posts that can have photos, comments. (Like the facebook timeline) 

Here is what i want to build: When i click on a photo, the modal will be open and shows the photo and loads the comments (of the photo) with ajax and my <comments> component. 

Every photo has its own modal at the time, but i want to use the "dynamic modal" way with vue-js-modal. Now, i try'd everything, but i don't know how to setup the component.

I've added the `<modals-container/>` and get this message: `[vue-js-modal] In order to render dynamic modals, a <modals-container> component must be present on the page`.

I also try'd the injectModalsContainer way, but it doesnt work.

```
 
import modal from 'vue-js-modal';
Vue.use(modal, { dynamic: true, injectModalsContainer: true });
```

Now i'am thinking, whats the best way so use vue-js-modal within my project? Can reuse the modal clean and simple or must i declare a modal for every photo? Which way will be the best?

Hope you can help!

Thanks!

**Comment by fusionsquare** [comment]
With some try's it works now. Awesome project, thanks a lot!

**Comment by euvl** [comment]
No problem 👍 Thanks 😄
