### ISSUE TITLE
Fullsize on mobile

### ISSUE THREAD

**Issue by fusionsquare** [euvl/vue-js-modal#268]
Hi,

i want to show the modal at 100% height and 100% width (fullscreen) on mobile devices. Is there any option to do that directly, or must i set custom media queries? 

Is that maybe a good feature to the project? I mean, fullscreen without border-radius seems very useful to me.

**Comment by euvl** [comment]
You can set `width="100%" height="100%"` 

Also, `border-radius` is just a CSS rule. Overriding it is 1 line of CSS...
