### ISSUE TITLE
@opened triggered twice

### ISSUE THREAD

**Issue by MiracleYF** [euvl/vue-js-modal#271]
I'm using the plugin with Nuxt(SSR) and wrap the modal inside one of my components, the problem is when I open the modal, the @opened function triggered twice. AND the wired thing is, only first time I open the modal, @opened triggered twice. After the first time, everything works as expected.

Any suggestions? Thank you for this wonderful phugin.

**Comment by MiracleYF** [comment]
found problem, it is not related to modal. It is because one of my component(no ssr support) get rendered in server, and it cause the page re-rendered, since dom in client side doesn't math the dom in server.

**Comment by euvl** [comment]
👍
