### ISSUE TITLE
How to set width to auto?

### ISSUE THREAD

**Issue by inquiloper** [euvl/vue-js-modal#273]
I see that the width of every modal is hard-coded to 600px. How do I set it to auto for responsive stuff? 

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by stedotmartin** [comment]
Also looking for a solution to do this.

**Comment by euvl** [comment]
You can set width with %. Like `width="30%"`. Plugin cannot know what is your definition of responsive, sou you have to define it yourself.

For example: `:min-width="320" width="50%"`

**Comment by adamreisnz** [comment]
Why no width: 'auto', and have it grow to the size of the content?

**Comment by euvl** [comment]
Thanks, @adamreisnz for explaining what width:auto is 😄 You are free to implement it and would be very happy to review your PR 👍

**Comment by adamreisnz** [comment]
Point in case, sarcasm instead of constructive discussion, excellent package maintainer.
