### ISSUE TITLE
Modal not show in Mobile Res: Modal Location (Top and Left) always getting futher when using plugin Swiper! 

### ISSUE THREAD

**Issue by dionfananie** [euvl/vue-js-modal#275]
#### Problem: 
Modal not show: Modal Location (Top and Left) always getting further when using plugin Swiper! 

when i using swiper, and change to the mobile responsive width, Modal not show, when i inspected, it getting Top and Left Further,

#### Example & [screenshots:](url)

[SOLVED]

you can change the modals css into : 
```
v--modal-background-click{
  display: flex ;
 justify-content: center ;
 align-items: center ;
}
  .v--modal-box{
        top: 0 ;
        left:0 ;
    }
...
```

**Comment by euvl** [comment]
Well done 👍
