### ISSUE TITLE
Slot not works in Custom modal

### ISSUE THREAD

**Issue by dvasyliev** [euvl/vue-js-modal#276]
#### Problem: 
When I use my custom popup and try to use slots, they do not work

#### Example & screenshots:
```
<template>
  <div class="my-popup">
    <div slot="top-right" class="my-popup__close">Close button</div>

    <div class="my-popup__content">My popup content</div>
  </div>
</template>
```

and after that use it like
```
import MyPopup from 'src/my_popup.vue'

export default {
...
  mounted() {
    const props = { ... }
    const options = { ... }

    this.$modal.show(MyPopup, props, options)
  }
}
```
I see button in **my-popup** container, not in **v--modal-top-right**

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
I think it was renamed from "slot" to smth else in latest vue versions.

**Comment by Ainaras** [comment]
I have the same issue. 
With `Vue.use(VModal, { dynamic: true, injectModalsContainer: true });` I can't use  `<slot name="top-right"/>`...

**Comment by TheCelavi** [comment]
Why is this closed? Is it fixed or...?
