### ISSUE TITLE
Prevent closing on click outside

### ISSUE THREAD

**Issue by nicolasvahidzein** [euvl/vue-js-modal#279]
Hello, is it possible to prevent closing by clicking outside? Like you can do with sweet alert?

I want to close only if the user clicks on the button. Thank you.

PS: your module is simply awesome!!!

**Comment by molobala** [comment]
Just add `clickToClose: false` to modal props.

**Comment by nicolasvahidzein** [comment]
Thank you i was coming back to see that i had an old version, i updated after seeing you had the new method in your docs. Thank you Molobala as well!!
