### ISSUE TITLE
Draggable true and editor issues

### ISSUE THREAD

**Issue by riksnelders** [euvl/vue-js-modal#28]
Using a WYSIWYG editor inside modal, unable to focus when modal is draggable.

**Comment by euvl** [comment]
Hey @riksnelders , I forgot to explain in the docs, `draggable` can be `Boolean` or `String`. 
So what you need is to specify a css selector in draggable specifying an element which will be a "handler" for dragging. 

Example: 
```
<modal name="foo" draggable=".my-handler">
  <div class="my-handler>DRAG ME HERE</div>
  <div>
      SOME OTHER STUFF HERE
  </div>
</modal>
```

Let me know if it worked for you

**Comment by riksnelders** [comment]
:draggable="'.my-handler'" doesnt seem to make it draggable tho

**Comment by euvl** [comment]
No problem :)

**Comment by euvl** [comment]
Just have updated the documentation with the example :)
