### ISSUE TITLE
When transition is ended the container calculates a new position (makes a little jump)

### ISSUE THREAD

**Issue by pmochine** [euvl/vue-js-modal#281]
#### Problem: 

If you use this:

```
.fade-modal-enter-active,
.fade-modal-leave-active {
  transition: transform 0.5s; //if you use all it is going to be super weird
}
.fade-modal-enter,
.fade-modal-leave-active {
  opacity: 0;
  transform: scale(1.1);
}
```
and transition="fade-modal" you will see the last ugly "pop".

**Comment by euvl** [comment]
I was not able to replicate it.

**Comment by rang-ali** [comment]
Try to set the the overlay transition to the same duration as your "fade-modal"-transition, 0.5s in your case.
The default overlay transition is 'overlay-fade'.
