### ISSUE TITLE
Transition jumps from button to top first time, but should jump from top to bottom

### ISSUE THREAD

**Issue by pmochine** [euvl/vue-js-modal#282]
#### Problem: 
![ezgif-2-c9c924edeb](https://user-images.githubusercontent.com/25006691/43419500-58681ae2-9441-11e8-8f64-cd1482d05d07.gif)

#### Example

http://vue-js-modal.yev.io/

**Comment by euvl** [comment]
Probably some issue with the demo. Feel free to look into it 👍

**Comment by pmochine** [comment]
@euvl sorry I was not really descriptive here. I have the same issue on my page with my modal. So that is why I wanted to show you that you have the same bug. I could not find out why it is so.

**Comment by euvl** [comment]
Ah, thanks, I've misunderstood. I will take a look, can send the css of your transition pls

**Comment by pmochine** [comment]
@euvl So I used your "css" transition="nice-modal-fade".

And I have created a vue template like:

```
<modal-wrapper :name="name" @before-close="redirect" >
//some content
</modal-wrapper>
```

And calling it like this:

    //ModalWrapper.vue
     <modal 
		:adaptive="true"
		:name="name"
		height="auto"
		:width="isMobile ? '100%' : '45%'" 
		:minWidth="isMobile ? 310 : 425"
		:maxWidth="isMobile ? 750 : 450"
		:scrollable="true"
		transition="nice-modal-fade"
		classes="v-modal osans rounded"
		@before-close="$emit('before-close')"
	>
	
		<div tabindex="-1" role="dialog" @click="$modal.hide(name)">

			<div v-if="closeButton" >
				<button type="button" class="position-absolute text-secondary close closeButton" aria-label="Close" @click="close">
		        	<span aria-hidden="true">&times;</span>
		    	</button>
		    </div>

			<div class="modal-document" role="document" @click.stop>

				<slot></slot>

		  	</div>

		</div>

	</modal>

**Comment by pmochine** [comment]
I found out what the problem is!

It's only when height is set to auto!
