### ISSUE TITLE
Dynamic modal cause IE 11 not responding (crash)

### ISSUE THREAD

**Issue by wasichris** [euvl/vue-js-modal#283]
#### Problem: 
I found top position keep changing will be the reason to cause IE not responding (crash). Could you simply add parseInt() on top value to avoid it? or other better solutions?

#### Example & screenshots:
The top value keep changing as below.
![watch 103](https://user-images.githubusercontent.com/12275870/43436333-9ac4dfae-94b6-11e8-879a-40037b8ca58b.gif)

**Comment by euvl** [comment]
This is weird 😄
