### ISSUE TITLE
cannot access document inside modal

### ISSUE THREAD

**Issue by nicolasvahidzein** [euvl/vue-js-modal#286]
Hello,

am i doing it wrong in accessing the DOM?

when i try to access an element using this method i get a null error:

			var div = document.createElement('div')
			document.getElementById('croppieContainer').append(div)

[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'style' of null"

I hope i can get this to work because i spent 4 weeks on this module and it needs to work with me accessing the DOM.

Thank you for your help.

**Comment by euvl** [comment]
Please read vue.js documentation to find an answer. It is not related plugin
