### ISSUE TITLE
Allow import of individual components

### ISSUE THREAD

**Issue by maritaria** [euvl/vue-js-modal#287]
#### Problem: 
All components of this package get installed 'globally' on Vue by default with no other option available.
Please allow to only install '$modal' and leave out the components.
You could achieve this by exporting the relevant components as named exports.

```javascript
export default install()
export {ModalsContainer}
export {Modal}
```
```javascript
// vue component
export default {
    components: {
        ModalsContainer,
        Modals
    }
};
```
I would like this because then each component I make in my project can import the relevant modals and the dependency gets ensured by the babel compiler because the component won't compile if the package is missing, without having to perform configuration because using dynamic modals isn't part of the components scope but rather the applications scope. If I can only specify the dependency to vue-js-modal at the application level then the individual component doesnt show its dependency throug the import list (as I would like to).

**Comment by euvl** [comment]
For plugin to actually work you need all components that are provided by plugin
