### ISSUE TITLE
Add prop overlay-class

### ISSUE THREAD

**Issue by DenniLa2** [euvl/vue-js-modal#288]
Hello
thanks for vue-js-modal!

Add please props 'overlay-class' to change overlay. In my app me need some modals with one overlay and others with other. I do not want to find and add a class through querySelector.

Sorry for my english )

**Comment by euvl** [comment]
<img width="1033" alt="screen shot 2018-08-15 at 17 40 35" src="https://user-images.githubusercontent.com/1577802/44160454-5bd35700-a0b2-11e8-9a1b-615c725d9837.png">

Please read the documentation carefully next time.
