### ISSUE TITLE
Can't close modal if 2 tabs are opened

### ISSUE THREAD

**Issue by HKskn** [euvl/vue-js-modal#29]
It appears only opened new tab by main tab. I will tell you step by step above.
1- activate your modal and don't close
2- open new tab by your site
3- click something on your page by you opened in new tab
4-return your first opened site where you activated your modal
5- just try to close modal
6- you will see that you can't close it :/

**Comment by euvl** [comment]
Works for me

**Comment by euvl** [comment]
Which browser tho?

**Comment by HKskn** [comment]
google chrome

**Comment by euvl** [comment]
I am afraid I cannot replicate this bug
