### ISSUE TITLE
Bug? You cannot use v-dialog or modals-container at the same time

### ISSUE THREAD

**Issue by pmochine** [euvl/vue-js-modal#292]
#### Problem: 

Interestingly I found this bug. I needed to use v-dialog, but v-dialog did not show up in the vue chrome extension. 

First it was like:

    <modals-container /> 

    <v-dialog/>

I just saw ModalsContainer, but just as a joke I changed the order

    <v-dialog/>

    <modals-container /> 

Now dialog VueJsDialog appears and ModalsContainer is gone.

I wonder why is it like that?

Setup:
  
    import VModal from 'vue-js-modal';

    Vue.use(VModal, {
      dialog: true,
      dynamic: true,
    });

If you need screenshots I can provide them for you.
Btw I feel sorry that I created another issue! But I think everyone needs to know...

**Comment by euvl** [comment]
I think that v-dialog already adds modal-container and modal-container tends to be singleton.

**Comment by pmochine** [comment]
Thank you for your fast answer!
I get the error:

    [vue-js-modal] In order to render dynamic modals, a <modals-container> component must be present on the page. 

The only way how I can use both is with: injectModalsContainer: true
