### ISSUE TITLE
Jest shows warning about unregistered component

### ISSUE THREAD

**Issue by rajastakilos** [euvl/vue-js-modal#293]
#### Problem: 
I am currently using VueJS Modal with the following options:
1. In main.js
```
Vue.use(VModal, { dynamic: true, injectModalsContainer: false })
```

2. In my Vue:
I am adding a custom element to represent the modals container:

```
<modals-container/>
```

The modal works, but the problem is I'm getting error warnings when I run my tests with Jest:

```
      [Vue warn]: Unknown custom element: <modals-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

      found in

      ---> <Main>
             <Root>
```
I know why this is happening (since modals-container is not a registered component), but I don't know how to change my setup to get rid of these errors, and keep the modal working. 

I realize I can simply change injectModalsContainer to true, and remove ``` <modals-container/> ```, but then I have a second issue arise, namely that my getters don't work inside my modal. I need them to work because I trigger some functionality based on a value coming from state.  

If there is a reason why getters won't work with injectModalsContainer: true, it would be good to know, but I'm really just interested in knowing how to register my component in such a way that I don't see those errors in Jest anymore.

**Comment by rajastakilos** [comment]
Solved my own question. I just needed to stub the components in my tests.

**Comment by Joris-Fonck** [comment]
How did you stub it exactly? What is the name of the component?
