### ISSUE TITLE
Transition of the overlay is killing any transitions longer than 0.2s

### ISSUE THREAD

**Issue by pietromanneschi** [euvl/vue-js-modal#294]
Hello,

#154  trouble getting custom transition to work on modal.hide

resurrecting this post as i'm having the same issue. As @gaetansenn said, the transition on the child part of the modal gets cut because the overlay has this code:
```
<transition name="overlay-fade">
   <div v-if="visibility.overlay"
```
and overlay-fade is defined directly in the single file component Modal.vue :

```
.overlay-fade-enter-active,
.overlay-fade-leave-active {
  transition: all 0.2s;
}

.overlay-fade-enter,
.overlay-fade-leave-active {
  opacity: 0;
}
```
so i can't apply transitions that are longer than 0.2s. Any idea how can i overwrite this without branching the repo?

**Comment by euvl** [comment]
Hey, just create a PR and make `overlay transition` configurable (don't forget to default it to existing one.

**Comment by euvl** [comment]
Merged @pietromanneschi 's PR. Will release a new version in the end if this or next week 👍
