### ISSUE TITLE
IE minimizes when opening a modal

### ISSUE THREAD

**Issue by VictorCazanave** [euvl/vue-js-modal#298]
#### Problem: 
It's a very specific bug that happens :
* in IE (11)
* only 1 tab open
* app in an iframe (in my case)

When clicking on a button to open a modal, the browser minimizes.

#### Example & screenshots:
It's a bit hard to give a simple example but if really needed, I'll try to do it.

Here is how I analyzed this bug:
1.  The only [stackoverflow post ](https://stackoverflow.com/q/3586139) I've found mentions an issue when calling `activeElement.blur()` or `document.body.blur()`.
1. I looked in my code and I didn't find anything like that.
1. I looked in my dependencies code and I found [this line](https://github.com/euvl/vue-js-modal/blob/13499d37d2a8e528c7fbff3b9fa768a471550196/src/Modal.vue#L449).
1. I tried a quick fix adding the condition `document.activeElement.nodeName !== 'BODY'` and it worked. It seems there is no problem with the keypress events (mentioned in the comment).

I can make a PR, if you agree with this fix.

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
lol, IE does not stop surprising me.  Sure, please feel free to create PR if it fixes this issue.

**Comment by VictorCazanave** [comment]
Thanks for your quick reply @euvl !

Actually I noticed this bug doesn't happen the first time I open the page containing the modal.
I think the problem is that a "toggle" event listener is added every time the component is mounted (in `beforeMount()`) but never removed (in `beforeDestroy()`).
So`toggle()` is called many times with the same parameters.
The first time the `activeElement` is the button to open the modal, but after `blur()` the `activeElement` becomes the body and the magic of IE happens 🌈

As you can see in https://github.com/euvl/vue-js-modal/pull/299, my solution to remove the event listener is to use named events.
If you have a better idea, let me know and I'll update my PR.

**Comment by euvl** [comment]
Tbh I am quite happy with your approach 👍 , I will just need to check if it possibly could break other functionality.
