### ISSUE TITLE
Modal with the same name in 2 different pages does not open

### ISSUE THREAD

**Issue by VictorCazanave** [euvl/vue-js-modal#300]
#### Problem: 
Version: 1.3.20 

When switching between 2 `<router-view/>` that both contain a modal with the same name, the modal doesn't open.

I think it's because in vue-router the next component is created first, then the previous one is destroyed.
I haven't found any official documentation but I tested it with `console.log()` and [this post](https://stackoverflow.com/q/51678395/9826498) confirmed it.
So in `Modal.vue`, `beforeMount()` of the 2nd page's modal is called before `beforeDestroy()` of the 1st page's modal and the event listener is finally removed because the modals have the same name.

I'm actually not sure this is a bug 🤔 
Maybe using 2 modals with the same name is a bad practice (although it's in 2 different pages)?
If yes, it would be interesting to add it in the documentation.
If no, I don't know how to fix it 😄

**Comment by euvl** [comment]
Modals should have unique names

**Comment by euvl** [comment]
I think it used to work with the previous event handling (when modals were receiving all show/hide events and just picking up what they need).

I'm not sure if I can fix it. I could probably enforce uniqueness of names per application (don't really like this idea)

**Comment by VictorCazanave** [comment]
Yes, it used to work in previous version (sorry 👼 )
Personally I don't mind to give a unique name but I think it would be good to write it in the doc.

**Comment by euvl** [comment]
If you have time, please test the latest master. I might have fixed the regression in event listening + kept event unsubscribing. I do not have windows computer though so cannot test in IE.

**Comment by VictorCazanave** [comment]
It seems to work well! 
- no problem in IE
- no problem with same modal's name in different pages
- I also did some debugging and `toggle()` is always called once, so there is only one event listener per modal 👍 

I'm curious about your solution 😃 
Does it work because the `handleToggleEvent()` method is unique in each modal instance, so it only removes the event listener of the destroyed modal?
