### ISSUE TITLE
ssr - ReferenceError: window is not defined

### ISSUE THREAD

**Issue by mikerogerz** [euvl/vue-js-modal#301]
#### Problem: 

Regarding version 1.3.22, with no changes to my code. Being used in SSR app.

ReferenceError: window is not defined

vue-js-modal/dist/ssr.nocss.js:85

`if (name in window) return window[name];`

#### Example & screenshots:

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Added a guard, should work now in 1.3.23

**Comment by larsjanssen6** [comment]
This problem is still there.

**Comment by jellevandevelde** [comment]
Facing the same problem too with the latest version

`    "nuxt": "^2.0.0",
    "vue-js-modal": "^2.0.0-rc.3",
`

**Comment by Patryk-Szylin** [comment]
Facing the same problem. Does anyone know a workaround?

**Comment by jellevandevelde** [comment]
I had to downgrade to version `"vue-js-modal": "1.3.31",` to get it to work like outlined in the Nuxt example

**Comment by defcom20** [comment]
Para los que usan Nuxtjs : Agreguen mode: 'client' -> a mi me funciono.
plugins: [
    { src: '~/plugins/vue-js-modal', mode: 'client' }
  ],

**Comment by andynunes** [comment]
> Para los que usan Nuxtjs : agrega mode: 'client' -> a mi me funciono. plugins: [ { src: '~/plugins/vue-js-modal', mode: 'client' } ],

For those still running into this, adding `mode: 'client'` worked for me as well.
