### ISSUE TITLE
computed modalStyle Top miscalculation

### ISSUE THREAD

**Issue by bendo01** [euvl/vue-js-modal#302]
#### Problem: 
After Update from version 1.3.18 to version 1.3.23, computed modalStyle Top miscalculation on first call, after i resize my browser window then modal placed on center screen, Being used in SSR app with nuxt

**Comment by euvl** [comment]
Probably its due to Mutation Observer being moved to utils.

**Comment by mijgame** [comment]
Noticing the same thing; the positioning on first opening is wrong. Removing `height="auto"` corrects the positioning, but that isn't really a workaround.

**Comment by euvl** [comment]
Check 1.3.24 pls

**Comment by mijgame** [comment]
Tested 1.3.24, it didn't fix it I'm afraid.

**Comment by euvl** [comment]
Then i don't really know what is going on >_<. WIll try to investigate.

**Comment by crnkovic** [comment]
Same thing here, removing `height="auto"` fixes it. Hopefully the bug is found soon! :)

**Comment by ta-os** [comment]
The bug is not fixed in the safari
