### ISSUE TITLE
Typescript error in using vue-js-modal/dist/ssr.index

### ISSUE THREAD

**Issue by KleinMaximus** [euvl/vue-js-modal#303]
#### I get an error
```
Could not find a declaration file for module 'vue-js-modal/dist/ssr.index'.
'/home/user/frontend/node_modules/vue-js-modal/dist/ssr.index.js' implicitly has an 'any' type.
Try 'npm install @types/vue-js-modal' if it exists or add a new declaration (.d.ts) 
file containing declare module 'vue-js-modal';
```

in the code (index.ts)
```
import Vue from 'vue';
import VModal from 'vue-js-modal/dist/ssr.index';

Vue.use(VModal, { dynamic: true, injectModalsContainer: true });
```

When I try to declare the `vue-js-modal/dist/ssr.index` module, I get an error:

`Invalid module name in augmentation. Module 'vue-js-modal/dist/ssr.index' resolves to an untyped module at '/home/user/frontend/node_modules/vue-js-modal/dist/ssr.index.js', which cannot be augmented.`

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
I a m not using typescript so if you will be able to fix it - go for it 👍

**Comment by euvl** [comment]
Assuming that there was no action, i am closing this issue

**Comment by dhritzkiv** [comment]
I was able to solve this for myself by creating a new file in my declarations direction (./declarations/vue-js-modal/index.d.ts) that simply re-exports the base module:

```ts
declare module "vue-js-modal/dist/ssr.index" {
	import VueJSModal from "vue-js-modal";
	
	export default VueJSModal;
}

```

**Comment by robaxelsen** [comment]
> I was able to solve this for myself by creating a new file in my declarations direction (./declarations/vue-js-modal/index.d.ts) that simply re-exports the base module:
> 
> ```ts
> declare module "vue-js-modal/dist/ssr.index" {
> 	import VueJSModal from "vue-js-modal";
> 	
> 	export default VueJSModal;
> }
> ```

Hi @dhritzkiv. How did you make this work?

I added the declaration above as file `~/declarations/vue-js-modal/index.d.ts`. That part is working, as my IDE stopped complaining.

But then I am adding the following to a plugin that I am importing in `nuxt.config.js`:

```
import Vue from 'vue'
import VModal from 'vue-js-modal/dist/ssr.index'

Vue.use(VModal)
```

And I get the following error:
```
 ERROR  ERROR in /home/rob/code/red-bull-media-house/rb-event-wizard/node_modules/vue-js-modal/types/index.d.ts(1,69):
1:69 Cannot find module 'vue'.
  > 1 | import Vue, { PluginObject, ComponentOptions, AsyncComponent } from "vue";
      |                                                                     ^
    2 | 
    3 | declare const VueJSModal: PluginObject<VueJSModalOptions> & {
    4 |   rootInstance?: Vue
```

**Comment by dhritzkiv** [comment]
My nuxt plugin for vue-modal looks similar to yours:

```ts
import Vue from "vue";
import VModal from "vue-js-modal/dist/ssr.index";
import "vue-js-modal/dist/styles.css";

Vue.use(VModal);
```

with the exception that I'm also importing css, but that should have no effect on importing the TS code.

---

I'm not sure why you're having issues with importing vue-modal or vue. Could it be a tsconfig issue?

Here's mine:

```json
{
  "compilerOptions": {
    "target": "es2019",
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "lib": [
      "esnext",
      "esnext.asynciterable",
      "dom"
    ],
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "jsx": "preserve",
    "sourceMap": true,
    "strict": true,
    "noImplicitAny": true,
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "skipLibCheck": true,
    "baseUrl": ".",
    "types": [
      "@types/node",
      "@nuxt/types",
      "simplytyped"
    ],
    "typeRoots": [
      "./declarations",
      "./node_modules/@types"
    ],
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"],
      "~~/*": ["./*"],
      "@@/*": ["./*"]
    },
    "allowJs": true
  }
}

```

**Comment by rommyarb** [comment]
> I was able to solve this for myself by creating a new file in my declarations direction (./declarations/vue-js-modal/index.d.ts) that simply re-exports the base module:
> 
> ```ts
> declare module "vue-js-modal/dist/ssr.index" {
> 	import VueJSModal from "vue-js-modal";
> 	
> 	export default VueJSModal;
> }
> ```

Thank you. I need to restart VSCode after creating this file. Now it works 👍
