### ISSUE TITLE
Extracting CSS from component using mini-css-extract-plugin

### ISSUE THREAD

**Issue by willjosefi** [euvl/vue-js-modal#307]
#### Problem: 
I'm using mini-css-extract-plugin to extract all CSS from the Vue components
But CSS from vue-js-modal are not being "extracted"
Other components, like vue2-google-maps (in the same project) CSS are being extracted to a separate file normally.

...

#### Example & screenshots:
I created a empty repository with the plugin and my configuration to extract CSS.
You can see that styles from Example component are extracted to dist/style.css
But the vue-js-modal CSS continue inside bundle.js
https://github.com/willjosefi/test-vue-js-modal-css
To run/compile
npm install
npm run production

...

* I saw the SSR version without CSS. But i'm not using SSR

**Comment by euvl** [comment]
SSR version without CSS, is a normal version, but that also works on SSR. You can freely use it any project.
