### ISSUE TITLE
vue-js-modal - “draggable” issue

### ISSUE THREAD

**Issue by soringabrielvasiliu** [euvl/vue-js-modal#310]
#### Problem: 

Hi,
I am using [vue-js-modal](https://github.com/euvl/vue-js-modal) to display a draggable and resizable modal but I have an issue with "draggable" property.

The modal is opening and all properties work properly except "draggable"; I can not drag the modal (seems to have no effect). This is how I set up the modal:

```
  <modal class="vue-js-modal"
      name="modal-name"
      :draggable="true"
      :resizable="true">

    <h1>Modal Title</h1>

  </modal>
```

**Comment by rickyruiz** [comment]
It might be [this](https://github.com/euvl/vue-js-modal/commit/79829041541c1489ed92506f6f3fd6ab40db6e56) commit, which moved `this.addDraggableListeners()` to `beforeTransitionEnter` instead of leaving it in `afterTransitionEnter`.

**Comment by rickyruiz** [comment]
This is working with the latest commit! Should be closed. @euvl @soringabrielvasiliu
