### ISSUE TITLE
Property "max-height" and "max-width" doesn't work 

### ISSUE THREAD

**Issue by juan2nolasco** [euvl/vue-js-modal#312]
Hi !!
I am using vue-js-modal to display a resizable modal, I set the properties max-height and max-width to 500 but this values aren't taken, when i change the size of the modal, width and height it can be bigger than 500 and i want that the maximum value when the modal is resized be 500 (seems take the default value).
also I'm using the properties min-height and min-width and this are working perfectly.  My code is shown below:

      <modal classes="demo-modal-class" :adaptive="true" :resizable="true" :min-width="350" :min-height="200" :max-width="500" :max-height="500" class="modalSize" :draggable="true" name="hello-world">
        <span slot="modal-title" class="modal-title">
        <i class="fa fa-file-image-o" aria-hidden="true"></i> Cambiar enlace
        </span>
        <b-container>
          <div class="link">
            <form action="" class="link__form">
              <input type="text" class="link__input" v-model="text" @keyup="saveText">
              <input type="text" class="link__input" v-model="href" @keyup="saveHref">
              <button type="button" class="link__btn" @click="closeModal">
                Cerrar<i class="fa fa-search"></i>
              </button>
            </form>
          </div>
        </b-container>
      </modal>

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
looks like it should work, i will take a look
