### ISSUE TITLE
modal's width has a lower bound

### ISSUE THREAD

**Issue by kraxner** [euvl/vue-js-modal#315]
#### Problem: 

The calculation of the modal's width imposes a lower bound, eventhough adaptive: true or width: 100% is used.
This is a problem especially on devices with a low screen width, as it leads to an overflow.

#### Example & screenshots:
1. http://vue-js-modal.yev.io/
2. using chrome: switching to development console: opening device toolbar - select responsive
3. opening modal  "Adaptive" 
here the minimum width is 295px - in my application it is 360px, which is more of a problem with mobile phones of smaller screen widths

this is probably related to #312 and #224 

```
<div class="v--modal-box v--modal" style="top: 334px; left: 0px; width: 295px; height: 300px;"><div class="example-modal-content">
...

```
![vue-js-modal-width](https://user-images.githubusercontent.com/631718/45414874-9bbf3700-b67c-11e8-8ba6-7037c4525901.JPG)

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by kraxner** [comment]
in case of Chrome - device toolbar this is due to window.innerWidth, which delivers a min value of 295px (/360px)

**Comment by euvl** [comment]
This library is designed with an emphasis on common sense. For example ti does not cover a case with 205px (!!!) screen width.

**Comment by kraxner** [comment]
> This library is designed with an emphasis on common sense. For example ti does not cover a case with 205px (!!!) screen width.

I am totally aware that 205 or even 295px would not cause real problems, in my case the min width was 360px, and there are still phones with a screen width of 320px. 

But as the example to reproduce it is not valid, never mind.
Anyway, it is a very nice component!

**Comment by euvl** [comment]
Thanks 😄
