### ISSUE TITLE
How to test modal-component

### ISSUE THREAD

**Issue by DenniLa2** [euvl/vue-js-modal#318]
#### Problem: 
I don`t understand, how to testing modal-component

#### Example & screenshots:
My modal-test component:

    <template>
      <modal name="modal-test">
        <div class="modal-test__content">I am modal</div>
      </modal>
    </template>
    <script>
      export default {
        name: 'modalTest',
      };
    </script>

My unit-test:

    import { expect } from 'chai';
    import { mount, createLocalVue } from '@vue/test-utils';
    import ModalTest from '@/modal/modalTest.vue';
    import VModal from 'vue-js-modal';

    const localVue = createLocalVue();
    localVue.use(VModal);

    describe('ModalTest.vue', () => {
      it('modal', () => {
        const wrapper = mount(ModalTest, {
          localVue,
        });
        expect(wrapper.find('.modal-test__content').exists()).eq(true);
      });
    });

Tell me pls, how can I test exists div.'modal-test__content' inside modal?

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by VictorCazanave** [comment]
Here is how I test my modals:
1. Create a custom stub for modal:
```javascript
VueTestUtils.config.stubs = {
  modal: '<div class="stub-modal"><slot/></div>'
};
```
The `<slot/>` will be replaced by your modal content.

2. Tests the content of the modal:
```javascript
import { shallowMount } from '@vue/test-utils';
import MyModal from '@/my-modal';

describe('MyModal', () => {
  const wrapper = shallowMount(MyModal);

  it('test the content of the modal', () => {
    // ...
  });
});
```

**Comment by seyfer** [comment]
@VictorCazanave that is not working in this case
`this.$refs.modal.updateRenderedHeight is not a function`

so only normal `mount` works

**Comment by WieFel** [comment]
The following solution works for me in Vue 2 (jest) for `v-dialog`.

1. Use this in the test stubs:
```ts
stubs: {
      VDialog: {
        name: 'VDialog',
        template: '<div class="v-dialog-stub"><slot /></div>',
        props: ['modelValue'],
      },
}
```

2. Trigger the dialog in the test, wait for nextTick:
```ts
it('Modal dialog test', async () => {
    const wrapper = mount(MyComponent, options);  // options = test options, including (1.)

    const dialogTrigger = wrapper.find('.my-dialog-trigger');
    dialogTrigger.trigger('click');

    await Vue.nextTick();
    const dialog = wrapper.find('.v-dialog-stub');
    expect(dialog.exists()).toBe(true);
  });
```

**Comment by tsung-jen1503** [comment]
@WieFel Hello, perhaps my question is basic and silly. But may I ask where you put the test stubs? Probably in the vitest.config.js file? Thank you for your help.

**Comment by WieFel** [comment]
@tsung-jen1503 no worries.

You add it to the `options` which you pass to the `mount` call:
```ts
const options = {
    vuetify: new Vuetify(),
    store,
    stubs: {
      ... // add your stubs here
    },
}
```

```ts
const wrapper = mount(MyComponent, options);
```
