### ISSUE TITLE
Top-right slot position

### ISSUE THREAD

**Issue by OmgImAlexis** [euvl/vue-js-modal#32]
Currently the top-right slot doesn't get any CSS applied to it. It'd be nice by default if it was positioned at the top right of the modal instead of the top right of the page.

![screen shot 2017-06-14 at 4 58 59 pm](https://user-images.githubusercontent.com/6525926/27120466-d8d0a892-5122-11e7-936e-3a7653beb7cb.png)

**Comment by euvl** [comment]
Yes, because everyone wants a different thing to be there, so you will have to implement your close button yourself.

I think the default is good enough. 

The corresponding class name is `.v--modal-top-right`. As the simplest solution, you can overwrite position in your code like this:

```
.v--modal-top-right {
    right: where_i_want_it_to_be px !important;
    top: where_i_want_it_to_be px !important;
  }
```

**Comment by OmgImAlexis** [comment]
What I was thinking instead is to just add another slot called "close button" that way for people that want to add a close button it's already positioned correctly in relations to the box. You shouldn't really have to override CSS to add an expected feature for a modal.

**Comment by euvl** [comment]
I will be happy to review a PR

**Comment by vesper8** [comment]
I must be missing something.. it seems the top-right slot is not at the right dom level. It should be relative to the modal window not the modal overlay?

If it's relative to the overlay then I don't know how we can tie it to the top-right corner of the model without using some javascript

I think the "default top right" for most cases is having it attached to the window.. not the absolute top right of the page as it is now..

**Comment by euvl** [comment]
Hey @vesper8, sure i can comment:

> I must be missing something.. it seems the top-right slot is not at the right dom level. It should be relative to the modal window not the modal overlay?

Nope, I think that it is in the right spot. Positioning elements relatively to modal is easy (you can use css relative parent/absolute child pattern.

> If it's relative to the overlay then I don't know how we can tie it to the top-right corner of the modal without using some javascript

Not to be rude, but I see no problem in here. I assume you are getting paid for this so writing a couple of lines of javascript ( < 5 ) should not be a problem.

> I think the "default top right" for most use-cases is having it attached to the window.. not the absolute top right of the page as it is now..

Which use-cases though? If you will look at facebook and twitter, they have the same layout (my projects also required same positioning).

>  I want the X button to be attached to the top right corner of the modal window.. how do I achieve this?

Position <button/> absolutely to right:-50px, top:-50px and set it's size to 50x50, make parent relative.

Thanks 👍

**Comment by felipeegasneris** [comment]
the solution to fit the close button to modal window is:

`<modal
        adaptive
        :name="modalSettings.name"
        :width="modalSettings.width"
        :height="modalSettings.height"
        :scrollable="modalSettings.scrollable"
      >
        <div class="quotation-container">  // this is the important a div container to slot an content
          <div slot="top-right">
            <button @click="$modal.hide('quotation-modal')">
              ❌
            </button>
          </div>
          <the-quotation :ad-data="adData" />
        </div>

      </modal>`


and this is the result:
![captura de pantalla 2018-01-29 a la s 16 17 26](https://user-images.githubusercontent.com/15789058/35529529-13ef5f1c-0510-11e8-90bf-7440007c9f19.png)

greetings!

**Comment by smelyakov** [comment]
@felipeegasneris you don't need the reference to slot in this case.

**Comment by Symbolk** [comment]
> the solution to fit the close button to modal window is:
> 
> ```
> <modal
>         adaptive
>         :name="modalSettings.name"
>         :width="modalSettings.width"
>         :height="modalSettings.height"
>         :scrollable="modalSettings.scrollable"
>       >
>         <div class="quotation-container">  // this is the important a div container to slot and  content
>           <div slot="top-right">
>             <button @click="$modal.hide('quotation-modal')">
>               x
>             </button>
>           </div>
>           <the-quotation :ad-data="adData" />
>         </div>
>  </modal>
> ```
> 
> and this is the result:
> ![captura de pantalla 2018-01-29 a la s 16 17 26](https://user-images.githubusercontent.com/15789058/35529529-13ef5f1c-0510-11e8-90bf-7440007c9f19.png)
> 
> greetings!

Just wrap the button with a <div> works, but the position is top-left, how to make it top-right as defined in the code?
