### ISSUE TITLE
Multiple modals close on esc

### ISSUE THREAD

**Issue by claudio147** [euvl/vue-js-modal#320]
#### Problem: 
I've multiple nested modals - it's working together with the vue-portal component.
But now I've got the problem that if I open the 2nd modal (which is inside the 1st modal) and want to close it via ESCAPE - all modals get's closed.

But if I do the same by click on the background it's working.

Now I found in you source code that the ESCAPE keypress calls
````
this.$modal.hide(this.name);
````
and the background-click calls
````
this.toggle(false);
````

Could this be the problem?

...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by claudio147** [comment]
Isn't the problem

**Comment by AlanVerne** [comment]
Hey, guys, is it relevant or what?
