### ISSUE TITLE
Dynamic modal - emit data to parent

### ISSUE THREAD

**Issue by lukasamd** [euvl/vue-js-modal#321]
#### Problem: 
I tried to emit some data from dynamic modal to parent page, but can't find way to do this - tried using emit close with my value and handle this, but function doesn't have any data from modal. Is it possible?

**Comment by vigikaran** [comment]
Try with Global Events and Listeners.

**Comment by GeorgeFlorian** [comment]
Is this possible ? If yes, how can we do it ?
