### ISSUE TITLE
scrollable model alway scroll to top

### ISSUE THREAD

**Issue by hoangnguyen291** [euvl/vue-js-modal#329]
#### Problem: 
When enable scrollable, modal always be push back to top of site, users have to scroll back to the previous position by themselves, this is very annoying
...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by jonnzer** [comment]
> #### Problem:
> When enable scrollable, modal always be push back to top of site, users have to scroll back to the previous position by themselves, this is very annoying
> ...
> 
> #### Example & screenshots:
> ...
> 
> I have checked stackoverflow for solutions and 100% sure that issue not in my code.

hi ,my brother ,so in the end how to solve this problem

**Comment by huydod** [comment]
I have the same issue, is there anyone have fixed it?

**Comment by jonnzer** [comment]
> I have the same issue, is there anyone have fixed it?

first , the version is 1.3.28
and then, my usage is 
` <modal name="remove-module-alert" width="380px" height="auto" :scrollable="true">
      ...content 
        </modal>`
i hope it will help you !

**Comment by ovo4096** [comment]
This problem still exists in v1.3.31.
