### ISSUE TITLE
Changing modal box style

### ISSUE THREAD

**Issue by arsalansultani** [euvl/vue-js-modal#33]
Hi can we change the style of the actual modal window e.g change white background. 
I added a new class and gave it some style but didn't effect.

**Comment by euvl** [comment]
Yes, use `classes` prop, in docs: 
<img width="921" alt="screen shot 2017-06-16 at 00 33 21" src="https://user-images.githubusercontent.com/1577802/27205881-833f950a-522b-11e7-8ecc-1aa824b9e713.png">

**Comment by Alleno** [comment]
I tried to do this on a <v-dialog/> but it didn't seem to work. Can you only pass classes to modals and not v-dialog?
