### ISSUE TITLE
TypeError: Cannot read property 'removeChild' of undefined at addStyle

### ISSUE THREAD

**Issue by DominusKelvin** [euvl/vue-js-modal#331]
#### Problem: TypeError: Cannot read property 'removeChild' of undefined
    at addStyle (/var/app/current/node_modules/vue-js-modal/dist/index.js:138:40)

```
function addStyle(obj) {
            var update, remove, styleElement = document.querySelector('style[data-vue-ssr-id~="' + obj.id + '"]');
            if (styleElement) {
                if (isProduction) return noop;
                styleElement.parentNode.removeChild(styleElement);
            }
```
I think the issue is from this function

**Comment by DominusKelvin** [comment]
I would really appreciate an answer to this for my project depends on it and it has crashed my nginx server. Thanks @euvl

**Comment by euvl** [comment]
hey @DominusKelvin, it is webpack generated code. Also, frontend javascript just physically cannot crash your server.

**Comment by DominusKelvin** [comment]
@euvl how do you think I can solve it?
![screenshot 209](https://user-images.githubusercontent.com/24433274/46529074-5e218880-c88d-11e8-84d3-f1d1803618ba.png)

**Comment by DominusKelvin** [comment]
I now understand @euvl it's web generated code. Still haven't quite gotten how to fix it though

**Comment by euvl** [comment]
This is some random node js log. I do not think that this is plugin related. Please use stackoverflow for cs questions.

Thanks

**Comment by DominusKelvin** [comment]
OK. But the logs are not random and it's pointing to the vue-js-modal dist folder.
