### ISSUE TITLE
How to close a modal in separate vue file?

### ISSUE THREAD

**Issue by focussing** [euvl/vue-js-modal#334]
Suppose the following modal in a separate vue file:
```
<template>
        <button @click="close">Close</button>
</template>

<script>
export default {
    methods: {
        close() {
            this.$emit('langsel');
        }
    }
};
</script>
```
In the parent I have;
`<modals-container v-on:langsel="onSelect"/>`
I open the modal like
```
this.$modal.show(
  modalComponent,
  {
   tags: this.tags
  },
  {
    clickToClose: false
  }
);
```
I am able to catch the click on the close button, but I cannot close the modal...
```
    methods: {
        onSelect() {
            console.log('yep')
            this.$emit('close');
            // this.$modal.hide(modalComponent);
        },
```

**Comment by focussing** [comment]
If I put in the 'close' event in the .vue file, it closes, but I do not get data back from the modal. How should I do that?
```
    methods: {
        close() {
            this.$emit('input', {a:'bb'});
            this.$emit('close');
        }
    }
```
So basically I need to catch the `{a:'bb'}` object in the parent.

**Comment by cicsolutions** [comment]
This is just a thought, without fully testing your code or my suggestion, but you may be able to accomplish what you're looking for by closing the modal by referencing its name prop.  Maybe try something like this:
```
this.$modal.show(
  modalComponent,
  {
   tags: this.tags
  },
  {
    name: 'my-modal-name', // notice how we are setting the name prop here
    clickToClose: false
  }
);
```

And then I think you should be able to close the modal from anywhere inside the vue app with:
`this.$modal.hide('my-modal-name');`

So something like this might work:
```
<template>
        <button @click="$modal.hide('my-modal-name')">Close</button>
</template>
```

Or, if you still want to emit from the child to the parent, then update your onSelect method to be like this:
```
methods: {
        onSelect() {
            this.$modal.hide('my-modal-name');
        },
```

**Comment by cicsolutions** [comment]
Regarding your second question, I think to get data back from the modal you would have to use one of the modal event callbacks.  Probably the before-close event would be the best for sending data from the modal to your parent.  

Again, I'm just throwing things at the wall to see if they stick ;)
