### ISSUE TITLE
keyup.enter is not showing v-dialog modal. Even though the method runs.

### ISSUE THREAD

**Issue by g3gurung** [euvl/vue-js-modal#339]
#### Problem: 
it seems that the method enterKeyHandler executes on enter key press but the modal is not popping or showing.
...

#### Example & screenshots:
`<input type="text" class="form-control"  v-on:keyup.enter="enterKeyHandler" v-model="searchText">`

```
enterKeyHandler() {
            const self = this;
            console.log(self.searchText)
            self.$modal.show('dialog', {
                title: 'Alert!',
                text: 'Search text must have either 3 or more characters',
                buttons: [
                    {
                        title: 'OK',       // Button title
                        default: true,    // Will be triggered by default if 'Enter' pressed.
                    }
                ]
            })
        }
```

**Comment by tillkolter** [comment]
I had a similar problem caused by the fact, that a windows listener is added on dialog creation that closes the dialog on enter. 

I monkey-patched the internal `keyUp` method like that:

```
<template>
  ...
  <v-dialog ref="dialog" />
  ...
</template>

<script>
   ...
   mounted () {
      ...
      this.$refs.dialog.onKeyUp = () => {}
   }
</script>
```

**Comment by euvl** [comment]
We dont sent enter handlers in the plugin so probably it is out of the scope of this project

**Comment by nayucolony** [comment]
@euvl 
It's not Enter handler, but there are keyup handler.

https://github.com/euvl/vue-js-modal/search?q=keyup&type=Code

**Comment by nayucolony** [comment]
so, please reopen issue.

**Comment by euvl** [comment]
goo find, thanks 👍

**Comment by lukas-pierce** [comment]
@g3gurung try use small timeout, experimentally get minimum is 100ms. Not beautiful - but it fastest solving and works for humans )
```js
setTimeout(() => {
    self.$modal.show('dialog', {
        // ...
    })
}, 100)
```

**Comment by dbethel-nib** [comment]
was this ever fixed? hitting the enter button in modal closes the modal for me still
