### ISSUE TITLE
Can't change background color

### ISSUE THREAD

**Issue by Zyles** [euvl/vue-js-modal#34]
`<modal name="hello-world" :width="300" :height="350" :classes="modal">
            asdf
          </modal>`

```
<style>
.modal {
    background-color: #000;
  }
</style>
```

Still white background.

Please advise.

**Comment by Zyles** [comment]
Partly figured it out:

Looks like it needs to be "classes" not ".classes" and I used this:

```
.modal {
    background-color: #000;
    text-align: left;
    border-radius: 30px;
    box-shadow: 0 20px 60px -2px rgba(27,33,58,.4);
    padding: 0;
    display: block;
  }
```

It makes the borders round, however the background still remains white.

**Comment by Zyles** [comment]
Consider removing this line from the project source:

https://github.com/euvl/vue-js-modal/blob/master/src/Modal.vue#L392

It seems to have no effect on the white rendering, and I can override the background color.

If I have no specified class I will get a white modal (did not test in all browsers)

**Comment by euvl** [comment]
Hey, thanks for your issue 👍 

I am busy currently to look into it, will go through it tomorrow/tonight. 
Meanwhile, please take a look at `Dog Profile Modal` example in demos, ty.

https://github.com/euvl/vue-js-modal/blob/master/demo/src/components/DogProfileModal.vue

**Comment by euvl** [comment]
Hi again

Actually you were right, tiny change. Please check out version `vue-js-modal@1.1.3`. It should not have white background.

Cheers 👍

**Comment by JStrebeyko** [comment]
Hi there!

Love the module, using it with my current project with ease. BUT! there's this `.v--modal` class that still has white background and seems stubborn with overwriting attempts. Any hints? Cheers! :beers:

**Comment by atourkow** [comment]
After banging my head around for hours I finally figured out how to overwrite the `.vm--modal` CSS. 
It's actually VERY simple.  Just add `!important` to the CSS (make sure the `.modal-override` class is global and not scoped)
```html
<modal name="foo" classes="modal-override">...</modal>
```
```css
.modal-override
    background #0008 !important
    border-radius 20px !important
    padding 10px
```
