### ISSUE TITLE
Common props for modal-container

### ISSUE THREAD

**Issue by suhodolskiy** [euvl/vue-js-modal#340]
Hello! Why not add common props/actions (height, width, before-close) to the `<modal-container>`? That would not prescribe every time you call the show method 🤔

Bad: 
```js
this.$modal.show(ProductManageModal, { product: data }, { width: 600, height: 'auto', classes: '...' }, { 'before-close': unlockViewport, 'before-open': lockViewport })
this.$modal.show(OrderManageModal, { product: data }, { width: 600, height: 'auto', classes: '...' }, { 'before-close': unlockViewport, 'before-open': lockViewport })
...

```
And repeating the same when calling others modals

Good:
```js
<modal-container @before-close="" @before-open="" height="">
```
And if you need to redefine when calling `$modal.show(...)`

Thanks 🙂

**Comment by alex83130** [comment]
A issue has been found ? I have the same problem ..

**Comment by bnku** [comment]
Use props from event in before-open handler:
https://stackoverflow.com/questions/46619336/using-vue-js-modal-how-do-i-access-the-data-passed-to-the-modal/46626575#46626575

But why it does not work, as written in the documentation?
