### ISSUE TITLE
opened event not triggering in Firefox

### ISSUE THREAD

**Issue by hdf** [euvl/vue-js-modal#342]
"opened" event not triggering in Firefox (62.0.3). It does work in Chrome, and "before-open" event works in Firefox too.

**Comment by sebbler1337** [comment]
same for IE11

**Comment by Socratezz** [comment]
I am also seeing this issue on IPhone/IPad (Safari and Chrome, haven't tested any others). 

The workaround I am using is to use beforeOpen and have an interval that checks the DOM every 100 milliseconds when an affected browser is used fire off the logic that is in opened when the DOM is fully populated. I also added a counter to limit the amount of time the interval is running.

**Comment by Wulfheart** [comment]
Is this fixed?

**Comment by euvl** [comment]
hopefully is fixed in v2 - it is using using vue's transition events
