### ISSUE TITLE
Weird behaviour with SSR

### ISSUE THREAD

**Issue by maverickpravin** [euvl/vue-js-modal#343]
I installed this plugin with exact instructions in `demo/server_side_rendering` but got this 
![capture12](https://user-images.githubusercontent.com/11708491/46893631-3767e100-ce8f-11e8-9803-37b4f20abff8.PNG)

**Comment by evry-johber** [comment]
+1, seems to be missing styles?

**Comment by euvl** [comment]
There is a css files, you need to import it yourself (due to how SSR works). Please check dist folder.

**Comment by evry-johber** [comment]
@euvl I see, thanks. I guess that part is missed in the SSR example?

**Comment by bradley-varol** [comment]
For nuxt users, this is simple a case of adding the **vue-js-modal** css file to the global css array like so:
```
/*
** Global CSS
*/
    css: [
        '~/assets/css/tailwind.css',
        '~/node_modules/vue-js-modal/dist/styles.css',
    ],
```
