### ISSUE TITLE
Transition modal-leave-active does not work

### ISSUE THREAD

**Issue by bingo-ingo** [euvl/vue-js-modal#344]
#### Problem: 

I tried to add transitions. The enter Transition works but not the Leave Transition

#### Example & screenshots:
```
     <modal
     	name="projekt-anfragen-modal"
     	height="auto"
     	width="100%"
     	:pivotY="1"
     	classes="modal-card"
      transition="modal"
     	>


<style>

.modal-enter-active, .modal-leave-active {
  transition: opacity 2.5s
}
.modal-enter, .modal-leave-to {
  opacity: 0
}
</style>

```

If i try to close the modal via  `this.$modal.hide('projekt-anfragen-modal')` the transitions will not be added.

**Comment by euvl** [comment]
Seems good to me, did you manage to find what was a problem?

**Comment by Fusseldieb** [comment]
Experiencing this issue here too. Using this setup below with _vue2-transitions_
```
<slide-y-up-transition :duration="300">
    <modal name="v_details" width="90%" height="auto" :scrollable="true">
        <v-details :result="results[selected_brush_id]"></v-details>
    </modal>
</slide-y-up-transition>
```
show the entering animation, but clicking at any other area, makes the window just dissapear, not animating it.

**Comment by Fusseldieb** [comment]
Experiencing this issue here too. Using this setup below with vue2-transitions

<slide-y-up-transition :duration="300">
    <modal name="details" width="90%" height="auto" :scrollable="true">
        <details :result="results[1]"></details>
    </modal>
</slide-y-up-transition>
show the entering animation, but clicking at any other area, makes the window just dissapear, not animating it.
