### ISSUE TITLE
Remove this from template

### ISSUE THREAD

**Issue by tryvols** [euvl/vue-js-modal#345]
#### Problem: 

I can't add class because there are syntax error

#### Example & screenshots:

![image](https://user-images.githubusercontent.com/8919860/47019699-5d77d480-d160-11e8-81ac-6d5def342f21.png)

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Thanks, @tryvols. So why not to create a PR and fix it? 😄 It's open source-after all 😄

**Comment by euvl** [comment]
Also what stops you from setting "class" param? Feels like its not a real issue
