### ISSUE TITLE
Dynamic Modals won't work without `injectModalsContainer: true`

### ISSUE THREAD

**Issue by viktorhunko** [euvl/vue-js-modal#349]
#### Problem: 
I've included the <modals-container/> component into my project, but got message `[vue-js-modal] In order to render dynamic modals, a <modals-container> component must be present on the page`.
But when I'm trying to add `injectModalsContainer: true` - it works.
The problem is that I can't use `injectModalsContainer` param, because it will be registered as a method of vm and I will not be able to use `vue-i18n` correctly with such components.

**Comment by euvl** [comment]
You need to either put <modal-container> or inject it using injectModalsContainer. I am sorry if it does not fit your use-case, but I'm afraid these are the only 2 ways.

**Comment by viktorhunko** [comment]
@euvl Thanks for your reply, but I guess there is misunderstanding. If by "put" you mean put `<modals-container>` into the project - I've did it, but it's not working. So in my case it works only with alternative option - injecting using `injectModalsContainer`

**Comment by jsoltysiak** [comment]
I've run into the same problem, but managed to resolve it by passing `{  root: this.$root }` as a third parameter to `this.$modal.show` call
Now it works just with `<modals-container>`, no need for `injectModalsContainer`
