### ISSUE TITLE
Dynamic Modal - Close params

### ISSUE THREAD

**Issue by ionutt** [euvl/vue-js-modal#353]
#### Problem: 
I want to ask how can I send data from the modal to the parent. For example in my modal I am doing an operation and I want to send on close an param: { success: true }. I need to make an difference between when that modal is dismiss or when it is close with the close event.
...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
you can use before-close, closed events or as you rightly said - global event bus

**Comment by euvl** [comment]
also shared state, like vuex could do the job

**Comment by ionutt** [comment]
I just look inside beforeClose and Close and I do something like
this.$emit('close', param ). That param is not pass into the before close or closed event.

The idea is that I want to make a difference between when I close the modal with button close, with button cancel or with clicking outside the modal. It will be a good feature to have a dismiss event on the modal.

**Comment by Untel** [comment]
Same issue here.

There is no way to pass data ? Or use the fourth argument to catch modal events ?
```
v.prototype.$modal.open = function(modal, paramsOrProps, params, events = {}) {
    return new Promise((resolve, reject) => {
        Vue.prototype.$modal.show(modal, paramsOrProps, params, { ...events,
            'before-close': (event, data) => {
                events['before-close']();
                
                // Data is always undefined
                resolve({ event, data })
            },

            // Or no way to use events emitted by the modal ?
            'custom-modal-event': (evt) => resolve(evt)
        });
    });
}
```

**Comment by adamreisnz** [comment]
Same issue here. I have made an Angular implementation of modals, and this feature was a must have. You need to be able to pass data or params with the close events so that the close handlers can differentiate between the modal being dismissed/cancelled or closed/resolved with a value/success result.

The event seemingly already contains a `canceled` property, but this is always false:

**Comment by dochoul** [comment]
2018년 11월 13일 (화) 오전 10:28, Adam Reis <notifications@github.com>님이 작성:

**Comment by dochoul** [comment]
2018년 11월 13일 (화) 오후 3:51, DY Kim <dochoul@gmail.com>님이 작성:

**Comment by adamreisnz** [comment]
O.o

**Comment by DiDHack** [comment]
> you can use before-close, closed events
This doesn't work for dynamic modals because in this case the event.params is undefined.
