### ISSUE TITLE
Modal from separate file shows empty modal as if I don't put anything 

### ISSUE THREAD

**Issue by yuriygavriluk** [euvl/vue-js-modal#355]
Hi, 
I feel like I am doing something wrong but still can't resolve this

```
import ExampleModal from './ExampleModal.vue'
```

```
this.$modal.show(ExampleModal, {
  text: 'This text is passed as a property'
}, {
  draggable: true
})
    }
```

In a separate file 
```
<template>
    
  <modal name="ExampleModal">
 
    <div slot="top-right">
      <button @click="$modal.hide('foo')">
        ❌
      </button>
    </div>
 
    Hello, ☀️!
 
  </modal>
</template>
```

But when I do call 
```
this.$modal.show(ExampleModal, {
  text: 'This text is passed as a property'
}, {
  draggable: true
})
    }

it works the same if i just called this
this.$modal.show();
```

really struggle with this problem any help is appreciated
Thanks

**Comment by mohapinkepane** [comment]
Did the simplest version of the modal show anything ? I found that the modal did not show anything because it render text as white and as such you can not see it.Try giving your text a color .Hope it helps.

**Comment by yuriygavriluk** [comment]
Thanks for a reply 
Almost all the modals work fine as expected

I just try to put html-template to the separate file and have some logic 
Color does not help as text simply is not present in html at all for some reason
