### ISSUE TITLE
How to use directly in browser using plain javascript?

### ISSUE THREAD

**Issue by Wardrop** [euvl/vue-js-modal#356]
Question, how can I use this using plain-old javascript in a web browser? 

The "vue-resource" extension for example includes a handy bit of logic to automatically register itself:

``` javascript
if (typeof window !== 'undefined' && window.Vue) {
  window.Vue.use(plugin);
}
```

vue-js-model doesn't include any such logic, so just wondering how I actually use in a web browser where import/require aren't available.

Thanks

**Comment by Wardrop** [comment]
Just found this little snippet in the README which did the trick:

``` javascript
Vue.use(window["vue-js-modal"].default);
```

**Comment by johnhorsema** [comment]
This should be in the documentation,
