### ISSUE TITLE
Modal component not registering

### ISSUE THREAD

**Issue by sic-craig** [euvl/vue-js-modal#358]
The modal component doesn't appear to be registering for use within my app.

I get the following error in any file that uses `<modal name="test"></modal>` for example.

`Unknown custom element: <modal> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**main.js**
```
import VModal from 'vue-js-modal'
Vue.use(Vuex, VueLodash, VModal)
```

**any component file**

`<modal name="test"></modal>`

Incidentally, WebStorm doesn't provide autocomplete options for `<modal>`, but does for `<vue-js-modal>` which auto imports via the following line:

`import VueJsModal from "vue-js-modal/src/Modal";`

Using this instead of `<modal>` though gives errors such as the following:
<img width="503" alt="screenshot 2018-11-12 at 17 18 49" src="https://user-images.githubusercontent.com/25926968/48363986-1e756a00-e69f-11e8-8955-5a789a744150.png">

**Comment by euvl** [comment]
You are using Vue.use in an absolutely wrong way. Please check the Vue documentation.

https://vuejs.org/v2/guide/plugins.html

**Comment by sic-craig** [comment]
I actually fixed this a couple of hours ago, apologies I see it was in fact Vue.use causing the issue - though the documentation you linked to - which I had already read - doesn't actually show how to include multiple plugins.

**Comment by euvl** [comment]
I don't think you can include multiple plugins.

**Comment by sic-craig** [comment]
@euvl you mean in one call to Vue.use? Lots of people say you can - i think possibly you can if you don't include an options object, but otherwise just multiple calls to .use() does the trick

**Comment by euvl** [comment]
exactly, has to do vue.use one time for each plugin 👍
