### ISSUE TITLE
Vue modal's SSR demo version has not matching error

### ISSUE THREAD

**Issue by SooJungChae** [euvl/vue-js-modal#361]
#### Problem: 

I followed [SSR demo version](https://github.com/euvl/vue-js-modal/tree/master/demo/server_side_rendering) in nuxt environment. When I get modal in page, then below error appear,
```bash
The client-side rendered virtual DOM tree is not matching server-rendered content
```

I compare with your codes, and follow your plugin but can't solve problem. I set plugin ssr to be `false` but error doesn't change. Did I miss something?

...

#### Example & screenshots:
![chrome debugger](https://user-images.githubusercontent.com/12723983/48462076-07a75280-e81a-11e8-8086-ca784f08ad1b.png)

nuxt.config.js
```js
plugins: [
  { src: '~/plugins/vue-modal', ssr: false }
]
```

inputDuration.vue
```vue
<template>
  <modal name="foo">
    Woo
  </modal>
</template>
```
...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Sorry, but I am not using SSR, if you have time please take a look if smth can be done to fix the demo.


Thanks

**Comment by Omintoblake** [comment]
Are there any updates for this? Im stuck at the same spot.

`  plugins: [
    { src: '~/plugins/modals', ssr: false }
  ]`

`    vendor: ['vue-js-modal'],
`
`<template>
  <modal name="foo">
    Woo
  </modal>
</template>
<script>
export default {
  name: 'foo',
  data () {
    return {
      time: 0,
      duration: 5000
    }
  },
  methods: {
    beforeOpen (event) {
      console.log(event)
      // Set the opening time of the modal
      this.time = Date.now()
    },
    beforeClose (event) {
      console.log(event)
      // If modal was open less then 5000 ms - prevent closing it
      if (this.time + this.duration < Date.now()) {
        event.stop()
      }
    }
  }
}
</script>
`

`<template>
  <div class="product">
    <foo />
  </div>
</template>`

`import foo from '@/components/foo'
`
`  components: {
    foo
  },
`
any help or ideas would be very appreciated.

**Comment by SooJungChae** [comment]
@Omintoblake No.. I decided to not using this ..

**Comment by coreycoburn** [comment]
@SooJungChae @Omintoblake You have to wrap the component in `<no-ssr></no-ssr>` tags as well.

```vue
<template>
  <no-ssr>
    <modal name="foo">
      Woo
    </modal>
  </no-ssr>
</template>
```

**Comment by coreycoburn** [comment]
I see there is an SSR version for Nuxt.

In your plugins directory, create a plugin file, ie `modal.js`
```javascript
import Vue from 'vue'
import VModal from 'vue-js-modal/dist/ssr.index'

Vue.use(VModal)
```
Make sure you import the ssr version

Then, create component like normal:
```vue
<modal name="foo">
  Woo
</modal>
```
