### ISSUE TITLE
How to closed v-dialog

### ISSUE THREAD

**Issue by darkwoolf10** [euvl/vue-js-modal#363]
#### Problem: 
How to close v-dialog if i click YES?
...

#### Example & screenshots:
![image](https://user-images.githubusercontent.com/16863894/48632993-fea9b300-e9ca-11e8-8008-901323702f64.png)

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by ahmedaabouzied** [comment]
Is this is what you are looking for , or I've got it wrong ?
`this.$modal.hide('dialog');`
