### ISSUE TITLE
Outdated version in npm

### ISSUE THREAD

**Issue by CaballoCarpiano** [euvl/vue-js-modal#366]
I Think the current version of the component in npm is outdated. I had run into some bugs related to the position of the component in safari, after searching for some time on the source I find out that the Modal component was lacking the watch.visible watcher.

So I decided to use the source version of the code directly on the project and everything worked fine, so I think maybe the version avaliable through npm is outdated. 

I saw in other trhead that you was having trouble maintaining the project, maybe you could build a team for housekeeping and PR checks.

**Comment by euvl** [comment]
Hey, I have just released the latest-latest version 👍

**Comment by CaballoCarpiano** [comment]
Thanks!! :D
