### ISSUE TITLE
Request: relative font size

### ISSUE THREAD

**Issue by quentinus95** [euvl/vue-js-modal#367]
#### Problem: 

When using the default dialog, it would be useful that all fonts uses a relative font size (using `rem` so we can increase the font size globally.

**Comment by euvl** [comment]
You can define it in CSS in your project. One style of this dialog clearly cannot fit ALL use cases, someone will want font relative, other will prefer it to be in pixels, etc. 

Please try updating it in your project (you can get class name from inspector) and let me know if it works 😄 👍
