### ISSUE TITLE
modal conflict with iview-ui Modal

### ISSUE THREAD

**Issue by tivonheng** [euvl/vue-js-modal#368]
#### Problem: 
modal conflict with iview-ui Modal
...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Sorry, but I cannot make sure that there are no conflicts with all libraries in the world. Also, we have the ability to give custom names to component (check readme).

**Comment by GopherJ** [comment]
@euvl I know this is a closed issue, but I have similar problem, $modal typescript definition conflict with buefy's modal, any ideas?
