### ISSUE TITLE
Draggable position not constrained by window bounds

### ISSUE THREAD

**Issue by natebell** [euvl/vue-js-modal#373]
#### Problem: 

When dragging a draggable modal, its displayed position is bounded by the edges of the window. However, if you continue dragging the modal past the window bounds, the actual position of the modal continues to change (relative to whichever direction you're dragging).

In other words, however far you drag the mouse past the window bounds in a given direction, you have to drag the mouse back in the reverse direction before the modal will start moving again. This has the effect of snapping the modal to the edges of the window, but the strength of the snap is dependent on how far the user "overdragged".

#### Example:

To reproduce, open the example page: http://vue-js-modal.yev.io/ and click the Draggable button. Drag the modal all the way to the right, then keep dragging further to the right. Now drag to the left and you should notice the modal doesn't immediately move. The same thing happens in the other cardinal directions. I see this happening in Chrome, FF, and Edge.

**Comment by euvl** [comment]
Hey @natebell, well spotted. The intention was to make you brig cursor back within the window but seems that we probably need to reset position somehow on mouse up. 👍

**Comment by brizzo** [comment]
I've noticed a related issue with draggable modals.

If the window is scrolled and then a draggable model is opened, the modal is not positioned correctly in the window and the window boundaries appear to be miscalculated; the modal is bounded by the initial window boundaries, before it was scrolled.
