### ISSUE TITLE
height: auto ignores bottom padding

### ISSUE THREAD

**Issue by duplo6** [euvl/vue-js-modal#374]
#### Problem: 

When I'm setting the height to auto, the padding-bottom option is getting ignored in the inner div

#### Example & screenshots:

...
![image](https://user-images.githubusercontent.com/44787124/49640521-17c3e380-fa0e-11e8-83e4-781ab84bb2b9.png)

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
try box sizing border-box
