### ISSUE TITLE
Adaptive scrollable won't scroll until browser dimensions change

### ISSUE THREAD

**Issue by mbalandis** [euvl/vue-js-modal#378]
#### Problem: 

Modal doesn't scroll until browser is resized. 
Chrome latest current version Version 71.0.3578.80 (Official Build) (64-bit) Mac OS (doesn't really matter which OS)

```
 <modal :click-to-close="false" name="mymodal" width='90%'
      height='auto' :scrollable='true' :adaptive='true'>
   [LONG LIST TABLE OR WHATEVER]
</modal>
```

#### Example & screenshots:

GIF showing the issue:
https://cl.ly/79a4083df4fb

Note, i was trying to scroll from the very beginning and then I resized the browser and did same thing it started working.

I have checked stackoverflow for solutions and 90% sure that issue not in my code. I have tried multiple times and this is not an issue on current latest version of Firefox.

p.s I tried triggering browser resize by code, doesn't work. I am not sure how to fix it but if there is a way, would be great if someone let me know. Thanks.

**Comment by uchoasvinicius** [comment]
I was having the same problem (Chrome latest version on Linux Mint 19 and macOS Mojave), but for some unknown reason, I was able to solve it by adding a transition class 

```
 <modal width="450" name="register" transition="nice-modal-fade" :min-width="200" :min-height="200" :pivot-y="0.5" :adaptive="true" :scrollable="true" :reset="true" height="auto">
```

As incredible as it sounds, Firefox Desktop and Chrome Mobile (latest versions) do not have this problem (and work without transition), apparently it's something specific to Chrome Desktop, regardless of operating system.

**Comment by mbalandis** [comment]
@uchoasvinicius thanks for your input. Always nice to get some workarounds and this one by far looks more eloquent.  
In my honest opinion, I think it is an issue that can be solved internally in vue-js-modal library, so we don't have to.

**Comment by rylax** [comment]
> @uchoasvinicius thanks for your input. Always nice to get some workarounds and this one by far looks more eloquent.
> In my honest opinion, I think it is an issue that can be solved internally in vue-js-modal library, so we don't have to.

+1

**Comment by euvl** [comment]
Now modals must have transition (or assigned one by default) - should work
