### ISSUE TITLE
Cannot read property '_dynamicContainer' of null

### ISSUE THREAD

**Issue by fusionsquare** [euvl/vue-js-modal#384]
Hi there, i need some help. I don't know why, but my photo modals doesn't working and i don't know why. I already checked everything, changes everything and now i stuck. 

vue.js

```
Vue.component('photo', require('./components/Photo.vue'));

import VModal from 'vue-js-modal';
Vue.use(VModal, {
    dynamic: true,
    injectModalsContainer: true
});

import ajax from './utilities/Ajax';

const app = new Vue({
    el: '#app',
    store: new Vuex.Store(ajax)
});
```

Modal component (method part that creates the modal
```

showModal() {
                this.$modal.show(Gallery, {
                    photo: this.photo
                }, {
                    name: 'photo',
                    height: 'auto',
                    width: '100%',
                    minHeight: 500,
                    maxHeight: 600,
                    maxWidth: 1000,
                    adaptive: true,
                    scrollable: true
                }, {
                    'before-close': (event) => { console.log('this will be called before the modal closes'); }
                })
            }
```
The console

```
Uncaught TypeError: Cannot read property '_dynamicContainer' of null
    at app.js:22566
    at Object.show (app.js:22566)
    at VueComponent.showModal (app.js:26470)
    at invoker (app.js:53874)
    at HTMLDivElement.fn._withTask.fn._withTask (app.js:53659)
(anonymous) @ app.js:22566
show @ app.js:22566
showModal @ app.js:26470
invoker @ app.js:53874
fn._withTask.fn._withTask @ app.js:53659
```

I don't know what happend, so if you need more infos, let me know. Hope you can help or give me a hint, what can happened here. I think the problems begin with my vuex implementation :(

Thanks

**Comment by fusionsquare** [comment]
I fixed it. I kicked this code within my component, so it can't work.

` import VModal from 'vue-js-modal';
    Vue.use(VModal, {
        dynamic: true,
        injectModalsContainer: true
    });`

**Comment by madebycaliper** [comment]
hey @fusionsquare can you explain a little more how you solved this? I'm getting the same error. I've used this package successfully on two other projects and I can't figure what's not working. I've tried every combination of config and settings I can imagine and the only thing that works is when I *don't* use the dynamic settings and have a discreet `Modal` component in my Vue template. Thanks!

**Comment by fusionsquare** [comment]
Hi @madebycaliper,

many things changed since my last post here. I put this into my vue.js file, before new Vue():

```import VModal from 'vue-js-modal';
Vue.use(VModal, {
    dynamic: true,
    injectModalsContainer: true
});```

And then within my gallery.vue file i set this methods:

``` methods: {
            showModal() {
                this.$modal.show(Gallery, {
                    photo: this.photo
                }, {
                    name: 'photo',
                    height: 'auto',
                    width: '100%',
                    minHeight: 500,
                    maxHeight: 600,
                    maxWidth: 1400,
                    adaptive: true,
                    scrollable: true
                }, {
                    'before-close': (event) => { console.log('this will be called before the modal closes'); }
                })
            },
            hideModal() {
                this.$modal.hide();
            },
        }
```

Hope that helps you! I think our problem shows when a HTML element missing or corrupted etc. Double check every DOM element.

**Comment by madebycaliper** [comment]
Thanks @fusionsquare. That's the same setup I've used in other projects to get it to work (including passing a Vue component into the `.show()` method) but for some reason the '_dynamicContainer' issue shows up in this newer project. I'm using a linter so I think other issues like missing/corrupted markup would surface from that but I'll keep looking. Maybe it has to do with incompatible versions of `vue` or `vuex` or something like that? @euvl if you have any suggestions, please chime in. Thanks!
