### ISSUE TITLE
vue-js-modal RWD web service

### ISSUE THREAD

**Issue by idhowardgj94** [euvl/vue-js-modal#390]
#### Problem: 
I'm using this in my project,
everything is perfect and smoothly,
save me a lot of time implement modal on vue.

but i just find out, 
My project is RWD web application,
but it seem that modal didn't response when I using phone.

didn't this project support RWD web?
or I need to set any propertis on?
...

#### Example & screenshots:
my modal is using by this:
`<modal name="create-modal" height="auto" :clickToClose="false">
 .........`
I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
hey @idhowardgj94 what does rwd stand for?
