### ISSUE TITLE
Set a minimum `top` value

### ISSUE THREAD

**Issue by LouWii** [euvl/vue-js-modal#391]
#### Problem: 

When the modal is taller than the viewport, I'd like the modal to not be that close to the top. I'd like to have some spacing between the top of the modal and the top of the viewport.

Increasing the top margin of the modal works fine for when the modal is taller than the viewport. But it creates an issue with smaller modals. Modals that are not taller than the viewport are off-centered because of the top margin (the top margin makes them display further down).

I think one way to fix it would be to set a minimum `top` value for the modal. But there's no way to change that value right now as it's calculated automatically.

I'm open to other ideas of how to do it, as I'm currently stuck.

**Comment by euvl** [comment]
Yeah, there are a lot of use cases that are not covered by this plugin, you could use `scrollable` if your modal is bigger than the window (otherwise I would question usability of that modal). But if you want this feature, please create a pr and i will be happy to help you get it approved 👍
