### ISSUE TITLE
Set modal default properties?

### ISSUE THREAD

**Issue by scheMeZa** [euvl/vue-js-modal#396]
Is there a way to set the defaults for all instances of modals?

I have to set the height to auto for every modal I instantiate:

```js
this.$modal.show(
    ListItemModalDelete,
    {},
    {height: 'auto'}
);
```

**Comment by euvl** [comment]
Hey, there is currently no way, but there were a lot of requests for this feature, so I am planning to add it at some point. I will probably post what my thinking is in this thread and it would be great if anyone could review it.

**Comment by scheMeZa** [comment]
I like that, my first instinct was to do:

```
Vue.use(VModal, {
   height: 'auto',
   dynamic: true,
});
```

**Comment by cirokd** [comment]
You can set the defaults currently by overwriting the `$modal.show` function after initializing the plugin, like this:
```js
Vue.use(VModal, { dynamic: true, injectModalsContainer: true })
Vue.prototype.$showModal = (component, props, options, events) => {
  Vue.prototype.$modal.show(
    component,
    props || {},
    {
      adaptive: true,
      height: 'auto',
      width: '100%',
      ...options
    },
    events
  )
}
```
This will behave exactly as expected:
```js
this.$showModal(MyComponent) // default properties
this.$showModal(MyComponent, { myProp: 52 }, { width: 300 }) // overwrite default
```

**Comment by euvl** [comment]
Hey, i've added this feature (i think 😄), please check out example: https://github.com/euvl/vue-js-modal/releases/tag/1.3.30

**Comment by p0psicles** [comment]
@cirokd the `events` param in your example. Is that really possible, or just a suggestion of yours?
