### ISSUE TITLE
Install via cdn example.

### ISSUE THREAD

**Issue by songoo** [euvl/vue-js-modal#397]
#### Problem: 
Hello , is it possible to install this plugin with direct cdn link ?

#### Example & screenshots:
Tried to use
```
<script src="https://cdn.jsdelivr.net/npm/vue-js-modal@1.3.28/dist/index.min.js"></script>
Vue.use(VModal);
```

#### But VModal is undefined.
---
Tnx for any answer.

**Comment by songoo** [comment]
Hi, after reading other issue and back to docs, used :

Vue.use(window["vue-js-modal"].default);

Which helped but code still fails on 

`Cannot read property 'show' of undefined`

from 

`this.$modal.show('hello-world');`

**Comment by songoo** [comment]
Ok, sry for bothering ;) 
Got it working, tnx much for neat plugin!


```
<script src="https://cdn.jsdelivr.net/npm/vue-js-modal@1.3.28/dist/index.min.js"></script>
Vue.use(window["vue-js-modal"].default);
```

In template

```
        <modal name="hello-world">
            hello, world!
        </modal>
```

In component
```
        methods: {
            confirmPassengersAndAcceptQuote: function (resort) {
                let thisInCustomVariable = this;
                thisInCustomVariable.$modal.show('hello-world');
```

(worked in chrome/ff/IE10)

**Comment by euvl** [comment]
<img width="742" alt="screen shot 2019-01-24 at 15 19 29" src="https://user-images.githubusercontent.com/1577802/51687964-7b6c9500-1feb-11e9-8637-1447fc196d68.png">
 fyi ^

**Comment by kidando** [comment]
Hi. I can't seem to get pinpoint where all this documentation is being referenced when working with this plugin using CDN. Where is this file/Readme on Bower that you are referencing above?

**Comment by EllSilva** [comment]
como fez para conseguir
