### ISSUE TITLE
Transition isn't working

### ISSUE THREAD

**Issue by leduonggithub** [euvl/vue-js-modal#398]
"Transition" doesn't seem to work for me. I set transition with class name like Vue's guide (className-enter-active, className-leave-active,...), but it is not working.

**Comment by euvl** [comment]
Hey, it definitely does work in my projects and examples 👍 Considering that this is the first time someone mentions it, probably you are doing something wrong. Double check with examples 👍

**Comment by leduonggithub** [comment]
@euvl 
Thank you so much, your package is very good to use. I hope you will always develop and support it.
I will consider my problem carefully again, 50% i'm doing something wrong and 50% i'm doing something ... isn't correct :))
