### ISSUE TITLE
How to pass slots into Dynamic Modal Component?

### ISSUE THREAD

**Issue by marbuser** [euvl/vue-js-modal#400]
So I recently found this package and have been really enjoying it, but was hoping for some advice/support.

I've got an app and I've also got a REST api. I want to use modals for creating, editing, and deleting stuff via the REST api.

My initial plan was to setup a dynamic modal with some components like; DeleteModal, EditModal, CreateModal, etc... and then just pass props into each of them. This works for DeleteModal, but not so much the other two and looks like I will need to use slots for them, since the input fields and content for a endpoint such as `/api/products`, wont be the same as one for `/api/users`, and ideally I want to keep it composite and not just a component for each one which would be really messy.

So my plan is to make EditModal and CreateModal accept slots which I can then pass in the input fields etc..., but I'm not sure how to do this with the dynamic modal.

Is this even possible? Or does anyone have any suggestions on a better way to handle this? (since this is the best one I've had at the moment.)

I can provide more info if needed! :)

**Comment by vaiil** [comment]
@euvl Is it impossible to pass slots into dynamic modals? 
There are at least 3 similar questions in issues, all of them were closed by stalebot.
