### ISSUE TITLE
'closed' and 'opened' event are not working properly on IE 11

### ISSUE THREAD

**Issue by trandaison** [euvl/vue-js-modal#403]
#### Problem: 
`closed` and `opened` event are not working properly on IE 11, it works sometimes, the percentage about 40%.

__My environment:__
- Windows 10 x64
- IE 11.1088.15063.0
- vue-js-modal 1.3.26

#### Example & screenshots:
I have an example on codesandbox, but Sandboxes don't load in IE11, so you guys can check the zip source.
- https://codesandbox.io/s/o7719ovzn6
- [vue-modal.zip](https://github.com/euvl/vue-js-modal/files/2859706/vue-modal.zip)

I found a similar issue about this #309 but it was closed;

**Comment by stepanorda** [comment]
Same here

**Comment by stepanorda** [comment]
@trandaison I have found the solution. For me it was just es2015 preset for babel, changed it to env and it works now. vue-js-modal uses arrow functions that are part of es2016.

**Comment by puck3000** [comment]
Sorry, I'm struggling with the same problem… and I seem not to be able to apply your solution… could you explain your solution to someone dumb as me?
Thank you!

**Comment by trandaison** [comment]
@stepanorda Can you show me the solution details. Thank you!

**Comment by stepanorda** [comment]
@trandaison if you have the same problem in your build configuration you need to set babel preset to "env". I don't know what build system do you use so don't know where you change it. Here are the link to the package: https://babeljs.io/docs/en/babel-preset-env

**Comment by euvl** [comment]
This might be helpful: https://stackoverflow.com/questions/56446904/transpiling-es6-for-ie11-with-babel
