### ISSUE TITLE
How to set auto height with a minHeight set too?

### ISSUE THREAD

**Issue by 181** [euvl/vue-js-modal#405]
#### Problem: 
How to set auto height with a minHeight set too?
...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by ronilitman** [comment]
Same issue, any suggestions?

**Comment by FeBe95** [comment]
FYI @181 @ronilitman @daverogers  @boenhoff

I came up with this hacky CSS solution as a workaround:

### MyModal.vue
```HTML
<template>
  <div class="modal-container">
    <div class="modal-header">
      <!-- The header has a fixed height of 64px -->
    </div>
  
    <div class="modal-body">
      <!-- The body's height should be adaptive -->
    </div>
  
    <div class="modal-footer">
      <!-- The footer has a fixed height of 64px -->
    </div>
  </div>
</template>

<style>

.my-modal-with-min-height[style*="height: auto"] .modal-body {
  min-height: calc(400px - 64px - 64px); /* 400px is the total modal min-height */
}
</style>
```

Obviously you don't strictly need the header/body/footer setup, but in my case the footer should stick to the bottom of the modal.

When calling `$modal.show()` just pass the appropriate class name as an option and set the height to `auto` as usual.

### MainPage.vue
```JS
this.$modal.show(MyModal, {}, {
  width: '600px',
  height: 'auto',
  classes: ['my-modal-with-min-height'],
  adaptive: true,
});
```

The modal is now constrained to the browser window and adapts its size accordingly, while keeping a min-height at the same time, whenever possible.
