### ISSUE TITLE
No SSR demo in  in /demo

### ISSUE THREAD

**Issue by elstr** [euvl/vue-js-modal#407]
#### Problem: 
The folder `demo/server_side_rendering` shown in the README file doesn't exist, would be good to see something built for ssr because I can't manage to popup the modal message 😢 

...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Yeah it was outdated and i noone picked up a ticket to update it so i had to remove it.
