### ISSUE TITLE
(Feature Request) Width cannot be set to inherit

### ISSUE THREAD

**Issue by scheMeZa** [euvl/vue-js-modal#409]
I would like to set the width to inherit from css.

```js

this.$modal.show(
      component,
      {},
      {
        height:       'auto',
        classes:      'bg-white mx-auto w-full sm:w-1/2',
        width:        'inherit',
        scrollable:   true,
        clickToClose: false,
      }
  )

```

Produces:
![image](https://user-images.githubusercontent.com/7773361/53284306-2f804d80-375b-11e9-909e-5947e6cdcd10.png)

I use [tailwindcss](https://tailwindcss.com), that has responsive utility classes that I would like to use to adjust the width of the modal responsively.

**Comment by DTX-92** [comment]
same for "auto"
