### ISSUE TITLE
Is there a way to use v-show instead of v-if?

### ISSUE THREAD

**Issue by alexbudure** [euvl/vue-js-modal#412]
#### Problem: 

I'm displaying some filters with vue-instantsearch but every time I close the modal, the filters don't get applied. This is due to how vue-instantsearch is setup to work well with v-show but not v-if. Is there anyway we can use v-show to display the modal instead of v-if? 

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Nope, i am afraid there is no way currently to use v-show

**Comment by 555ea** [comment]
Would be a nice feature in many cases, like displaying a captcha, it gets reloaded each time I open a modal :(

**Comment by pwnz22** [comment]
Also need this feature

**Comment by iSWORD** [comment]
@euvl Can this be labelled as a feature request instead of a closed issue?

**Comment by oeway** [comment]
Hi I think it would be great to have an option to keep hide the dom element instead of remove it.

In my case, I have iframe inside the container which holds important state, if removed, everything is gone. 

@euvl could you please consider this?

**Comment by guanyun-helo** [comment]
still this issue need be used
