### ISSUE TITLE
How to judge whether modal is closed or cancelled

### ISSUE THREAD

**Issue by xiaoXiao-keCong** [euvl/vue-js-modal#413]
#### Problem: 
How to judge whether modal is closed or cancelled
...

#### Example & screenshots:
![image](https://user-images.githubusercontent.com/30426455/53873422-541dd480-403b-11e9-86f0-1617cb9bb1b0.png)
![image](https://user-images.githubusercontent.com/30426455/53873516-7a437480-403b-11e9-9c28-ecbd480410c2.png)

can you add a cancel function?  Thanks
...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
You might want to return some parameters
