### ISSUE TITLE
How can I set event 'before-close' on dialog?

### ISSUE THREAD

**Issue by estylehq** [euvl/vue-js-modal#417]
### Problem: 

I don't understand set 'before-close' on dialog.

Please tell what I missing.

#### Example & screenshots:
```
export default {
  methods: {
    showDialog: function showDialog(title, text, ...buttons) {
      this.$modal.show('dialog', {
        title,
        text,
        buttons: [...buttons],
      }, null, null, { // or ... {}, {} ...
        'before-close': () => {
          console.log('close');
        },
      });
    },
  },
};
```
I created mix-in codes for use globally, but not work 'before-close' trigger.
And I set this code directly needs components, but not work either.

#### Another question.
Can I set option disabled click to close on dialog?

--------
I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by estylehq** [comment]
```
<v-dialog :clickToClose="false"></v-dialog>
```

solved.

please add this your guide.

**Comment by MacgyverMartins** [comment]
I'm having the same problem, but it did not work for me.
