### ISSUE TITLE
The modal is not responsive, how to pass custom design?

### ISSUE THREAD

**Issue by shahidkarimi** [euvl/vue-js-modal#419]
#### Problem: 
The modal is not responsive, how to pass custom design?

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by arnacmj** [comment]
when using scoped. you can use deep shadow styling

` /deep/ .v--modal {
background-color: red
}`

**Comment by robfr77** [comment]
It's not letting me style .v--modal. I changed it to classes="modal" and styled .modal to no effect. I'm on vue-loader v13, I'm not sure when /deep/ was enabled. The documentation online generates a 404 for anything before v14 :(

**Comment by arnacmj** [comment]
:host

**Comment by robfr77** [comment]
Thanks. I'm using fixed width modals and want to resize them on the single breakpoint. Any advice? Thanks

**Comment by euvl** [comment]
You can pass designs using classes prop
