### ISSUE TITLE
The input box can not be entered

### ISSUE THREAD

**Issue by hpy1022** [euvl/vue-js-modal#42]
When the modal draggable property is set to true ,the input box can not be entered.

**Comment by euvl** [comment]
You need to specify a selector of the element that will be a draggable handler:

```
Draggable handler

Draggable property can accept not only Boolean but also String paramenters. With String value, you can specify a CSS selector to the element which will be a "handler" for dragging.

Example:

<modal name="bar" draggable=".window-header">
  <div class="window-header">DRAG ME HERE</div>
  <div>
     Hello, 🌎!
  </div>
</modal>
```

Otherwise if you will set the prop to `true` all the modal will be a draggable handler and clicks will be handled differently.
