### ISSUE TITLE
dynamic modals as vue component not worked true

### ISSUE THREAD

**Issue by marmulack** [euvl/vue-js-modal#424]
#### Problem: 
vue component loaded but is empty(just background hielite showed).
...

#### Example & screenshots:
in my source two component in a directory named index.vue and `NewPersonal.vue`. in `app.js` imported vue-ja-modal true and used as vue like below:

> import VModal from 'vue-js-modal';
Vue.use(VModal, { dynamic: true, dialog: true, injectModalsContainer: true });

the NewPersonal.vue file:
![111](https://user-images.githubusercontent.com/15891911/56093947-cd82cf80-5ee3-11e9-8c82-940e320c4f23.jpg)
the index.vue file:
![222](https://user-images.githubusercontent.com/15891911/56094013-53067f80-5ee4-11e9-9f11-1a6e078c9ca6.jpg)

but after `npm run dev` and `serve` server, i have not any error in `browser console` and work correctly. but when click on new button the modal are not showing any thing and  just background hielite(full page shadow) are. inside the browser inspector the modal view are showing empty.
what is problem???
I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
You used library incorrectly. Please take a look into readme. The example of calling dynamic modal:

```
this.$modal.show({
  template: `
    <div>
      <h1>This is created inline</h1>
      <p>{{ text }}</p>
    </div>
  `,
  props: ['text']
}, {
  text: 'This text is passed as a property'
}, {
  height: 'auto'
}, {
  'before-close': (event) => { console.log('this will be called before the modal closes'); }
})
```
