### ISSUE TITLE
Clicking outside of modal nto working when scrolling down

### ISSUE THREAD

**Issue by matej-svejda** [euvl/vue-js-modal#426]
#### Problem:
For modals that have height set to auto and content that requires scrolling, closing by clicking outside of the modal doesn't work anymore when you scroll down.

The reason is that for  `.v--modal-background-click` you set `height: 100%;`, causing it to scroll out of view when scrolling down. It used to be `min-height: 100%;` (which worked) but that was changed in commit 07822e013b64505beb7124e72554441b55ae4726. I think just leaving height to the default value should be fine.

**Comment by euvl** [comment]
Can you make A PR pls to fix it? 😄

**Comment by euvl** [comment]
Fixed

**Comment by matej-svejda** [comment]
Hi, sorry I didnt get arrount to do a PR. But I think there was an error in my suggestion: IMHO height: auto also needs to be set. But this time I created a PR https://github.com/euvl/vue-js-modal/pull/427
