### ISSUE TITLE
Dynamic modal is not opening on version 1.3.30

### ISSUE THREAD

**Issue by liranhershko** [euvl/vue-js-modal#428]
#### Problem: 
When configured `Vue.use(VModal, { dynamic: true, injectModalsContainer: true })` the modal is not opening.

The console shows error `vue.runtime.esm.js:1887 ReferenceError: modalsContainer is not defined`

This error occurs on version 1.3.30. It might be an internal library that causes the problem.

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by mlumbroso** [comment]
I can reproduce the exact same issue. It's working fine with 1.3.28 though, so it's definitely the 1.3.30 which causes this bug.

**Comment by euvl** [comment]
There seems to be regression in .30, please use previous version until it gets fixed

**Comment by euvl** [comment]
I have published 1.3.31 and unpublished 29, 30, hopefully you will get updated automatically.
Please check if it works for you.
Thanks

**Comment by pisaq** [comment]
@euvl is it possible - I had version 1.3.16, so not very up to date and bug appeared also ?

**Comment by mlumbroso** [comment]
@euvl Thanks the super quick fix !

**Comment by liranhershko** [comment]
@euvl Thanks. It works for me now. Keep up the good work.

**Comment by euvl** [comment]
Thanks for your feedback guys! 🙏
