### ISSUE TITLE
Modal not showing

### ISSUE THREAD

**Issue by SilverFoxA** [euvl/vue-js-modal#429]
#### Problem: 

I followed the installation steps as briefed in the documentation. i.e.

`npm install vue-js-modal --save`

Version:: `"vue-js-modal": "^1.3.30"`

Defined the component globally

```
import VModal from 'vue-js-modal'

Vue.use(VModal,{ dialog: true })
```

Invoking the modal within the component

```
<template>
  <div>
.....
<modal name="hello-world">
  hello, world!
</modal>
</div>
<template>
```

Calling `show` in `mounted` using `this.$modal.show('hello-world');` but nothing happens. Shows no pop-up

I have checked StackOverflow for solutions and 100% sure that issue not in my code.

**Comment by sloone** [comment]
Got exactly the  same probleme, i dont even see the modal button on my page, nothing on logs or console

**Comment by euvl** [comment]
Seems .30 version has regression, please use previous version until it is fixed

**Comment by euvl** [comment]
Please follow #428

**Comment by SilverFoxA** [comment]
I tried downgrading it to `1.3.25` yet it's not working.

Here's how I'm importing it now

```
import VModal from 'vue-js-modal'

Vue.use(VModal, { dialog: true })
```

Not even the `dialogue`

```
this.$modal.show('dialog', {
                    title: 'Remove all products.',
                    text: 'All the products from this seller will be removed. Do you want to continue?',
                    buttons: [
                        {
                            title: 'Yes',       // Button title
                            default: true,    // Will be triggered by default if 'Enter' pressed.
                            handler: () => {
                                axios.post('https://api.tinkersale.com/messages/discard-offer',{
                                    "chatId":this.chatid
                                },this.headers).then((response)=>{
                                    console.log(response)
                                },(error)=>{
                                    this.$notify({
                                        group: 'notifications',
                                        title: 'Unsuccessful.',
                                        type: 'error',
                                        text: 'Unable to process your request. Please try again later.'
                                    });
                                })
                            } // Button click handler
                        },
                        {
                            title: 'No'
                        }
                    ]
                })
```

**Comment by habibsogbesandeji** [comment]
> ere's how I'm importing it now

Hello. Did you ever figure this out ?

**Comment by hmoskva** [comment]
> @euvl I tried downgrading it to `1.3.25`, tried `1.3.28` too yet it's not working.
> 
> Here's how I'm importing it now
> 
> ```
> import VModal from 'vue-js-modal'
> 
> Vue.use(VModal, { dialog: true })
> ```
> 
> Added `<v-dialog/>` in the component.
> 
> Not even the `dialog`
> 
> ```
> this.$modal.show('dialog', {
>                     title: 'Remove all products.',
>                     text: 'All the products from this seller will be removed. Do you want to continue?',
>                     buttons: [
>                         {
>                             title: 'Yes',       // Button title
>                             default: true,    // Will be triggered by default if 'Enter' pressed.
>                             handler: () => {
>                                 axios.post('....',{
>                                     "chatId":this.chatid
>                                 },this.headers).then((response)=>{
>                                     console.log(response)
>                                 },(error)=>{
>                                     this.$notify({
>                                         group: 'notifications',
>                                         title: 'Unsuccessful.',
>                                         type: 'error',
>                                         text: 'Unable to process your request. Please try again later.'
>                                     });
>                                 })
>                             } // Button click handler
>                         },
>                         {
>                             title: 'No'
>                         }
>                     ]
>                 })
> ```

I came across this issue when using vue-js-modal with a static nuxt build. On nuxt dev, it works fine. On static build, same issue as yours. Did you event figure it out ?
