### ISSUE TITLE
Support compiled components in dynamic modals

### ISSUE THREAD

**Issue by lehni** [euvl/vue-js-modal#430]
#### Problem: 

I noticed that when compiling my app, the dynamic modals stopped displaying. I spent quite a while tracing this back to this part of the code inside `vue-js-modal`:

```js
case 'object': {
  return options.dynamic
    ? showDynamicModal(modal, ...args)
    : console.warn(DYNAMIC_MODAL_DISABLED_ERROR)
}
```

In my case in the compiled app, the imported component ends up being a function, not an object.

I have an PR coming up to fix this already.

**Comment by lehni** [comment]
@euvl when do you plan to release a new version with this in?

**Comment by lehni** [comment]
@euvl I'm still waiting for a new release with this in... Could you do one soon? Thank you!

**Comment by LbISS** [comment]
Please make a new release, it seems i have the same issue too.

**Comment by lehni** [comment]
@euvl apologies for nagging, but could we please get a new release of this?
