### ISSUE TITLE
Custom componentName and dynamic modal do not play nice

### ISSUE THREAD

**Issue by AdrienPoupa** [euvl/vue-js-modal#432]
#### Problem: 
Hi,

I am using a custom component name as follows:
```
import VModal from 'vue-js-modal'
Vue.use(VModal, { componentName: "vue-modal", dynamic: true, injectModalsContainer: true });
```

When I create a dynamic modal from a component, like in here
https://github.com/euvl/vue-js-modal/blob/master/demo/client_side_rendering/src/components/modals/CustomComponentModal.vue
https://github.com/euvl/vue-js-modal/blob/master/demo/client_side_rendering/src/App.vue#L221

The modal created is using the `<modal>` component name instead of my own, `<vue-modal>`.

![Screenshot_20190502_180412](https://user-images.githubusercontent.com/15086425/57109903-b6761700-6d04-11e9-9e96-48f5adbe9ce8.png)

I assume it comes from here https://github.com/euvl/vue-js-modal/blob/master/src/ModalsContainer.vue#L3

Thanks!

**Comment by resyin** [comment]
I have the same problem

**Comment by mklph** [comment]
Any updates on this?

**Comment by AdrienPoupa** [comment]
I think it could be done like this: https://vuejs.org/v2/guide/components.html#Dynamic-Components

**Comment by euvl** [comment]
Fixed in v2
