### ISSUE TITLE
Update modal content

### ISSUE THREAD

**Issue by FlorianWerndl** [euvl/vue-js-modal#433]
#### Question: 

Is there any way to update the content of the modal while it is shown?

#### Example

My modal is initialized like this:

```
      this.$modal.show(
        myComponent,
        {
          data: someData,
          submit: data => this.submitForm(data),
        },
        {
          clickToClose: true,
          height: 'auto',
          pivotY: 0.5,
          scrollable: true,
          transition: 'pop-out',
        },
        {}
      )
```

I know how to pass data from parent to modal as props or events. But is there any way to update e.g. `data` while the modal is open? (I know I could do it with custom events or maybe vuex inside `myComponent`)

Example:
https://codesandbox.io/s/7znwp74vv1

It would be nice if the props passed to the component would update in this example

**Comment by euvl** [comment]
(I know I could do it with custom events or maybe vuex inside myComponent This will be the correct way. Otherwise you need to use static modals if you need prop reactivity
