### ISSUE TITLE
maxWidth doesn't work on 1.3.31

### ISSUE THREAD

**Issue by MacgyverMartins** [euvl/vue-js-modal#435]
#### Problem: 

I can't set maxWith.
I try:
```javascript
  <modal name="onboard" :max-width="302">
```
```javascript
  <modal name="onboard" :maxWidth="302">
```
Am I missing something here? Thanks

**Comment by Sebiworld** [comment]
Hi @MacgyverMartins , I think I had a similar problem. Try adding `:adaptive="true"`!

If  adaptive is false (which is the default), the internal logic of the modal will only use your width-attribute to calculate the width and position of the modal. With adaptive=true it will include maxWidth for the calculations. By the way: With adaptive=true, it will automatically set the window-width as maximum width which is nice for responsive behavior.

**Comment by ibdf** [comment]
This should be mentioned in the docs.

"If adaptive is false (which is the default), the internal logic of the modal will only use your width-attribute to calculate the width and position of the modal. With adaptive=true it will include maxWidth for the calculations. By the way: With adaptive=true, it will automatically set the window-width as maximum width which is nice for responsive behavior."
