### ISSUE TITLE
add close button to a dynamically injected modal

### ISSUE THREAD

**Issue by hamsterbacke81** [euvl/vue-js-modal#439]
#### Problem: 
Is there a way to add a close button on top right in a dynamically injected modal?
#### Example & screenshots:
I am using vue-js-modal with the config {dynamic: true, injectModalsContainer: true}. In the code, I use this.$modal.show() to inject the modal where first argument is my custom object and second argument the properties for the object. I can not add the close button in my object's template because it is used else where without the need to close it.  I just want to add this when it is showed in this modal. Is there a way to do this?
...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by mulukenrock** [comment]
What happened to this issue? I think the modal should have optional closing/other buttons/icons irrespective of the dynamic content it accepts.
