### ISSUE TITLE
prop "Adaptive" is not working in new release

### ISSUE THREAD

**Issue by whaoran** [euvl/vue-js-modal#44]
After I npm install the lastest version, I found that prop "adaptive" is not working.
In the code:
if (this.adaptive) {
this.modal.width = (0, _util.inRange)(0, this.window.width * this.maxAdaptiveWidth, this.modal.width);
...

this.maxAdaptiveWidth is always "undefined" when set a breakpoint before it.
I need to set it to 1 to make "adaptive" work.
Please check it.

**Comment by euvl** [comment]
Oh shit, my bad, thanks a lot for spotting it. 

Did not mean to publish master to npm >_<

**Comment by euvl** [comment]
Published `vue-js-modal@1.2.3`. That should fix the issue. 
Again, thanks a lot for spotting it!!!

**Comment by whaoran** [comment]
You're welcome, my friend: )
