### ISSUE TITLE
Problem with Android and text fields in form

### ISSUE THREAD

**Issue by daromnik** [euvl/vue-js-modal#440]
In Android, when you click on the text input in form in the modal, the content of modal goes up beyond the phone and the keyboard appears under modal. Scroll does not work after that.

I show modal:

```
  show () {
                this.$modal.show(
                    VFeedBackForm,
                    {
                        user: {}
                    },
                    {
                        maxWidth: 700,
                        height: 'auto',
                        resizable: true,
                        adaptive: true,
                        scrollable: true
                    }
                );
},
```

I have checked stackoverflow for solutions and 100% sure that issue not in my code.
![photo_2019-05-28_17-00-47](https://user-images.githubusercontent.com/16938890/58479918-483d3c80-816a-11e9-9137-478359b0fce3.jpg)
![photo_2019-05-28_17-00-40](https://user-images.githubusercontent.com/16938890/58479919-48d5d300-816a-11e9-9474-630cb810f349.jpg)

**Comment by alehlipka** [comment]
Same problem

**Comment by marcamos** [comment]
Same here.
