### ISSUE TITLE
Dynamic modal limitations

### ISSUE THREAD

**Issue by dland512** [euvl/vue-js-modal#444]
#### Problem: 
The docs say

> Note: keep in mind that there are some limitations in using dynamic modals. If you need full functionality then use ordinary modal instead.

Can I get some clarity on what those limitations are?

**Comment by euvl** [comment]
It is opinionated on which props can be set and which are pre-set and cannot be changed.

**Comment by davidleureka** [comment]
Can I get a list of which props those are? I'm not trying to be difficult, it's just hard to make a decision on whether or not to use dynamic modals without all the info.
