### ISSUE TITLE
Vue.extend component

### ISSUE THREAD

**Issue by ar53n** [euvl/vue-js-modal#446]
#### Problem: 

Don't open modal with component created like a `Vue.extend({})`. But i want i use typescript

...

#### Example & screenshots:

https://codesandbox.io/s/vue-template-n9mz2
...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by AlexandrSymonov** [comment]
Hello everybody

I have the same issue
I have tried to find a reason

When you use component style like: 
// SomeComponent.vue
`export default {
data() {}
}`

and 
`import SomeComponent from "./SomeComponent"
typeof SomeComponent // object
`
but if you use some like 
`export default class SomeComponent extends Vue {}`

and 

`import SomeComponent from "./SomeComponent"
typeof SomeComponent // function
`

After that https://github.com/euvl/vue-js-modal/blob/master/src/ModalsContainer.vue#L38
The same job for 'function' and 'object'.

Well, I hope it helps.

**Comment by ancodeUDW** [comment]
I have the same problem, and its a prerequiste to use typescript an Vue.extend in my project
