### ISSUE TITLE
the same name modal

### ISSUE THREAD

**Issue by xiechuanlong** [euvl/vue-js-modal#447]
hello:
 I have a question that the modal name is the unique Identification， but in a big application, there may be a lot of modal, and the modal name maybe repetition. so all modals with the same name will appear, and we can only hide one modal from click background. Is it necessary to add a duplicate named intercept?

forExample: 
```
 file: src/index.vue
const Plugin = {
    install (Vue, options = {}) {
    ...
    this.allModalsName = [] //  initialize： collection modal name
    .....
  Vue.prototype.$modal = {
        show (modal, ...args) {
        if(hasRepeat(Plugin.allModalsName, modal)) {  // whether is repeat?
            throw new Error ('the modal name is unique, you have already this modal , please rename it')
        }
        switch (typeof modal) {
         ....
          }
 }
````
````
 file: src/Modal.vue
beforeMount () {
    Modal.allModalsName.push(this.name)  // collect modal name 
   }
````

**Comment by euvl** [comment]
Modal name is a sort of template, if you need different content, pass it through parameters when you call $show. Or you can have "generic" modal and pass "type" through params
