### ISSUE TITLE
Modal doesn't work with .vue component which has <script> block

### ISSUE THREAD

**Issue by rejifald** [euvl/vue-js-modal#449]
#### Problem: 

Modal doesn't work with .vue component which has <script> block.
I am not sure where problem is exactly, but, i tried show modal with very simple component (just logo without any script), and it worked, but with other components which have script tag - it works. Also i tried remove script tag from components which didn't show on modals - and it worked.
Actual result: Nothing happens, modal isn't showing.

**Comment by euvl** [comment]
https://medium.com/@lassiuosukainen/how-to-include-a-script-tag-on-a-vue-component-fe10940af9e8

**Comment by rejifald** [comment]
@euvl i told about script **block**, not **tag**.
Script block is a part of single file vue component.
