### ISSUE TITLE
how do I fix the resizable - (.vue-modal-resizer) fixed at the bottom while scrolling.

### ISSUE THREAD

**Issue by KaitoXion** [euvl/vue-js-modal#450]
how do I fix the resizable - (.vue-modal-resizer) fixed at the bottom while scrolling.

...

#### Example & screenshots:
![image](https://user-images.githubusercontent.com/23281263/60646792-cded8f80-9e6e-11e9-8b55-4b1942781905.png)

...

I have checked stackoverflow for solutions, I didn't manage to make it work though -_- 
maybe the search keyword is wrong or something

**Comment by euvl** [comment]
i don't think scolling and resizing works together well. you should probably even see the warning in the console that says please don't do that 😄

**Comment by KaitoXion** [comment]
Haha, ya; it didn't work well. am not sure if css can do it but I really appreciate your confirmation. ;) 

(≧∀≦ゞ
