### ISSUE TITLE
Max Height/Max width is not honored during resizing

### ISSUE THREAD

**Issue by hybridwebdev** [euvl/vue-js-modal#451]
#### Problem: 

As stated in title, the maxWidth and maxHeight properties to not get applied, resulting in modal being able to scale to fill entire view port. There was a previous ticket opened about this, however it was closed. 

Having taken a look at your code, I believe this is to do with your resizer component. You can see in the resizer event that the modals maxWidth and maxHeight parameters are not taken into consideration during the resize event. In fact, they aren't even passed in as props. I believe this means that when resizing, these props are completely ignored. 

*Edit* Submitted PR https://github.com/euvl/vue-js-modal/pull/452

**Comment by hybridwebdev** [comment]
bump to keep this alive.

**Comment by adewalegeorge** [comment]
bump to keep this alive.

**Comment by hybridwebdev** [comment]
Any chance of getting the PR I created for this merged?
