### ISSUE TITLE
v-dialog is the same as vuetify's dialog

### ISSUE THREAD

**Issue by KTLdeveloper** [euvl/vue-js-modal#453]
#### Problem: 
Registration of <Dialog/> component name is the same as vuetify's dialog component name, so it has a conflict with this v-dialog cause `this.$modal.show('dialog')` doesn't work
...

#### Example & screenshots:
```
    /**
     * Registration of <Dialog/> component
     */
    if (options.dialog) {
      Vue.component('VDialog', Dialog)
    }
```
...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by hybridwebdev** [comment]
This can easily be solved by importing the vue-js-modal component in and then creating a component with your name using the vue-js-modal import as the object. I suggest reading the VUE docs for how to do this, but it's really a pretty trivial matter and you'd do it in lieu of doing Vue.use(vue-js-modal);
