### ISSUE TITLE
Error in v-on handler: "TypeError: Cannot read property '$modal' of undefined"

### ISSUE THREAD

**Issue by rafal-leap** [euvl/vue-js-modal#456]
@click="$modal.show('example-adaptive')" - works fine
@click="showModal()" - throws an error

Example

https://codesandbox.io/embed/vue-template-9h0uj

**Comment by euvl** [comment]
You've used an arrow function which does not have "this" scope in javascript.
```
  methods: {
    showModal: () => {
      this.$modal.show("example-adaptive");
    }
  }
```

You should use `showModal () {}` because vue.js uses "this" as a context for all your variables, plugins, etc.

**Comment by rafal-leap** [comment]
Perfect, thanks. I totally forgot about this limitation.
