### ISSUE TITLE
Modal z-index not on top

### ISSUE THREAD

**Issue by ricky11** [euvl/vue-js-modal#457]
#### Problem: 
Using Vue 2.5.2 the modal appears to be behind components 
...

#### Example & screenshots:
http://drop.pmgrouphk.com/xrg01E

...
I have checked stackoverflow for solutions and 100% sure that issue not in my code.
I have checked my component and cannot find any z-index that would cause conflict with vuejsmodal.  Any ideas or suggestions?

**Comment by FedoraTipper** [comment]
You are right, the issue is to do with z-index. I had the same issue. You will need to structure your components with explicit z-index values. Currently this modal component sets itself to a z-index value of 999. You'll want to structure your other components to be a lower value.

**Comment by ricky11** [comment]
I have checked my vue components css, and none of them have a z-index associated with them. Setting the parent wrapper css to z-index:-1 doesn't help.  i need to to do more digging, do you have any other suggestions.

**Comment by euvl** [comment]
This is really strange. Could it be that you didn't close the tag somewhere so that browser tries to interpret the template but does it in a weird way?

**Comment by euvl** [comment]
Also if you are using portal-like functionality or render modal in a different root - it might be the cause of the problem
