### ISSUE TITLE
Cannot scroll until the end when modal content is long on mobile phone

### ISSUE THREAD

**Issue by tdimov** [euvl/vue-js-modal#461]
#### Problem: 
Cannot scroll modal until the end when modal content is long. I have tested it on Samsung S5 and iPhone 7 but on Samsung S9 works as expected (I guess it is because of the screen size). When I rotate screen on S5 and iPhone 7 devices everything is fine, but when I open it at first it is broken.
...

#### Example & screenshots:
Here are my configurations of the modal:
`{
  adaptive: true,
  height: 'auto',
  width: '600px',
  scrollable: true,
  pivotY: 0.1
}`
...
Did somebody have this problem?

**Comment by gokhantaskan** [comment]
I use Huawei Mate 20 lite and face that problem, too. It is probably about adaptive option.

**Comment by euvl** [comment]
Hi, can you please send a screenshot

**Comment by mrdigitalau** [comment]
Hey @euvl , I also confirm this using Chrome on Samsung S10.
Thank you for your wonderful plugin by the way.

If the modal is taller than the actual screen, scrolling down is usually OK, but scrolling up gets stuck for me.

**Comment by besrabasant** [comment]
This issue occurs due to the behavior of the browser address bar in mobile browsers. When you scroll up the page, the browser address bar scrolls up and hides, changing the height of the browser. So the modal tries to reposition itself according to the new height.

**Comment by fervailanti** [comment]
+1 here. Tested in Chrome and Safari with iPhone X.

Any news or workaround?

**Comment by Patchx** [comment]
I think the issue I faced was the same as this one. It was very frustrating. This fixed it for me!

```
<style>

.mobile-fixes-for-vue-modal {
  height: 100%;
  max-height: 100%;
  overflow-y: auto !important;
  padding: 1rem;
  position: fixed !important;
}

</style>

<template>
    <modal 
        :adaptive="true"
        :classes="['mobile-fixes-for-vue-modal']"
        height="auto"
        :scrollable="true"
    >
        <div>
	</div>
     </modal>
</template>
```
