### ISSUE TITLE
CSS filter property on parent breaks modal

### ISSUE THREAD

**Issue by moka491** [euvl/vue-js-modal#462]
#### Problem: 
When using filter: drop-shadow(); on any parent element of the modal component (up the dom tree),
the modal will show up behind multiple elements contained in the same parent.
The filter property also breaks the modal's positioning, hence you can scroll out of the normally fixed overlay.

edit: We also noticed that any parent element with a z-index set lower will take priority, thus the modal's z-index 999 doesn't have any effect anymore. This can also make it appear behind other elements.

**Comment by taraschuiko** [comment]
https://github.com/euvl/vue-js-modal/issues/457
