### ISSUE TITLE
Custom/dynamic confirm dialog without event bus

### ISSUE THREAD

**Issue by Blanen** [euvl/vue-js-modal#464]
#### Problem: 
I to put a form inside the modal. I want the form to have a close button. If the form has been changed this close button needs to open a modal asking if I'm sure I want to quit because there are unsaved changes.

How could I get the boolean value for this prompt? 

(before) close Events don't allow data to be send with it.

**Comment by hybridwebdev** [comment]
You can manually trigger the form open, close via your own methods. I'd reckon in this case, you'll want to manually control the modals state based on the state of your form.
