### ISSUE TITLE
variable replacement in dynamic mode template does not work when variable inside an element.

### ISSUE THREAD

**Issue by glennpierce** [euvl/vue-js-modal#467]
#### Problem: 

I have a dynamic dialog with the following template

```
<div style="padding:10px;">
            <div>sensor_id: {{sensor_id}}</div>
            <img style="height:340px;width:450px;overflow:scroll;" src="http://127.0.0.1:2337/graph/{{sensor_id}}" />
          </div>
```

The first sensor_id placeholder gets replaced correctly but the one inside the img element does not.

...

#### Example & screenshots:

Looking in the browser inspection window I get
```

<div>sensor_id: 611269</div> 
<img src="http://127.0.0.1:2337/graph/{{sensor_id}}" style="height: 340px; width: 450px; overflow: scroll;"></div>
```

How can I get around this issue ?

Thanks

**Comment by shpfive** [comment]
please try with 

`<img :src="'http://127.0.0.1:2337/graph/'+sensor_id" style="height: 340px; width: 450px; overflow: scroll;"></div>`

or with a computed property

`
computed: {
    link: function () {
      return 'http://127.0.0.1:2337/graph/' + this.sensor_id
    }
  }
`
and
`<img :src="'link" style="height: 340px; width: 450px; overflow: scroll;"></div>`

**Comment by glennpierce** [comment]
Thanks. That seemed to work.
What is the fix doing ?

**Comment by shpfive** [comment]
{{}} is not for attribute binding
attribute binding with vue properties is always done with :attr
