### ISSUE TITLE
Getting all dynamically generated modal names to close all of them

### ISSUE THREAD

**Issue by brumik** [euvl/vue-js-modal#474]
#### Problem: 
Would be (or is it) possible to return all the dynamically generated modal names? Or be able to close all the dynamic modals programmatically? I am using lots of modals in my application and there can be multiple open at a time. If an event occurs I want to close them all. It would be cumbersome to give a name to them all, store it and then iterate ower to close them all.

As I was looking at your code it would be possible to close them all with the `hide()` without any arguments. If it is called like that there could be an iteration over modals, getting the ids and apply to hide.

(BTW: nice code style)

**Comment by ksherman** [comment]
I bet you could do this with a global event bus and add a listener on the mounted components to execute the `this.$emit('close')` event to close the dynamic modal modal.
