### ISSUE TITLE
Arabic Problem Position

### ISSUE THREAD

**Issue by ionutt** [euvl/vue-js-modal#477]
#### Problem: 
When the body has direction: rtl, the position of the modal is way off.
The left should be switch to right. Any suggestion how to do an hack of this?
...

#### Example & screenshots:
![image](https://user-images.githubusercontent.com/13276052/66209149-6c340000-e6bf-11e9-8bbc-731529331a02.png)

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by hot4mix** [comment]
this happens because the modal is positioned using an absolute left style. you can go around it using this dirty hack.

`let modal = document.getElementsByClassName('v--modal')[0]; \\the modal element
				let position = modal.style.left; \\current left position
				modal.style.left = null; \\removing the left margin since its still in effect in the rtl display
				modal.style.right = position; \\ assigning the position to the other side (right)`

i applied this to a method that gets triggered when the modal is mounted.

**Comment by ionutt** [comment]
Thanks for this. I was think about that but for this is a hack, and also what will we do if there is an screen resize or I think that we can drag the modal.

 My aproach was different.
- detect the direction or language on the body ( direction: rtl )
- if arabic apply a class on the modal wrapper to change the direction ( direction: ltr ). 
- if arabic apply a class on component inside the modal ( direction: rtl )

Hope these solution will help other developers.

**Comment by hot4mix** [comment]
actually an earlier hack i did was to calculate window and modal sizes to have the modal box center even on resizing. but i discarded it on account of too much dom manipulation for probably no reason, but here it is, if someone would benefit from it

```
let maxW = document.getElementsByTagName('body')[0].clientWidth / 2;
//half the body width

let modalW = document.getElementsByClassName('v--modal')[0].clientWidth / 2;
//half the modal width

let position = maxW - modalW;
//the absolute position

document.getElementsByClassName('v--modal')[0].style.left = `-${position}px`;
//in minus incase of ltr to avoid doing an extra step tbh :D
```

**Comment by hot4mix** [comment]
i concede that your approach is absolutely cleaner and way simpler 😄

**Comment by henriquesantos-hotmart** [comment]
I add a custom css in v--modal
  .v--modal {
    text-align: right;
    left: 0px !important;
    margin: 0 auto;
}

**Comment by henfreire** [comment]
I add a custom css in v--modal
.v--modal {
text-align: right;
left: 0px !important;
margin: 0 auto;
}

**Comment by amirehman** [comment]
I handled this issue like this.

`
<div :class="{'ltr': $i18n.locale === 'ar'}">
      <modal name="subscribe" height="auto" :scrollable="true">
          <div class="text-center pt-5 lg:pt-0" :class="{'rtl': $i18n.locale === 'ar'}">

            //Content

          </div>
       </modal>
 </div>

`

**Comment by eslamoo** [comment]
> 

Thanks for sharing this, solved the problem.

**Comment by eslamoo** [comment]
> I handled this issue like this.
> 
> ```
> <div :class="{'ltr': $i18n.locale === 'ar'}">
>   <modal name="subscribe" height="auto" :scrollable="true">
>     <div class="text-center pt-5 lg:pt-0" :class="{'rtl': $i18n.locale === 'ar'}">
>       
>     </div>
>   </modal>
> </div>
> ```

Thanks for sharing this, fixed the problem.
