### ISSUE TITLE
Dynamic modal is not shown when using vue-class-component

### ISSUE THREAD

**Issue by GrassiSupport** [euvl/vue-js-modal#480]
I've created a modal component using vue-class-component

```
<template>
    <div>Hello, world!</div>
</template>

<script lang="ts">
    import Vue from 'vue';
    import Component from 'vue-class-component';

    @Component
    export default class ModalHelloWorld extends Vue {}
</script>
```

When I try to open it, using dynamic modals, it does not appear:

```
// some code here
import ModalHelloWorld from '@/components/ModalHelloWorld.vue';

openModal() {
    this.$modal.show(ModalHelloWorld);
}
```

Of course, I've imported vue-js-modal in this way:

```
import Vue from 'vue';
import VModal from 'vue-js-modal';

Vue.use(VModal, { dynamic: true, injectModalsContainer: true });
```

**Comment by seeARMS** [comment]
I have a similar problem. Looks like the CSS is not being applied correctly, and the dynamically injected model has display: none and opacity: 0:

![image](https://user-images.githubusercontent.com/3957773/67260820-61fd5a00-f452-11e9-8113-219ee87bc5ad.png)

**Comment by jbryan-76** [comment]
I have the same issue. I think the npm package code is behind the GitHub code.

Un-minifying and diffing npm versions of dist/index.js between versions 1.3.28 and 1.3.31 (ie latest) reveals several changes in how $modal.show works for dynamic components (at least using typescript). src/index.js implies that a new switch statement is supposed to include a 'function' case which allows imported components to render as dynamic:
![image](https://user-images.githubusercontent.com/56934964/67423058-95023380-f5a1-11e9-8a19-a797ea3b254f.png)

However, the generated 1.3.31 npm bundle dist/index.js (here un-minified) does NOT include the 'function' case:
![image](https://user-images.githubusercontent.com/56934964/67423582-85371f00-f5a2-11e9-9e4d-14bb6e219322.png)

The code [here](https://raw.githubusercontent.com/euvl/vue-js-modal/master/dist/index.js) is correct:
![image](https://user-images.githubusercontent.com/56934964/67423891-0db5bf80-f5a3-11e9-9223-3ff32257b9b1.png)

Downloading above and replacing in node_modules or manually adding "case 'function':" to dist/index.js fixes it for me, but it appears the npm package is "behind" the current master even though they are using the same version.

**Comment by nibytes** [comment]
So it will update on npm?

**Comment by nibytes** [comment]
@euvl when will news version?

**Comment by nibytes** [comment]
Temp fix for peoples who can't download and replace code in node_modules.
Just change version to this
`"vue-js-modal": "euvl/vue-js-modal#master",`
But in future when new version will on npm, replace back to need version.
