### ISSUE TITLE
Make use of Vue App while modal is open

### ISSUE THREAD

**Issue by erkanatesli** [euvl/vue-js-modal#483]
#### Problem: 
When i opened the vue-js-modal, i'm not able to do thing outside this modal. It is permanent available and the only action i can do is to close the modal. When i open the modal i should have the possibility to continue on my page while modal is open.
...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Hi, thanks for your feedback. This use-case is currently not supported, i will add it to our trello board 👍
