### ISSUE TITLE
Disable Overlay?

### ISSUE THREAD

**Issue by ricky11** [euvl/vue-js-modal#484]
#### Problem: 
Can i disable the overlay shadow? 
...

#### Example & screenshots:
Would like to use this as a context menu.
...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Yep, you can just change the css of the overlay, it is called `.v--modal-overlay`

```
.v--modal-overlay { background: red }
```
