### ISSUE TITLE
Cannot make modal dynamic

### ISSUE THREAD

**Issue by nicolasvahidzein** [euvl/vue-js-modal#49]
Hello, i really love your modal, of all of the ones i tried this is my favorite. I do have one issue though, i cannot get it to be dynamic in that when i set a size, it gets the values loaded on page load, and not what the new computed property i pass on.

Is this normal? I wanted to adjust the width and height based on many dynamic parameters but after all my testing it just takes what is computed on page load. Thanks for your help and insight.

**Comment by euvl** [comment]
Hey @nicolasvahidzein,

Thanks a lot for kind words 😀.  You are right, that is how it currently works. The reason is that position/size are already pretty complicated to calculate due to a number of features like resizing + dragging + adaptivity. 

Watching height/width and recalculating everything based on changes is not impossible to do, I just don't have enough free time 😞 . Currently contributors and I are working on an option to set the size in %. 

I will add it to my todo list, I think it's a nice improvenet 👍

**Comment by nicolasvahidzein** [comment]
Ok i understand well thank you anyway already for all this wonderful and great looking hard work.

As a newbie, is there maybe a way with javascript to generate that portion of code on the fly?

I am using your demologin code component from your website that i modified, i tried placing it in a v-show tag but that only hides it, it does not rerender it, any way to generate it in javacsript or vue or something? That way it would go around the pb entirely.

Thanks.

**Comment by nicolasvahidzein** [comment]
I FOUND A SOLUTION THAT WORKS PERFECTLY, you don't even need to worry about modifying your project, you can tell your users to do this:

```
<div v-for="item in languageModal" key="item.name">
			
			<LanguageChange v-show="languageModalVisible" v-bind:adaptive="adaptive" v-bind:resizable="resizable" v-bind:draggable="draggable" v-bind:modalWidth="modalWidth" v-bind:modalHeight="modalHeight" v-on:languageChanged="languageSelected"/>
			
</div>
```

Basically wrap the component in a v-for div, link it to an array that starts off empty:
```
languageModal: [ ]
```
then populate the array before showing the modal:
```
                               this.languageModal.push({name: 'langModal'})

                               this.resizable = resizable
				this.adaptive = adaptive
				this.draggable = draggable
				this.modalWidthStatic = 700
				this.modalHeightStatic = 350
				
				this.$nextTick(() => {
					this.$modal.show('language-change')
				})
```

Then remove it. It's better to use a timer in case you want it to transition it out nicely .
```
                         hideLanguageModal () {
				console.log('hideLanguageModal function')
				
				this.$modal.hide('language-change')
				
				//do a timer and then kill it
				this.languageModalAssassin = setInterval(this.killLanguageModal, 500)
			},
			
			languageSelected () {
				console.log('languageSelected function')
				
				this.hideLanguageModal()
			},
			
			killLanguageModal () {
				console.log('killLanguageModal function')
				
				//clear the array
				this.languageModal.pop()
				
				//clear the timer so it never shows up again
				clearInterval(this.languageModalAssassin)
			}
```

**Comment by euvl** [comment]
Nice work!

**Comment by nicolasvahidzein** [comment]
Thank you dear sir, i'm closing this ticket and have a wonderful day!!!

**Comment by euvl** [comment]
You've done all the work, so no need to thank me! 👍 😄
