### ISSUE TITLE
Three (3) separate CSS files

### ISSUE THREAD

**Issue by krstic-duci** [euvl/vue-js-modal#490]
#### Problem: 
I am using **v1.3.31**, and in dev or prod environment the **vue-js-modal** is loading 3 separate CSS (please see image) files, and I would like to load all of the CSS files into one (1) file or to turn off for example CSS related to dialog. I've built my project via vue-cli.

#### Example & screenshots:
![Screenshot_1](https://user-images.githubusercontent.com/22850096/68682181-fc8a1e00-0564-11ea-954c-1d5a8462f1d2.png)

![Screenshot_2](https://user-images.githubusercontent.com/22850096/68682189-ff850e80-0564-11ea-9df4-6b6b32515ae2.png)

![Screenshot_3](https://user-images.githubusercontent.com/22850096/68682195-014ed200-0565-11ea-8606-8f137308a411.png)

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Are you 100% sure that this is happening in production ? As for dev it is just how dev server works - converting all css blocks into separate imports (faster to process)

**Comment by euvl** [comment]
Also there is a built version where you can import js and css files separately. Check /dist folder

**Comment by krstic-duci** [comment]
Yep, I just double checked the production and there are 3 separate CSS _<style>_ tags. So you would suggest to import **.js** and **.css**  from _/dist_ into my **main.js** files?

**Comment by euvl** [comment]
Yep, those were initially done for nuxt, but then no-one wanted to maintain demo (and nuxt loves to change things).

**Comment by krstic-duci** [comment]
Thanks @euvl. I will try it, and let you know. Cheers
