### ISSUE TITLE
Modal is broken in Nuxtjs

### ISSUE THREAD

**Issue by wiadev** [euvl/vue-js-modal#491]
#### Problem: 
Modal is working fine when we refresh the page but if we come back from the other page via nuxt-link(without hard-refresh), the modal is broken.

I figured that all `v--modal-**` modal classes weren't imported if we come from the other pages via nuxt-link.

styles in `vue-js-modal/src/modal.vue/<style></style>`

Any thoughts why it wasn't imported at all if we navigate via nuxt-link?

**Comment by euvl** [comment]
Hi, thanks for your report. Please try importing styles directly for nuxt. There is a nocss + css version of package in /dist folder.

https://github.com/euvl/vue-js-modal/blob/master/dist/styles.css
