### ISSUE TITLE
Max height not used when height set to auto

### ISSUE THREAD

**Issue by KendallSpackman** [euvl/vue-js-modal#493]
#### Problem: 
When the value of the height prop is set to "auto" the "maxHeight" prop is ignored. There doesn't seem to me to be any reason why the maxHeight could not also be applied to the modal.

#### Example & screenshots:
https://codepen.io/kendallspackman/pen/zYOZVMa
![maxheight](https://user-images.githubusercontent.com/12240557/68814481-324b0780-0636-11ea-8b6f-d410187c1836.png)

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by KendallSpackman** [comment]
keeping open

**Comment by soylomass** [comment]
Happens to me too

**Comment by Marianissimus** [comment]
Me, too
