### ISSUE TITLE
how to set the content of modal to keep-alive？

### ISSUE THREAD

**Issue by mexhfl** [euvl/vue-js-modal#494]
#### Problem: 

...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by rafalolszewski94** [comment]
Do you have any example ? Since you haven't provided any it's hard to help. You can achieve it I believe using non-dynamic modal in your component.

**Comment by ricky11** [comment]
how would you keep a dynamic modal alive?
