### ISSUE TITLE
Re-center modal after image has loaded

### ISSUE THREAD

**Issue by aceraven777** [euvl/vue-js-modal#495]
#### Problem: 

Is there a way / method to re-center the modal after the image is loaded? I can't seem to re-center the modal.

#### Example & screenshots:

I created a `opened` event handler and I have this code

```
$('.modal img').one('load', () => {
    $(window).trigger('resize');
});
```

But this is not working, the modal doesn't re-center.

**Comment by S-Cardenas** [comment]
There doesn't seem to be a way to re-center the modal. I suggest you load the image first and then display the modal once the image has finished downloading.

```
        // Download iamge first to prevent modal jank
        let downloadingImage = new Image();

        downloadingImage.onload = () => {
          // Show modal
          this.$modal.show('name-of-modal');
        };

        downloadingImage.src = 'https://images.lifealth.com/uploads/2018/03/commitments-to-make-if-you-want-to-be-happy.jpg';
```

**Comment by aceraven777** [comment]
@S-Cardenas , thanks. Actually that's what I did, I preloaded the image before showing the modal.

I hope they will add a re-position method on this.
