### ISSUE TITLE
box-shadow, border-radius setting

### ISSUE THREAD

**Issue by kintony** [euvl/vue-js-modal#496]
I want to set box-shadow and border-radius by myself.

**Comment by ricky11** [comment]
Did you find a solution?

**Comment by atourkow** [comment]
After banging my head around for hours I finally figured out how to overwrite the `.vm--modal` CSS. 
It's actually VERY simple.  Just add `!important` to the CSS (make sure the `.modal-override` class is global and not scoped)
```html
<modal name="foo" classes="modal-override">...</modal>
```
```css
.modal-override
    background #0008 !important
    border-radius 20px !important
    padding 10px
```
