### ISSUE TITLE
Problem with Dynamic Modals

### ISSUE THREAD

**Issue by MEJSIK** [euvl/vue-js-modal#499]
Hey, I' trying to use Typescript in my project and i have problem with modals in this plugin. I'm passing an object with template and when I'm running my function I have this error:
![image](https://user-images.githubusercontent.com/26696620/70640479-476a8480-1c3c-11ea-977b-1c19569d81b6.png)

**My function:**
```
showDialogNoInternet() {
            this.$modal.show(
                {
                    template: `
                    <div>
                    jabadu
                    </div>`
                }, {
                text: 'Test'
            }, {
                height: 'auto'
            })
        }
```

**My main.ts file:**

```
import Vue from "vue";
import App from "./AppNew.vue";
import router from "./router";
import store from "./store";
import VModal from 'vue-js-modal'

Vue.use(VModal, { dynamic: true, injectModalsContainer: true })



new Vue({
  router,
  store,
  render: h => h(App),

}).$mount("#app");

```

**Comment by samydoesit** [comment]
Are you using vue-cli? Then you need to turn on the `runtimeCompiler` in vue.config.js.

https://cli.vuejs.org/config/#runtimecompiler

**Comment by MEJSIK** [comment]
@samydoesit thanks. It's working :)
