### ISSUE TITLE
Bug of "this.$modal.hide()"

### ISSUE THREAD

**Issue by yyh1102** [euvl/vue-js-modal#5]
When I use "this.$modal.hide()", the hidden modal will also show up. I guess the bug lies in the trigger function.

**Comment by euvl** [comment]
Thanks a lot for your bug report @yyh1102 😄  Hopefully I have fixed the issue in the version 1.0.17

**Comment by yyh1102** [comment]
Thanks for your helping, and please npm publish~

**Comment by yyh1102** [comment]
It works well! Thanks very much~
