### ISSUE TITLE
No response when use nuxt

### ISSUE THREAD

**Issue by z22919456** [euvl/vue-js-modal#503]
#### Problem: 

When I add vue-js-modal with yarn in my nuxt project, and run in development mode, My browser keeps loading without any response. And my console also no any message, There is only silence.

I wonder if I did something wrong?  
Did any one have the same problem?

##### nuxt version
`Nuxt.js v2.10.2`

##### nuxt.config
```
plugins: [
   ....
   ....
    '@/plugins/vue-js-modal',
  ],
```

##### plugins/vue-js-modal.js
```
import Vue from 'vue'
import VModal from 'vue-js-modal/dist/ssr.index'

Vue.use(VModal)
```

**Comment by z22919456** [comment]
I fixed it, is my fault
Sorry for disturbed

**Comment by xkisu** [comment]
What fixed it for you? I'm having the same problem
