### ISSUE TITLE
Modal keeps to be alive even when I call this.$modal.close method

### ISSUE THREAD

**Issue by Qwoxa** [euvl/vue-js-modal#505]
#### Problem: 
Hi!
I can not figure out a way to clear the data cached in the component.
I have a form in the modal window. If a user closes the window ($modal.close), and then opens again, the data entered will still be there.
...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by samydoesit** [comment]
Did you try to null it yourself?

**Comment by Qwoxa** [comment]
Yes, I did.

The issue was that I had the container, which hold the all the state inside. So, when I emitted $modal.close, the modal was destroyed, but the state in the container was alive.
For solving this I needed to destroy container by emitting 'closeModal' to the parent.

Thanks.

**Comment by camielm** [comment]
I'm having the same issue, @Qwoxa  could your provide an example of your solution?

**Comment by Qwoxa** [comment]
> I'm having the same issue, @Qwoxa could your provide an example of your solution?

You have to store the state inside the modal itself, not in the parent. Then when the modal is destroyed, the state will be lost.

For example, you have Settings component, which holds a state for the ChangePasswordModal component (which is a modal).
```
<template>
  <div class="settings">
    <ChangePasswordModal :new-password="newPassword" />
  </div>
</template>

<script>
import ChangePasswordModal from '../ChangePasswordModal';

export default {
  name: 'Settings',

  data() {
    return {
      newPassword: '',
    };
  },
};
</script>
``` 
If you destroy a modal, and then mount it once again, the state will be the same, and you'll see the new password property as before. So, you have to either transfer all the state to the ChangePasswordModal component, or to destroy Settings component as well.

**Comment by camielm** [comment]
for starters, thanks!
I understand what you are saying but not how to implement it. (fairly new with Vue).

My situation:

login.vue compoment:
<template>
	<modal name=“login”>
		<button @click="$modal.hide('login')">close</button>
		<input type=“text” name=“user” v-model=“user”>
	</modal>
</template>
<script>	
	export default {
	data(){
		return {
			user : “”
		}
	}	

When I close the modal and re-open it, the user name is still filled in.
How can I transfer the state to the login modal?

**Comment by Qwoxa** [comment]
> How can I transfer the state to the login modal?

You have to create some component for modal.
For example, LoginFormModal. Put the data from the Login component to the LoginFormModal component, then import LoginFormModal into Login component.

**Comment by camielm** [comment]
@Qwoxa got it, thanks
