### ISSUE TITLE
How to don't destroy slot component in modal?

### ISSUE THREAD

**Issue by martell2010** [euvl/vue-js-modal#506]
Hi, thank for this project.
#### Problem: 

I have component with form in modal. I don't want destroy it. How can I do it? I tried use keep-alive in slot and wrap modal, but it don't work. 

#### Example & screenshots:
AuthModal is destroyed for all this cases:

 

    <modal name="auth"
      height="auto"
      width="480px"
      :adaptive="true"
      :scrollable="true">
      <keep-alive>
        <AuthModal />
      </keep-alive>
    </modal>

    <keep-alive>
      <modal name="auth"
        height="auto"
        width="480px"
        :adaptive="true"
        :scrollable="true">
        <AuthModal />
      </modal>
    </keep-alive>

    <keep-alive>
      <modal name="auth"
        height="auto"
        width="480px"
        :adaptive="true"
        :scrollable="true">
        <keep-alive>
          <AuthModal />
        </keep-alive>
      </modal>
    </keep-alive>

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by martell2010** [comment]
Have any advices?

**Comment by ricky11** [comment]
did you solve this?
