### ISSUE TITLE
Pls, add method to manually resize modal

### ISSUE THREAD

**Issue by DenniLa2** [euvl/vue-js-modal#507]
Hello
Thanks for you modal
Now there is no way to change the height / width of the window after it appears

Add, please, method to manually changing width height of modal. Calling like this:
In template
`
<modal ref="modalRef">
`
in script

    methods: {
        resize() {
            this.$refs.modalRef.resize({ width: '100px', height: '200px' })
        },
    }

**Comment by invisor** [comment]
+1
I want to change modal width dependently on a device window width. For example for mobile devices, I want to show modal with 100% width, on other devices 60%. But there is no way to do this

**Comment by garbinmarcelo** [comment]
Hi, any news about it?

**Comment by xvladxtremal** [comment]
Any news +1 ?

**Comment by axetroy** [comment]
Any news +1 ?
