### ISSUE TITLE
Does not work with Turbolinks

### ISSUE THREAD

**Issue by guillaumebriday** [euvl/vue-js-modal#508]
#### Problem: 

This component only works on the first page load with Turbolinks and vue-turbolinks.

#### Example & screenshots:

Neither using the `modals-container` component in the view nor using `injectModalsContainer` in the plugin declaration works after page visits.

Do you have any idea how I could do that ?

Thank you for your work !!

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by adrianthedev** [comment]
Could we bring open this up? If someone could give me some guidance on how to get started on a PR for this (big picture where to start), I could put in some work.

**Comment by euvl** [comment]
Hey @adrianthedev, thanks for looking into this. Feel free to shoot question, to start you can build the modal library locally using `npm run build'

**Comment by adrianthedev** [comment]
Hey, sorry about the radio silence. I ended up removing turbolinks altogether from this project. 
I'm not going to be able to work on this at this time.

**Comment by guillaumebriday** [comment]
@euvl Could you please reopen this issue?

I tried with 1.x and 2.x, it does not work. I'm using the https://github.com/jeffreyguenther/vue-turbolinks adapter and it works fine with every single other components I have in my application.


This is a screenshot on the first load:
![Screenshot 2020-12-17 at 23 06 23](https://user-images.githubusercontent.com/8252238/102549528-8daebb00-40bc-11eb-9610-676324e9e518.png)

After going back from another page, we can see the calendar (which is in Vue too) but I cannot open the modal now):
![Screenshot 2020-12-17 at 23 06 47](https://user-images.githubusercontent.com/8252238/102549568-9c956d80-40bc-11eb-9257-d2746225313e.png)

Any idea?

**Comment by sergomet** [comment]
@guillaumebriday share the code please (part of it ... where the calendar and modal init). I am using the modal in the same way and it works for me, the only problem would be if you have async data in your modal (i.e: from an ajax call).
