### ISSUE TITLE
Content is clipped

### ISSUE THREAD

**Issue by at0g** [euvl/vue-js-modal#51]
The height on the modal doesn't resize to the content?
I've tried `:adaptive="true"` but it seems to have no bearing on the height.

Saw a similar issue (#48) that's been closed?

As a courtesy to others, it would be nice to update the readme/examples and mention that the module is only suitable for fixed size content.

**Comment by euvl** [comment]
Yeah, thanks for your feedback, im working on that.

**Comment by euvl** [comment]
Hey @at0g, @nya1, 

In `v1.2.6` i've added support for height="auto" (p.s. `resizable` will be turned off if height is auto)

Also if you think that your content height might exceed window height - you can set new flag `:scrollable="true"` to make modal scrollable 😄 

Cheers.

**Comment by euvl** [comment]
Link for docs: https://github.com/euvl/vue-js-modal#height-auto
