### ISSUE TITLE
[Question] How to access $modal in vuex store?

### ISSUE THREAD

**Issue by jamesmorgan** [euvl/vue-js-modal#518]
#### Problem: 

Hi all, I am trying to push some modal launching into a vuex store form a component so it more easily be triggered from common actions. 

Although I am struggling to work out how?

Any ideas if this is possible?

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by fraserk** [comment]
You can do this in your store. 
~~~this._vm.$modal.hide("modal")~~~

**Comment by derevandal** [comment]
@fraserk do you know how hide dynamic modal?
