### ISSUE TITLE
[Question] How to target the modal class? Want to make it display:flex

### ISSUE THREAD

**Issue by ricky11** [euvl/vue-js-modal#521]
#### Problem: 
I would like to create my own footer which sits at the bottom of the modal, i have currently solved this by creating a inner div with class .container and making it display:flex column. But i would like to target the parent modal and make it flex as well.
...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
You can pass `classes` prop (see docs)

**Comment by ricky11** [comment]
should this work below, the modal border radius does not change

<modal name="test" :classes="radius" </modal>

.v--modal-radius {
    border-radius: 65px;
}

**Comment by ricky11** [comment]
Doesn't seem to work for me.

**Comment by ricky11** [comment]
even with passing :classes="radius" and with .v--modal-radius { )  the modal doesn't show any changes.

**Comment by hoodsy** [comment]
@ricky11 did you figure out a workaround? encountering the same issue

**Comment by ricky11** [comment]
No, still can't make the modal border with a radius.

**Comment by atourkow** [comment]
After banging my head around for hours I finally figured out how to overwrite the `.vm--modal` CSS. 
It's actually VERY simple.  Just add `!important` to the CSS (make sure the `.modal-override` class is global and not scoped)
```html
<modal name="foo" classes="modal-override">...</modal>
```
```css
.modal-override
    background #0008 !important
    border-radius 20px !important
    padding 10px
```
