### ISSUE TITLE
clickToClose doesn't work in app.blade.php

### ISSUE THREAD

**Issue by Photoshopper** [euvl/vue-js-modal#522]
#### Problem: 
:clickToClose="false" doesn't work if modal is located in app.blade.php. In Vue components it works as expected
...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
Sorry but I have no idea what app.blade.php is..  😆

**Comment by Photoshopper** [comment]
it's a layout in Laravel

```
<div id="app>
    <router-view></router-view>

    <modal name="test-modal" :clickToClose="false">
        content
    </modal>
</div>
```

**Comment by euvl** [comment]
You might need to debug this, i don't use laravel & don't know what to look for. 
Let me know if you need help with js stuff

**Comment by keeev** [comment]
Do you have some more code and the mentioned screenshots/examples from your first comment? 
I use `vue-js-modal` in combination with Laravel and maybe can help if you give some more details.
