### ISSUE TITLE
Programmatically add classes to overlay

### ISSUE THREAD

**Issue by dland512** [euvl/vue-js-modal#523]
#### Problem: 
I would like to add a class to the top level overlay of the modal. I'm only doing this for one particular modal so I can't just add more properties to the `.v--modal-overlay` class.

This works pretty well:
```
<modal name="my-modal" class="top-level-modal" :click-to-close="false">
   whatup
</modal>
```
which translates into something like this:

```
<div aria-expanded="true" data-modal="my-modal" class="top-level-modal v--modal-overlay">
   <div class="v--modal-background-click">
      <div class="v--modal-top-right"></div>
      <div class="v--modal-box v--modal" style="top: 210px; left: 568px; width: 600px; height: 300px;">
         <div>whatup</div>
      </div>
   </div>
</div>
```
where the `top-level-modal` class is added to the top most `div`, which is exactly what I want. Is there any way to do this using the programmatic interface? I tried this:
```
this.modal.show(MyComponent, { class: 'top-level-modal '}, { clickToClose: false });
```

but it put the class on the innermost `div`:
```
<div aria-expanded="true" data-modal="_dynamic_modal_0" class="v--modal-overlay">
   <div class="v--modal-background-click">
      <div class="v--modal-top-right"></div>
      <div class="v--modal-box v--modal" style="top: 210px; left: 568px; width: 600px; height: 300px;">
         <div class="top-level-modal">whatup</div>
      </div>
   </div>
</div>
```

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by Szymon-dziewonski** [comment]
Such a nice plugin but I cant use it because there is no way to change classes on modal elements. When I generate classes automatically I cant have fixed class name.
