### ISSUE TITLE
`height: 100vh` shouldn't be used because it's broken on mobile web

### ISSUE THREAD

**Issue by ItamarGronich** [euvl/vue-js-modal#529]
#### Problem: 

`height: 100vh` or `min-height: 100vh` is broken on mobile web.
On mobile chrome for example (and other browsers too), there's a feature that minimizes the top search bar when you scroll down:
![search-bar-shrink](https://user-images.githubusercontent.com/14963977/75328312-79c46f00-5886-11ea-903f-5f0ad88e0d69.gif)
This results in the viewport suddenly being a bit taller.
So, what most browsers decided to do was to let 100vh be equal to the height of the viewport with the search-bar already minimized.
This will result in the modal being a bit taller than the screen and the bottom section of the modal will be cut off.

**Comment by JeRabix** [comment]
```
beforeCreate() {
    // First we get the viewport height and we multiple it by 1% to get a value for a vh unit
    let vh = window.innerHeight * 0.01;
    // Then we set the value in the --vh custom property to the root of the document
    document.documentElement.style.setProperty("--vh", `${vh}px`);
  }
```

and listen resize
