### ISSUE TITLE
Need help with transition

### ISSUE THREAD

**Issue by sKoleff** [euvl/vue-js-modal#530]
#### Problem: 
If I use overlayTransition I can apply every transition which I made, but if i try to apply it to transition it doesn't work. It works only with your transition which is in <style> tag in Modal.vue (line 775 'nice-modal-fade'). The problem is that I want to use transition on modal not the overlay and I can't.
...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by euvl** [comment]
if you pass `transition` prop - transition is applied to modal `overlayTransition` is a transition for the background part (overlay). 

you can pass both if you need, for example if you want the overlay to slowly get dark and the modal to jump out
