### ISSUE TITLE
Elements outside modal are hidden

### ISSUE THREAD

**Issue by alexey-m-ysbm** [euvl/vue-js-modal#533]
Needed to add arrows outside of the modal (next/prev) and we can't currently do it because everything is overflow:hidden'ed.

**Comment by ricky11** [comment]
Did you ever figure this out?

**Comment by mark-drastrup** [comment]
Hi @alexey-m-ysbm & @ricky11 :)

If you are still have this issue then you can solve it by using the `>>>` selector in the css from the parent component to target the css for the modal:

```
.parent >>> .v--modal-overlay .v--modal-box {
  overflow: visible;
} 
```
