### ISSUE TITLE
how to register this component  locally in a component?

### ISSUE THREAD

**Issue by ibreathebsb** [euvl/vue-js-modal#54]
i got a warning:
```
[Vue warn]: Failed to mount component: template or render function not defined.
```
when i use import like this:
```vue
import modal from 'vue-js-modal'
```
and register it in components like this:
```vue
components:{
    ChatRoom,
    Player,
    modal
  },
```
and use it like this:
`<modal name="test"></modal>`

**Comment by euvl** [comment]
You dont have to do it, plugin does registration for you. 
Just do
```Vue.use(modal)```

**Comment by dland512** [comment]
The problem I have with not being able to register the component locally is that I get this error when running unit tests with karma:

> ERROR LOG: '[Vue warn]: Unknown custom element: \<modal\> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Is there a way to fix that?

**Comment by euvl** [comment]
@dland512 its not plugin's issue, please use stackoverflow for such matters.

**Comment by scottadamsmith** [comment]
It would be nice to be able to have the option to register locally in addition to via a plugin for those that prefer to avoid plugins. Would you be open to this change?

**Comment by ArkhipovK** [comment]
Agreed, i want to use modals only on certain pages of my spa, so i dont want to register it globally.

**Comment by euvl** [comment]
@ArkhipovK Nothing stops you from not using modal on some pages and using it on others. The idea of spa itself is that you don't have to use resources to reinitialise same scripts/modules every time you navigate to a new "page" (considering spa is happening on one html page all the time..). 

With the current setup, you allocate resource only once.

Overall, avoiding using plugins just sounds wrong to me. You do not save resources and if you do, you still load & execute like 300kb of javascript with vue framework.
