### ISSUE TITLE
Access from context of NuxtJS

### ISSUE THREAD

**Issue by mohkoma** [euvl/vue-js-modal#543]
#### Problem: 

I have been trying to access the instance in the `context.app` of Nuxt js but it seems that it's not there!
Is there any solution for that?

Thank you

#### Example & screenshots:

```
import Vue from 'vue'
import VModal from 'vue-js-modal/dist/ssr.index'
Vue.use(VModal, { dynamic: true, injectModalsContainer: true });
```

**Comment by euvl** [comment]
Hey @mohkoma, tbh I never used nuxt js so would not know how to approach this issue. If you can help me debug this to understand the problem it would be great.

Thanks.

**Comment by andrew-secret** [comment]
@mohkoma 
I did this in the plugins section to register the `VueJSModal`.

```ts
import Vue from 'vue'
import VueJSModal from 'vue-js-modal'

Vue.use(VueJSModal, { dynamic: true, injectModalsContainer: true, scrollable: false })

```

Then I jumped into my `component` and I could get access through the `@vue/composition-api`

```ts
...
  setup(props, context) {
    const showDynamicComponentModal = () => {
      context.root.$modal.show(
        ModalBase,
        {
          text,
        },
        { height: '100%' }
      )
    }

    const hideDynamicComponentModal = () => {
      context.root.$modal.hide('modal-base')
    }

    return { showDynamicComponentModal, hideDynamicComponentModal }
  }
...
```

Maybe this could help u

Good luck 🍀
