### ISSUE TITLE
Click-event in modal not triggered on mobile device

### ISSUE THREAD

**Issue by Brilbroeder** [euvl/vue-js-modal#545]
on a webpage add a modal,  in that modal add a button, add click-event to that button

In chrome:
Show a modal ok,
click on button, nicely triggered

In chrome with device toolbar toggled to a mobile device:
Show a modal ok,
click on button, NOT triggerd

**Comment by Brilbroeder** [comment]
Any suggestions ?

**Comment by Eleventiy** [comment]
Someone have any suggestions?

**Comment by MathieuDR** [comment]
According to [this issue](https://github.com/euvl/vue-js-modal/issues/118) the click event isn't triggered when drag able is enabled on mobile.

**Comment by Eleventiy** [comment]
[As stated by Google](https://developers.google.com/web/updates/2017/01/scrolling-intervention), they've changed the behavior of passive event listeners only for window, document or body elements.

The fix is add `{ passive: true }` to draggable touch events.

**Comment by euvl** [comment]
@Eleventiy Thanks for finding this, should i add it here:

https://github.com/euvl/vue-js-modal/blob/6f9389421f587a71fefbc739f6143b599cb2a371/src/Modal.vue#L670-L674

?

**Comment by euvl** [comment]
Is this issue happening on android devices? (Still seems to work for me on iphone)

**Comment by aloiseau17** [comment]
It seems issue is still happening. I just try demo page [http://vue-js-modal.yev.io/](http://vue-js-modal.yev.io/), last modal "Dynamic: Component Modal with modal params" on my Android phone and chrome device devtool.
