### ISSUE TITLE
Reset focus after modal is closed for accessibility

### ISSUE THREAD

**Issue by NateWr** [euvl/vue-js-modal#547]
#### Problem: 
When a modal is closed, I want to set the keyboard focus back to the element that was focused when the modal was opened. This is an accessibility requirement that we face in our project.

I would like to capture the previously focused element by using `document.activeElement` in the `before-open` event. However, it appears that focus has already been moved to the `<body>` element by the time this event fires.

At the moment I have to work around this by capturing the focus element every time that I open a modal, but I would like to find a general solution so that it happens without requiring each developer to remember to do it.

#### Example & screenshots:

```
<template>
	<div>
		<button @click=$modal.show('example')">Toggle</button>
		<modal
			name="example"
			@before-open="beforeOpen"
		>
			...
		</modal>
	</div>
</tempate>

<script>
export default {
	methods: {
		beforeOpen() {
			// The activeElement is the <body>
			console.log(document.activeElement);
		}
	}
};
</script>

**Comment by euvl** [comment]
The problem here if the focus is not changed when the modal is opened, the focused element will still be getting events. For example, if you do kepress and press Escape button, the plugin would not catch event. I remember there were lots of issues with leaving focus outside of the modal but it was in 2017... and i dont remember what they were

**Comment by NateWr** [comment]
Thanks for the reply @euvl! I am not suggesting that the focus never changes, but that you delay moving the focus until after the `beforeOpen` event is fired. This will allow me to catch the focused element before it is blurred.

Alternatively, could there be a new event that is fired before vue-js-modal does anything to the state or the dom, so that a proper "before" snapshot can be captured?

**Comment by euvl** [comment]
To help you with the solution, you can create your custom modal using plugin, i have not tried this but:

```
// DaModal.vue
<template>
	<modal
		v-bind="$attrs"
		@before-open="beforeOpenProxy"
    @closed="closedProxy"
	>
		<slot/>
	</modal>
</template>

<script>
export default {
  name: 'MyLovelyModal',
  methods: {
    beforeOpenProxy(event) {
      this.cachedActiveElement = document.activeElement
      this.$emit('before-open', event)
    },
    closedProxy(event) {
      if (this.cachedActiveElement) {
        this.cachedActiveElement.focus()
        this.cachedActiveElement = null
      }

      this.$emit('closed', event)
    }
  }
}
</script>


```

**Comment by euvl** [comment]
Ahh, i didn't realise the problem and until i finished the example you have replied 😄

**Comment by euvl** [comment]
So the logic for opening is:
```
      if (beforeEventName === 'before-open') {
        /**
         * Need to unfocus previously focused element, otherwise
         * all keypress events (ESC press, for example) will trigger on that element.
         */
        blurActiveElement()

        if (reset) {
          this.setInitialSize()

          this.shift.left = 0
          this.shift.top = 0
        }

        if (scrollable) {
          document.body.classList.add('v--modal-block-scroll')
        }
      } else {
        if (scrollable) {
          document.body.classList.remove('v--modal-block-scroll')
        }
      }

      let stopEventExecution = false

      const stop = () => {
        stopEventExecution = true
      }

      const beforeEvent = this.createModalEvent({
        stop,
        state: nextState,
        params
      })

      this.$emit(beforeEventName, beforeEvent)

      if (!stopEventExecution) {
        this.visible = nextState
      }
```

It is clearly the problem, even if event is canceled - the blur will be taken off the activeElement, let me fix this

**Comment by euvl** [comment]
Coolio, try vue-js-modal@1.3.35 if it works. I got to join work meetings but will be back in the evening so let me know if it works 👍

**Comment by NateWr** [comment]
Works, thanks! :tada:
