### ISSUE TITLE
How can i trigger this with a button?

### ISSUE THREAD

**Issue by marianne-fullstack** [euvl/vue-js-modal#548]
#### Problem: 
This is such a noob question but i cant see any examples of triggering a modal using a button
Can you show me an example? Everytime I try to place the simplest example on my app it keeps on displaying on my whole screen without me triggering it.. i hope you can help a beginner! :D

**Comment by euvl** [comment]
Hmm you need to post some code, otherwise it is impossible to understand what the issue is. You can show modal by calling this.$modal.show(name) from anywhere within your system
