### ISSUE TITLE
Dynamic modal using globally registered component not working

### ISSUE THREAD

**Issue by frufin** [euvl/vue-js-modal#549]
First, many thanks for your great work !

#### Problem: 

Using a component name as a first arguments works fine when declaring the component locally, but not globally. In that case, i get a a compilation error.

#### Example & screenshots:

This works: 
```
import Alert from '@/components/dialogs/Alert.vue'

export default{
   ...
   methods:{
       displayAlert(){
          this.$modal.show(Alert, ...)
       }
   }
}
```
But when registering my component globally, i get that error:

<img width="486" alt="Capture d’écran 2020-04-17 à 18 35 30" src="https://user-images.githubusercontent.com/17597383/79592641-8d4bc380-80da-11ea-80be-b1ad11cdd95c.png">

I ensured the component was really globally registered:

<img width="458" alt="Capture d’écran 2020-04-18 à 17 48 47" src="https://user-images.githubusercontent.com/17597383/79642298-07dd1780-819d-11ea-8ac5-fe98edab2a42.png">

**Comment by euvl** [comment]
Hey, thanks :) 

What do you mean by global? 

If you used `Vue.component(name, Component)` - you can render this component  without registration in vue but it does not mean you can refer to it by name i would think..

Or you actually would need to do something like `this.$modal.show(Vue.options.components.Alert)` or smth like that

**Comment by frufin** [comment]
Hi euvl, 

You are right, globally registered components cannot be accessed by name.

They can be easily accessed using  `this.$options.components.Alert`
as JS will follow the prototype chain if it doesn't get the component from inside the current Vue instance.

Thank you for your reply !
