### ISSUE TITLE
❗️❗️❗️2.0.0-rc.3+ version 

### ISSUE THREAD

**Issue by euvl** [euvl/vue-js-modal#551]
Changelog (potentially has breaking changes): 

* Using ResizeObserver instead of MutationObserver
* Using transition states to coordinate modal & overlay transitions (instead of delays)
* Using prettier
* Overlay is not a parent of the modal anymore (now has independent transition)
* Renamed **Event.stop => Event.cancel**
* Removed `v--modal-background-click` element
* Removed `v--modal` default class
* **Removed "delay" property** - component is relying on modal & overlay transition durations
* Added naive implementation of **focus trap**
* Added source-maps
* Added `hideAll` for dynamic modals
* Fix: dialogs not working when componentName is changed
* Fix: ActiveElement is blurred after before-open is fired - not it is possible to cache document.activeElement

If you have found any issue related to the latest changes, please tag this thread in your ticket.

Thanks ❤️

**Comment by eduarguz** [comment]
Is this published?

> Removed v--modal default class

I am using `vue-js-modal@2.0.0-rc.3` and cannot find an easy way to:
- change borde-radius of "modal box" (Could be related https://github.com/euvl/vue-js-modal/issues/521)
- add margin on adaptive mode. (Could be related https://github.com/euvl/vue-js-modal/issues/158)

**Comment by euvl** [comment]
hmm, yeah it should be published. i think it depends on where the css is imported in your app, if modals default css ifile is imported after the bundled styles - you will get this issue

**Comment by eduarguz** [comment]
Yeah, that is what happens in my app :/
I dont think I can change that, Vue loads components/libraries css after my own.

**Comment by euvl** [comment]
yeah, not sure plugin can fix that unfortunately :(

**Comment by DavidRouyer** [comment]
I have the same problem with the CSS file import order. In production, the modal styles are imported after my own so the classes I passed to the modals get overridden.
There is a simple fix. Do not bundle the CSS file by default and let us import it where we want it.

**Comment by DavidRouyer** [comment]
Opened an issue in #587 to discuss more about it
