### ISSUE TITLE
modal not loading css

### ISSUE THREAD

**Issue by vdiaza** [euvl/vue-js-modal#553]
Hi, 
I am experiencing this bug just specifically when coming from another route that didn't have any modal on it.
it seems that it only loads the modal css such as .v--modal when the page has acually rendered a modal from the beginning.

I am using Nuxt with the SSR plugin

    "vue-js-modal": "^1.3.33",
    "nuxt": "^2.0.0",

hopefully you can help me out! thanks

**Comment by mrFANRA** [comment]
```
import Vue from 'vue';
import VModal from 'vue-js-modal/dist/ssr.index';
import 'vue-js-modal/dist/styles.css';
```

You can try import directly

**Comment by euvl** [comment]
Hm there seems to be lots of issues with using plugin in ssr, is there aythng can be done to fix it?
