### ISSUE TITLE
vue-js-modal and nuxt SSR

### ISSUE THREAD

**Issue by ishetnogferre** [euvl/vue-js-modal#557]
#### Problem: 
I get a "window is not defined" error when using this plugin in Nuxt.

#### Version:
Nuxt: 2.12.2
Vue-js-modal: 2.0.0-rc.3

#### Example & screenshots:
<img width="1283" alt="Screenshot 2020-05-14 at 12 55 26" src="https://user-images.githubusercontent.com/6649706/81926594-78335900-95e2-11ea-8dcb-ee36c3a966ae.png">

The content of my 'vue-js-modal.js' in ~/plugins
```
import Vue from 'vue'
import VModal from 'vue-js-modal/dist/ssr.index'
import 'vue-js-modal/dist/styles.css'

Vue.use(VModal)
```

**Comment by hifull** [comment]
I don't know your needs, but you can turn off the plugin in SSR-mode (because "window" is not existing on server without any workarounds).

I use plugin in this way in `nuxt.config.js`:

**Comment by hifull** [comment]
I don't know your needs, but you can turn off the plugin in SSR-mode (because "window" is not existing on server without any workarounds).

I use plugin in this way in `nuxt.config.js`:
```
plugins: [
  { src: '@/plugins/vue-js-modal', ssr: false }
],
```

**Comment by arthur-sorami** [comment]
I have same situation.

vue-js-modal also supported SSR mode, so it could be used without problems until now.

However, the version of nuxt is 2.12.2, and when developing in SSR mode, I also got "window is not defined" ...

**Comment by paolomangiadev** [comment]
the readme states that ssr is supported but it's not working, ssr: false is just a workaround. Also it still gives an error:
- e._ssrNode is not a function

**Comment by defcom20** [comment]
yo agregue { src: '~/plugins/vue-js-modal', mode: 'client' } y me funciona todo bien
