### ISSUE TITLE
Scrollable not working when dynamic content in modal is rendered after opening modal

### ISSUE THREAD

**Issue by TomDeSmet** [euvl/vue-js-modal#563]
#### Problem: 
I have a modal which has 2 Vue components inside that depend on API calls. So nothing is rendered initially but after a few milliseconds the API returns the correct data and the Vue components are rendered.
The height of the modal adapts to this new content, but a scrollbar isn't triggered.

#### Version:
2.0.0-rc.3

#### Code example:
```    
Vue.use(VModal, { dynamic: true, dynamicDefaults: { clickToClose: false }, injectModalsContainer: true })
```

```
this.$modal.show(ProductModal, {
    productId: productId,
    defaultVariantId: variantId
}, {
    height: "auto",
    width: "90%",
    scrollable: true,
    adaptive: true,
    'max-width': 1200
});
```

> I have checked stackoverflow for solutions and 100% sure that this issue is not not related to my code.

**Comment by euvl** [comment]
Can you please create a sandbox to replicate an issue? Thanks

**Comment by TomDeSmet** [comment]
I did some further testing, but I'm not understanding what's going on.
It goes wrong on Firefox. At first, it seems that it works, but whenever I click somewhere, scrolling gets disabled.

On Chrome and Safari it seems to go fine.
But on neither browser I can drag the browser bar itself. I can only scroll with the mouse wheel.

https://xfp79.csb.app/

**Comment by bogdan-dukhevych** [comment]
I have the same issue but just with a list of images inside modal. Also Firefox.

**Comment by kimchristiansen** [comment]
Same here on Firefox 77.0.1
The scrollbar on the right appears. Scrolling with keyboard is no problem, but i can't scroll with the mouse wheel.

**Comment by Mr-Ev-H** [comment]
I'm experiencing the same issue - I can scroll fine on Chrome, but have issues scrolling the modal with Firefox 77.01. Keyboard scrolling works fine but mousewheel does not.

I've noticed that scrolling works if the scroll event starts when the mouse pointer is over either an anchor element or an element that receives mouse input in some way (in my case GChart).

Crude diagram:

`<Component>
  <Modal>
    <p>
      Can't scroll
    </p>
    <gchart>
      Can Scroll
    </gchart>
    <a>
      Can Scroll
    </a>
  </Modal>
</Component`

My hacky fix will be to wrap the body of the modal in an anchor tag.

**Comment by kimchristiansen** [comment]
The error is not only with dynamic content, but also with normal added modals.

**Comment by LuizVisnadi** [comment]
I'm encoutering the same issue with the 2.0.0-rc6 version and using dynamic modals.

After some investigation, _div_**.vm--overlay** is the source of the problem. Overlay style rules seem to conflict with container style rules, specially **"height: 100vh"**.

When I add the css rules below, the error disappears.

```css
.vm--overlay {
  	height: 0 !important;
}
.vm--container {
  	/* add to keep a modal backdrop */
  	background-color: rgba(0, 0, 0, 0.85) !important;
}
```

**Comment by FrancisCaille** [comment]
Having the same problem
