### ISSUE TITLE
Distinguish between "handleBackgroundClick" and "esc.keyup event"

### ISSUE THREAD

**Issue by curiosity-hyf** [euvl/vue-js-modal#564]
#### Problem: 
I want to close modal by clicking on the background BUT not be closed by pressing ESC.
I found this code.
``` javascript
if (this.clickToClose) {
  window.addEventListener('keyup', this.handleEscapeKeyUp)
}
```
Can provide something like `closeOnPressEscape` instead of it ? Thanks.

#### Version:
1.3.33

#### Example & screenshots:

> I have checked stackoverflow for solutions and 100% sure that this issue is not not related to my code.

**Comment by euvl** [comment]
Closing modals through escape is w3c requirement for a11y, see here in the keyboard support section: https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

**Comment by curiosity-hyf** [comment]
I use codemirror.js in the modal and use escape to exit full-screen editing. Modal was also closed together. Is there any way to solve this problem?

**Comment by avmalyutin** [comment]
I am also interested in this feature. I have some rare cases, like wait dialogs, which should not be closed by ESC key.
Is it possible to:
- Add property **closeOnPressEscape**, which is by default **true**. By default, the dialog will be closed, when ESC is pressed. However, with this property we can override this functionality.
- Add a link in documentation for this property to W3C standards, indicating that such behavior is discouraged.

If this is approved, I can try to implement this feature and make a pull request.

**Comment by ajdvoynos** [comment]
I also need the property @avmalyutin mentioned above. My use case is showing a modal while an ajax request finishes. I don't want users interacting with the page before the request finishes or times out. Does anyone have any workarounds?

**Comment by syJSdev** [comment]
I also need this property.
