### ISSUE TITLE
Window jumps to top when opening dynamic modal

### ISSUE THREAD

**Issue by intergalactisch** [euvl/vue-js-modal#566]
#### Problem: 
I am using a basic dynamic implementation of the plugin, and have registered it (in Laravel) like so:
```
import Vmodal from 'vue-js-modal';
Vue.use(Vmodal, {
    dynamic: true,
    injectModalsContainer: true,
    dynamicDefaults: {
        height: 'auto',
        scrollable: true,
    },
});
```

Whenever I click on a button to show a modal, the window jumps to the top of the page, instead of staying in position. Any ideas on how to fix this?

#### Version:
^2.0.0-rc.3

**Comment by euvl** [comment]
HI, thanks for the report, can you please create a sandbox or repo so we could replicate an issue?
Thanks
