### ISSUE TITLE
Modal not properly resizing and repositioning on orientation change

### ISSUE THREAD

**Issue by the-worldly-monkey** [euvl/vue-js-modal#568]
Hello, I am experiencing this strange behavior with vue-js-modal (**2.0.0-rc.3**) on mobile (iOS 13) Chrome and Safari, please see the 2 videos linked:

- Safari: https://streamable.com/kd7vlx

- Chrome: https://streamable.com/ebjn6c

As you can see, on Safari it behaves correctly on first orientation change, then it screws up by not properly resizing the overlay (you can see the background at the bottom when returning to portrait orientation).

On Chrome, instead, it completely screws up the positioning since the very first orientation change, and also it does not resize the modal at all when switching from portrait to landscape. You can see that, unlike Safari, the width and height do not change, plus the position is not as it should be (horizontally centered).

EDIT: I will add some details that might be useful to identify the issue better. The modal is **dynamic** and created with the following options:

```
{
  width: "70%",
  height: "auto",
  clickToClose: false,
  classes: "loginModal",
  name: "loginModal"
}
```

and with the following CSS applied:

```
.loginModal {
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: #9cf!important;
  border-radius: 3.35vmin!important;
}
```

Any clue or ideas on how to fix it?

**Comment by aoimewo** [comment]
same problem on orientation
the modal not center after orientation change.
(both happened on real mobile device and Chrome F12 device testing)

**Comment by ricky11** [comment]
are your styles scoped?

**Comment by the-worldly-monkey** [comment]
If you mean the styles where I have the <modals-container/> then no, they are not scoped.

**Comment by euvl** [comment]
Is there an event that is fired when orientation changes?

**Comment by the-worldly-monkey** [comment]
I am not exactly sure if I understood your question correctly. Are you asking me if I added a custom event listener for the `orientationchange` event somewhere? If that's the case, then no, there is no custom handler nor for that event, nor for the `resize` one, which is also fired when orientation changes on those browsers, I think.

**Comment by euvl** [comment]
Thanks, `orientationchange` event is what i was looking for 😄

**Comment by RasmusO95** [comment]
Can confirm, this is using chrome on iphone 11 

https://streamable.com/rp96vl
