### ISSUE TITLE
Setting data outside Modal? (Help) 

### ISSUE THREAD

**Issue by smholsen** [euvl/vue-js-modal#57]
Hi!
Is it possible to set data or props inside a modal from outside, without giving it as props in the declaration?

Like, if I define a modal like this; <error-modal></error-modal>
but I want to show it with different parameters, depending on where the 'show' is called, like for example like this; 
@click="$modal.show('error-modal', 'data'));"
Is it possible to achieve this in some way?
Would greatly appreciate any help :)

**Comment by smholsen** [comment]
Like a verification modal where you accept or deny deletion of a user, so you need to know what user is in question inside the modal :)

**Comment by euvl** [comment]
Hey,

Try this: 

```
@click="$modal.show('error-modal', { foo: 'bar' });
```

In modal component:

```
<template>
  <modal name="error-modal" @before-open="beforeOpen">
  ...
  </modal>
</template>
```

```
methods: {
  beforeOpen (event) {
    console.log(event.params) // <- your data is here
  }
}
```

For more a workign example look in demo -> ConditionalModal.vue

**Comment by smholsen** [comment]
Thank you so much mate!
This was exactly what I was looking for 👍

**Comment by euvl** [comment]
No probs 😄 Thanks for using the plugin!
