### ISSUE TITLE
Changing width of modal in media query

### ISSUE THREAD

**Issue by cvakodobro** [euvl/vue-js-modal#570]
#### Problem: 
I want to change width to 100% with media query but i can't. I tried to change it in class but it is not the way.

`@media screen and (max-width: 700px){
    .v--modal-box.v--modal{
        width: 100%;
        top: 50px;
        left: 0;
    }
}`
 after that modal still have these values:

![image](https://user-images.githubusercontent.com/40690031/83948482-bb699c00-a81d-11ea-82b3-d4cd597ca91a.png)

**Comment by ricky11** [comment]
are you using scoped styles?

**Comment by cvakodobro** [comment]
oh, yes i am using scoped. it's ok now. thank you!
