### ISSUE TITLE
Can use a psuedo element ::after on the modal container?

### ISSUE THREAD

**Issue by ricky11** [euvl/vue-js-modal#572]
#### Problem: 
I am trying to use vuejs modal to create a tooltop with a arrow 

Is it possible to use psudo elements on the modal?
#### Example & screenshots:

.container {
    position:relative;
    display:flex;
    flex-direction: column;
    padding:2rem;
}

.container::after {
    content: '>>>';
    border: 5px white solid;
    position: absolute;
    left: 100%;
    top:50%;

}

> I have checked stackoverflow for solutions and 100% sure that this issue is not not related to my code.

**Comment by euvl** [comment]
tbh I don't think this package fits your usecase of making tooltips, there is https://github.com/euvl/vue-js-popover if you want, but I didn't really maintain it much. I am sure there are good tooltip libs for vue
