### ISSUE TITLE
Question: Is it possible to not to disable background when modal in open state.

### ISSUE THREAD

**Issue by pranavkumar389** [euvl/vue-js-modal#573]
Is there any way to NOT to disable the main content(background) of the page?

Modal vs Non-Modal:-

https://www.nngroup.com/articles/modal-nonmodal-dialog/#:~:text=Definition%3A%20A%20modal%20dialog%20is,special%20mode%20requiring%20user%20interaction.&text=In%20contrast%2C%20nonmodal%20(or%20modeless,functionality%20of%20the%20user%20interface.

**Comment by euvl** [comment]
Hey, nope, unfortunately there is no such option
