### ISSUE TITLE
Horizontal alignment doesn't exclude window scroll bar width

### ISSUE THREAD

**Issue by ptilli** [euvl/vue-js-modal#58]
This is a great component, but there is a slight issue with horizontal alignment.

Web page content is usually aligned with scroll bar taken into account (document.body.clientWidth). However, this modal includes scroll bar width (window.innerWidth), which makes it aligned a bit too much on the right. Depending on the content behind, it looks more or less like a layout bug. 

<img width="1010" alt="screen shot 2017-08-06 at 23 09 00" src="https://user-images.githubusercontent.com/23285659/29006710-2282bca0-7afe-11e7-83f3-f8fe1c177e76.png">

I think there should be at least a prop to choose whether to exclude scroll bar width.

**Comment by euvl** [comment]
Hey @ptilli,

Thanks for spotting it, ill change it to `document.body.clientWidth`.

**Comment by euvl** [comment]
Hey @ptilli, should be fixed in latest version 👍

**Comment by ptilli** [comment]
Tanks for the quick fix @euvl! Tested and it works.
