### ISSUE TITLE
Dynamic modal won't show

### ISSUE THREAD

**Issue by hitostacha** [euvl/vue-js-modal#580]
#### Problem: 
The dynamic modal isn't showing, the component I'm calling is registering properly as I can see it on the HTML file, but isn't displaying due to CSS properties

#### Version:
2.0.0-rc.3

#### Example & screenshots:

I have a button which calls the modal, and it's working, this is the code for calling the modal:
```
this.$modal.show(
        Notification,
        {},
        {
          height: 'auto'
        },
        {
          'before-close': () => {
            console.log('this will be called before the modal closes')
          }
        }
      )
```
The modal displays is loaded in the DOM, like this:
![image](https://user-images.githubusercontent.com/40004595/85773126-8600f180-b6eb-11ea-9094-74d3d26cdb7c.png)

But as you can see, the css attributes are by default display none, am I doing something wrong?

> I have checked stackoverflow for solutions and 100% sure that this issue is not not related to my code.

**Comment by hitostacha** [comment]
Apparently it doesn't work only if it's a dynamic modal, it works just fine if I use the modal component as a wrapper for my component

**Comment by euvl** [comment]
Hey, can you please try the 1.3.34 version, I am wondering if it is a bug in the release candidate

**Comment by hitostacha** [comment]
Hi, thanks for your reply!
Also, I tried downgrading to the 1.3.34 version and it's still the same bug, the component mounts and render when I trigger the modal, but doesnt show

**Comment by euvl** [comment]
Weird, can you please create a sandbox or smoth so I could replicate it?

**Comment by mvalitov** [comment]
i faced the same problem. In my case, the cause of the problem turned out to be this:
`Vue.component('modal', require('./components/ModalComponent').default);`
I had another custom component called `modal`. After renaming the problem disappeared

**Comment by mofolo** [comment]
Hi! 
Experienced the same problem.
The issue is because your `Notification` component has a <Model></Model> segment within it as the top-level DOM.
Change it to a <div></div> or something else and it should work.
