### ISSUE TITLE
Passing options to dialog

### ISSUE THREAD

**Issue by VincentVanclef** [euvl/vue-js-modal#583]
Is it possible to pass options to the dialog? If i want to not be able to close from clicking the background (clickToClose) ? 

Ive tried a lot of possible combinations with no luck, the documentation seems pretty slim on the dialog part, am i missing something ?

**Comment by nacr** [comment]
Same problem any luck?

**Comment by nacr** [comment]
This was my solution:

**<v-dialog :click-to-close="false" />**

hope it helps you m8

**Comment by VincentVanclef** [comment]
Ahh nice! I ended up recreating The dialog as a modal xD so i got the same functionality plus all the other props

**Comment by euvl** [comment]
Hey, dialog is an example of the modal and in fact, it is exposing the same features as all other medals, meaning that you can pass props, params, etc.

**Comment by RasmusO95** [comment]
@euvl  We are 3 people here who are unable to pass props to the dialog. Could you atleast show a code snippet or explain how to do it? Clearly the documentation needs some update as to how this is done, as doing it the same way as a modal doesnt seem to work.

**Comment by embluk** [comment]
The `click-to-close` property is wrong on the docs as it is listed as `clickToClose`?
