### ISSUE TITLE
Buttons are not added

### ISSUE THREAD

**Issue by ibrahem-kamal** [euvl/vue-js-modal#584]
#### Problem: 

i try to initialize a modal with buttons but the buttons is not shown

![image](https://user-images.githubusercontent.com/38753243/86373668-efe94000-bc83-11ea-8537-0284f91faf23.png)
![image](https://user-images.githubusercontent.com/38753243/86373701-f972a800-bc83-11ea-8fc0-c834444dedac.png)
![image](https://user-images.githubusercontent.com/38753243/86373777-1018ff00-bc84-11ea-8f32-ef7d2ab06c11.png)

**Comment by euvl** [comment]
Buttons is a feature of the "Dialog" component. You are using "MOdal" which is kind an un-opinionated framework for building models, dialogs, windows, etc... so it does not know what buttons are.
