### ISSUE TITLE
Vue3 support

### ISSUE THREAD

**Issue by Xenoha** [euvl/vue-js-modal#586]
#### Problem: 
Getting an error when using with Vue3.

Looking to see if there are plans to support upcoming Vue3.
#### Version:
Version: 2.0.0-rc.3

#### Example & screenshots:
```
Uncaught TypeError: a is not a constructor
    at Object.install (vue-js-modal.js:20)
    at Object.use (vue.js:3310)
    at main.js:8
```

> I have checked stackoverflow for solutions and 100% sure that this issue is not not related to my code.

**Comment by euvl** [comment]
I am not using vue anymore and unfortunately would not have enough time to learn about all the new things. If you, or anyone reading this thread would have an interest - please feel free to give it a go 👍
