### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by euvl** [euvl/vue-js-modal#588]
Hey guys, thank you for using this library, I hope it has helped you build some awesome things!

It has become increasingly hard for me to maintain this project. I have not been using Vue in prod for almost 3 years and I don't have enough free time that I can spend on learning new things about vue, srr, etc.

Hence, I am trying to find someone who is interested in maintaining & building new features. If you are interested, please either reply here or send me an email at yev.dev@gmail.com

Thanks,
yev

--- 

Edit: you do not need an "approval" or anything to start contributing - JUST DO IT 

<img src="https://i.pinimg.com/originals/85/0f/f0/850ff03095c99048708074cb1b3a3615.gif">

**Comment by Jacob-Marshall** [comment]
Hi yev,

I'll help maintain it.

**Comment by Codefor-Future** [comment]
I want to contribute to this project :)

**Comment by maxvanceffer** [comment]
Maintainer found?

**Comment by euvl** [comment]
Nope 😞

**Comment by ricky11** [comment]
you have some great vue packages on your profile, 2 of which i use. 
did you switch to react?

**Comment by euvl** [comment]
yeah, I did, it's much easier to have cross-functional teams with react/react native and my previous job was in react.

**Comment by ricky11** [comment]
but you secret prefer vue right..?  only if everyone else was using it.

**Comment by euvl** [comment]
yes, tbh i would :D

**Comment by Gerdon262** [comment]
I would like to contribute as well, I've already made a pull request for something I needed, which might help others as well.

Maybe you should make a (google) form with a few questions, or an introduction of the person who wants to contribute, this way you might find someone based on the given answers.

Maybe you prefer to stay as a maintainer, but let the community help you out just like we do now. This way you still have control over your 'child' and let others help you grow it up.

If there is a shortage of time on your side, maybe get another maintainer who will help to accept PR's.

These are just a few options/suggestions, you could also ignore those. All up to you.

**Comment by DJEDAINI** [comment]
Want to contribute :)

**Comment by juliageek** [comment]
@euvl Did you decide on a contributor yet? I am also interested to help maintain this project.

**Comment by euvl** [comment]
Hey, no luck yet.

I got A LOT of emails like "Transfer the repo to me and I will contribute".

I had to decline those for many reasons, particularly:

* I don't know these people, most of them have like 0 contributions to open-source.
* It is dodgy, this package is used by 10000s, what if someone has malicious intent and will inject bitcoin miner or other shady stuff in dist file.
* Even if I am not actively working on this - handing off the project i was working in and out for the last 5 years to someone else "just because they asked" seems unreasonable.

**Comment by euvl** [comment]
BUT just want to highlight that if you guys want to contribute, **JUST DO IT!** (c) Shia LaBeouf

Just create PRs, start working on fixing issues, understand why some things are made in the way they are made, etc;

### 🤗 There are no restrictions on contributing - any registered github user can create a pull request!

**Comment by Gerdon262** [comment]
@euvl Nice to see your response.

As said in my previous comment, you do not have to 'transfer' the project to another contributor. You can just have someone as a collaborator, this will keep you in charge but lift some weight off your shoulder by accepting PR's. If you don't like what that person does just remove him.

**Comment by euvl** [comment]
Ahh you are right there is a difference between contributor and collaborator in the github, i was thinking in the context of contributors (assumed it's `===`) 😄 

I will catch up with PRs during christmas time and will start inviting contributors into collaborators, thanks for your suggesting 👍 🙏

**Comment by jassehomar** [comment]
I would love to be a contributor. At the moment, do you have any feature in mind that you would want to add? I think that can also be a good start for those who would like to contribute.

**Comment by euvl** [comment]
Hey, no particular features in mind but maybe a good start will be something like:

* to investigate what are the requirements for using it in vue 3
* improving unit tests coverage
* this nasty thing i never had time for: https://github.com/euvl/vue-js-modal/issues/335
* and another one: https://github.com/euvl/vue-js-modal/issues/346

Also there was an interesting todo: 
* https://github.com/euvl/vue-js-modal/issues/442

**Comment by hunterliu1003** [comment]
Hi, I'm the author of [vue-final-modal](https://github.com/vue-final/vue-final-modal) and it supports `Vue 2` and `Vue 3` both.
I really learned a lot from **vue-js-modal**. vue-final-modal reference a part of the code of vue-js-modal, for example:

- Dynamic modal
- Transition
- FocusTrap

However, there are still some differences between using vue-js-modal and vue-final-modal.
For example, you must define the CSS for vue-final-modal by yourself because it's a [renderless component](https://adamwathan.me/renderless-components-in-vuejs/).

Assuming you are already using Vue 3 and need a modal component library, maybe you can consider using vue-final-modal.
And if you run into any difficulties when using it, feel free to open a discussion. I will be happy to help you solve the problem.
