### ISSUE TITLE
Documentation moved to https://euvl.github.io/vue-js-modal/

### ISSUE THREAD

**Issue by euvl** [euvl/vue-js-modal#589]
The documentation moved from readme to https://euvl.github.io/vue-js-modal/

As in any contribution-driven project - if you find typos, errors, or want to add more explanations & examples - please do not hesitate and create a PR! All contributions are welcome! ❤️ 

ps. we are using vuepress, check out /docs directory 🤓

**Comment by A7madXatab** [comment]
currently there is a bug where the contents of the docs are not up to date, any ideas why this is occuring @euvl
