### ISSUE TITLE
Nuxtjs - ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Jacob-Marshall** [euvl/vue-js-modal#591]
**This is a duplicate, and I know this but the problem is still here. I have tried everything in the [previous issue](https://github.com/euvl/vue-js-modal/issues/301)**
**I am using version `^2.0.0-rc.5`**

#### Problem: 

When I run `npm run dev` It outputs `ReferenceError: window is not defined` at `node_modules\vue-js-modal\dist\index.js`.

Thanks,
Jacob

**This is not on stackoverflow**

**Comment by euvl** [comment]
for ssr you need to use 
```
import VModal from 'vue-js-modal/dist/ssr.nocss'

import 'vue-js-modal/dist/styles.css'
```
