### ISSUE TITLE
[vue-js-modal] $modal() received object as a first argument, but dynamic modals are switched off.

### ISSUE THREAD

**Issue by Gmiliuta** [euvl/vue-js-modal#592]
#### Problem: 

I could not find any documentation on how to enable dynamic modals. Link in the error does not take you to "dynamic modals section" (https://github.com/euvl/vue-js-modal/#dynamic-modals).

#### Version:

2.0.0-rc.3

#### Example & screenshots:

playVideo(videoPath: object) {
    this.$modal.show(
      ModalVideoPlayer,
      { videoPath }
    );
  }

Thanks!

> I have checked stackoverflow for solutions and 100% sure that this issue is not not related to my code.

**Comment by euvl** [comment]
From now on, you dont need to switch on dynamic models, it just should work (in the latest published version)

**Comment by toleberdyyeva** [comment]
Hi there! Is there some updates with Dynamic Modals on SSR (Nuxt) ?

**Comment by euvl** [comment]
Don't know, i don't think there's anything specific for

**Comment by TiTTY-TWiSTER** [comment]
Hey buddy, am just delete in package.json old version 1.3 and install 2.0 from npm and this f*cking dynamic modal is works... dam
