### ISSUE TITLE
The <v-dialog> tag in vue-js-modal and the <v-dialog> tag in vuetify overlap, and an error occurs.

### ISSUE THREAD

**Issue by hyunsu7993** [euvl/vue-js-modal#594]
### help me...
I am using vuetify in a nuxt based project,
vuetify's v-dialog tag and vue-js-modal's v-dialog tag are OVERLAP and an error occurs.
In this case, is it possible to give the <v-dialog> tag a different name?

**Comment by avpavp** [comment]
I'm also using Vuetify, and things were working fine, but now the dialog just won't show.  I call:

this.$modal.show("dialog", { ...

but nothing happens.  No errors in console; just no dialog shows...

Any ideas?
