### ISSUE TITLE
Does not work with Vue 2.1.0

### ISSUE THREAD

**Issue by hkhandare** [euvl/vue-js-modal#6]

**Comment by euvl** [comment]
Thanks, i'll take a look tomorrow, do you get any specific error @hkhandare ?

**Comment by hkhandare** [comment]
Hi, sorry my bad. 
I just couldn't get it to work by placing the `<modal></modal>` tag directly within a component.
I had to refer it from the root i.e. 'app' by importing the component having the modal tag.

**Comment by euvl** [comment]
@hkhandare So am i getting right, that it does work for you? 

p.s. you always have to specify name, e.g. `<modal name="test" />`

**Comment by euvl** [comment]
hey again, i've just tested using vue 2.1.0, my package.json for demo:

```
  ...
  "dependencies": {
    "vue": "2.1.0"
  },
  "devDependencies": {
    ...
    "vue-template-compiler": "2.1.0",
    ...
  }
```

All features work fine.

**Comment by hkhandare** [comment]
Yes, works. 
Thanks a lot.
