### ISSUE TITLE
Can't figure out how to use this. Documentation is lacking. Where is the button to open the modal ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [euvl/vue-js-modal#600]
Hello !

First of all, I want to say that this library and example page look good.

Secondly, I have read the documentation and I have no idea how to use it.

Thirdly, the examples page should contain the source code, for stupid idiots like to figure out how the hell to use the thing.

I have no idea how to use this because there is no "complete" example anywhere. There's only bits and pieces of information: how to use this, how to use that; but there is nothing that puts them together.

Here is how my Vue component, in which I want to use a modal, looks like:
```
<template>
 <div> <v-dialog /> </div>  
</template>

<script>
import Vue from "vue";
import VModal from "vue-js-modal";

Vue.use(VModal, { dialog: true });

export default {
 name: "Component",
  methods: {
    show() {
      this.$modal.show("dialog", {
        title: "The standard Lorem Ipsum passage",
        text: "Lorem ipsum dolor sit amet, ...",
        buttons: [
          {
            title: "Cancel",
            handler: () => {
              this.$modal.hide("dialog");
            },
          },
          {
            title: "Like",
            handler: () => {
              alert("Like action");
            },
          },
          {
            title: "Repost",
            handler: () => {
              alert("Repost action");
            },
          },
        ],
      });
    },
  }
}
</script>
```

Obviously it doesn't work. `<v-dialog />` renders nothing.

Where is the `button` that should open the modal ?

There is NOTHING in the docs that points to a button.

# What I hope for:

I would like to use a modal inside a component of my own making.

I would like for said modal to open when I press a button of my own making.

I would like said modal to render a Vue component of my own making.

**Comment by GeorgeFlorian** [comment]
Don't worry, I can't stay stupid for too long, so I've figure out how to use this on my own.

Thank you for the best VueJS modal library out there.

**Comment by embluk** [comment]
@gabskoro I have been facing the same issues, any chance you could explain what you did to get it working?

**Comment by gabskoro** [comment]
I believe you wanted to ask @GeorgeFlorian 😅

**Comment by embluk** [comment]
Oh yeah, not sure what happened there, sorry about that 😅

**Comment by GeorgeFlorian** [comment]
@gabskoro I have forgotten. I've only used it then, almost 4 months ago and never since. I forgot what I did or how I made it work.
Just try different things, write code over and over. Trial and error. That's how I did it.

**Comment by GeorgeFlorian** [comment]
> @gabskoro I have been facing the same issues, any chance you could explain what you did to get it working?

I have forgotten. I've only used it then, almost 4 months ago and never since. I forgot what I did or how I made it work.
Just try different things, write code over and over. Trial and error. That's how I did it.
