### ISSUE TITLE
How do you send data from Modal to Parent ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [euvl/vue-js-modal#601]
In VueJS in order to send data from child component to parent component we can use `$emit`

Child component triggers clicked event:
```
export default {
  methods: {
    onClickButton (event) {
      this.$emit('clicked', 'someValue')
    }
  }
}
```
Parent component receive clicked event:
```
<div>
  <child @clicked="onClickChild"></child>
</div>
export default {
  methods: {
    onClickChild (value) {
      console.log(value) // someValue
    }
  }
}
```

`v-on` directive captures the child components events that is emitted by $emit

But how can we do this with the Dynamic Modal ? There is nothing in the documentation or readme regarding this flow direction of data.

**The only thing that is mentioned is how to send data from Parent to Child. I need it the other way around.**

How can we do this ? @euvl

**Comment by petr-ptacek** [comment]
Hi, i do this by provide the function handler to modal via props.

```vue
export default {
  props: {
    onClicked: Function
  }
  methods: {
    onClickButton (event) {
      this.onClicked && this.onClicked(event)
    }
  }
}
```
```vue
<div>
  <child :on-clicked="onClickChild"></child>
</div>
export default {
  methods: {
    onClickChild (value) {
      console.log(value) // someValue
    }
  }
}
```
