### ISSUE TITLE
Typo in example code for static modals

### ISSUE THREAD

**Issue by Therealskythe** [euvl/vue-js-modal#606]
#### Problem: 
There is a typo in the [documentation for static modals](https://euvl.github.io/vue-js-modal/Intro.html#static-modals). Therefore the modal will not show.

It reads:
`mount () {
        this.show()
    }`

It should read:
`mounted () {
        this.show()
    }`

#### Example & screenshots:

![modal](https://user-images.githubusercontent.com/3187318/89907379-e50fbc80-dbec-11ea-825a-189cad659c1a.jpg)

> I have checked stackoverflow for solutions and 100% sure that this issue is not not related to my code.

**Comment by euvl** [comment]
Hey, if you could create a PR - would be awesome, thanks
