### ISSUE TITLE
vue-js-modal causes fail on builds, due  to directly addressing 'window'

### ISSUE THREAD

**Issue by narration-sd** [euvl/vue-js-modal#617]
#### Problem: 
This is a nice module, when used in an npm develop version of an app. 

However, if you npm build, you'll find the old 'window doesn't exist outside the browser' trap, and
your app will fail out of the webpack build.

Inside vue-js-modal, it's apparent that there are a number of calls on window.x, without the
well-known  `if typeof window !== 'unknown` protection.

#### Version:

vue-js-modal@1.3.35

#### Example & screenshots:

> I have checked stackoverflow for solutions and 100% sure that this issue is not not related to my code.

**Comment by euvl** [comment]
Hi thanks for your feedback, there is a guide in the documentation how to use it with SSR. If it is not SSR and for some reason, you don't have "window" - unfortunately, this plugin most likely not fit your use case 😄 

Thanks.
