### ISSUE TITLE
Can't find dev script?

### ISSUE THREAD

**Issue by ejpusa** [euvl/vue-js-modal#62]
Hi,  getting this error with the demo:

cd demo
Edwards-MacBook-Pro:demo edwardpotter$ npm install
Edwards-MacBook-Pro:demo edwardpotter$ npm run dev
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/Users/edwardpotter/.npm-packages/bin/npm" "run" "dev"
npm ERR! node v7.3.0
npm ERR! npm  v4.0.5

npm ERR! missing script: dev
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/edwardpotter/code/modal/demo/npm-debug.log

**Comment by euvl** [comment]
Demo contains 2 folders - `client_side_rendering` and `server_side_rendering`, you will have to run one of them.

**Comment by ejpusa** [comment]
Wow, that was easy.  Thanks!  :-)

**Comment by euvl** [comment]
No probs :)
