### ISSUE TITLE
overlay should be placed under body tag directly

### ISSUE THREAD

**Issue by yaquawa** [euvl/vue-js-modal#621]
#### Problem: 
if the container has position set to `relative`, the overlay won't be placed properly.

```html
<div style="position: relative;">
    <modal name="name"></modal>
</div>
```

**Comment by Tyler-RCSD** [comment]
In my case I resolved this by using [vue-portal](https://www.npmjs.com/package/portal-vue) to change where the modal is actually rendered.

**Comment by yaquawa** [comment]
I just created another modal component which solved the problem.

https://github.com/yaquawa/muku-ui

**Comment by rathboma** [comment]
Solution with vue-portal:

in App.vue:
```vue
<portal-target name="modals" multiple />
```

Your modal:
```vue
<portal to="modals">
  <modal>
    ...
  </modal>
</portal>

```
