### ISSUE TITLE
The modal keeps bouncing up and down when adaptive is set

### ISSUE THREAD

**Issue by ever-dev** [euvl/vue-js-modal#624]
#### Problem: 

The modal keeps bouncing up and down when the modal height is bigger than screen height and `adaptive` is set to `true`.
It works fine when `adaptive` is `false` and `scrollable` is set to `true`.

#### Version:
^2.0.0-rc.6

> I have checked stackoverflow for solutions and 100% sure that this issue is not related to my code.

**Comment by fervailanti** [comment]
+1 here.
