### ISSUE TITLE
vue-js-modal@2.0.0-rc.6" has incorrect peer dependency "vue@2.6.11"

### ISSUE THREAD

**Issue by simonschaufi** [euvl/vue-js-modal#625]
#### Problem: 

I executed `yarn upgrade` and got the following warning:

`warning " > vue-js-modal@2.0.0-rc.6" has incorrect peer dependency "vue@2.6.11".`

#### Version:

vue-js-modal@2.0.0-rc.6
vue@2.6.12

**Comment by euvl** [comment]
why is it incorrect?

**Comment by simonschaufi** [comment]
my expectation is that it is using `"vue": "^2.6.11",` instead of `"vue": "2.6.11",` (note the `^`)

**Comment by simonschaufi** [comment]
Ping

**Comment by simonschaufi** [comment]
ping

**Comment by simonschaufi** [comment]
@euvl Could you please make a new release to finally get rid of this error?

**Comment by noonanwebgroup** [comment]
@euvl If you could make a new release that would be great. It's currently preventing us from using other packages which depend on Vue 2.6.12

**Comment by Vincently92** [comment]
> @euvl If you could make a new release that would be great. It's currently preventing us from using other packages which depend on Vue 2.6.12. Thank you!

can you solve it?

**Comment by noonanwebgroup** [comment]
@Vincently92 no, @newsrw has already provided a fix and it has been merged. Just awaiting a new release.

**Comment by Vincently92** [comment]
> @Vincently92 no, @newsrw has already provided a fix and it has been merged. Just awaiting a new release.

how, then, to use this plugin?

**Comment by seancolsen** [comment]
@euvl I would love to see a release so that I can install vue-js-modal in my Nuxt app
