### ISSUE TITLE
Unexpected offset, when 'width' and 'height' set to '100%'

### ISSUE THREAD

**Issue by bicstone** [euvl/vue-js-modal#637]
#### Problem: 
Unexpected offset, when 'width' and 'height' set to '100%'.
Only on mobile.

#### Version:
2.0.0-rc.6

#### Example & screenshots:
https://g0lce.sse.codesandbox.io/

Screenshot: 
<img src="https://user-images.githubusercontent.com/47806818/97081467-9a271200-163d-11eb-964f-46443a4aa204.png" width="300px">

Unexpected offset: `left: 2px;`

I have checked stackoverflow for solutions and 100% sure that this issue is not not related to my code.

**Comment by bicstone** [comment]
![image](https://user-images.githubusercontent.com/47806818/97081747-72d14480-163f-11eb-8814-a49a22821401.png)

**Comment by dhritzkiv** [comment]
I also experience this (in the v1 branch), where my 'left' offset is 5px. This only happens at specific widths (not necessarily related to breakpoints). For example, for me this occurs when the window is at 928px wide, 954px wide, 962px wide, but not in between those pixel widths.

**Comment by vintagesucks** [comment]
In one of our projects this was solved by setting [`shiftX`](https://euvl.github.io/vue-js-modal/Properties.html#shiftx-number-between-0-and-1-0-default-0-5) to `0`.

```js
:shift-x="0"
```

**Comment by bicstone** [comment]
I am closing this issue as this repository looks like it is already no longer maintained. Please clone this issue if necessary.
Have a great new year!
