### ISSUE TITLE
Does it support nesting?

### ISSUE THREAD

**Issue by shelart** [euvl/vue-js-modal#64]
Hi,

Can I open a modal over another open modal? E.g. is it possible to open editor in a modal & a dialog prompting to save changes over the editor?

**Comment by euvl** [comment]
Hey @shelart, 

I don't think I ever tried that 😄. I can check a bit later or you can play with it and raise an issue if it does not work.

**Comment by kdekooter** [comment]
Very curious about the answer! Can it be done?

**Comment by euvl** [comment]
yes if you use dynamic modals
