### ISSUE TITLE
Custom event in dynamic modal

### ISSUE THREAD

**Issue by Pochwar** [euvl/vue-js-modal#641]
#### Problem: 
How to use custom event in dynamic modal?

#### Example & screenshots:

I want to display a component in a modal, and the component emits a custom event when I click on a button (`<button @click="$emit('custom-event')">Emit Event</button>`).

I found how to retrieve this custom event when implementing ta static modal :
```
<modal
    name="example-modal"
>
    <ExampleModal
        text="some text for component props"
        @custom-event="customMethod()" // here, this works fine
    />
</modal>
```
But I want to do the same with a dynamic modal, and I don't find how to implement it.
I tried  these different things :

```
this.$modal.show(
    ExampleModal,
    {
        text: 'some text for component props',
        'custom-event': this.customMethod(), // doesn't work
        '@custom-event': this.customMethod(), // doesn't work
    },
    {
        name: 'example-modal'
    },
    {
        'custom-event': this.customMethod(), // doesn't work
    },
);
```

Is this even possible?

Any help would be appreciated :)

**Comment by fateme572** [comment]
I have the same problem

**Comment by bicstone** [comment]
duplicate of #192

**Comment by antek-drzewiecki** [comment]
My workaround - maybe a hack - was to use the build in events from `vue-js-modal`.
I use vue class components  so my example will be using them. 

first create a custom component
```
// no <modal /> is needed
<template>
  <button @click="onEvent"/>
  <button @click="onEventFail"/>
</template>
<script>
@Component
export default class ExampleModal extends Vue {

  onEvent(){
    this.$emit("close", true);
  }
  onEventFail(){
    this.$emit("close", false);
  }
}
</script>
```

Then in your main function you can use:

```
this.$modal.show(
    ExampleModal,
    {
        text: 'some text for component props',     
    },
    {
        name: 'example-modal'
    },
    {
        'before-close': (params) => { console.log("this works! ", params.params); 
    },
);
```

I managed to extract the parameters from the before-close event...
It does not fit all usecases, but i hope it does yours..
