### ISSUE TITLE
Compatibility with vuejs3 ?

### ISSUE THREAD

**Issue by sergeynilov** [euvl/vue-js-modal#642]
Hello,
Are there compatibility of vue-js-modal with vuejs3 ?

Thanks!

**Comment by sergeynilov** [comment]
I found declared 2.0.0-rc.X version. Is it for  vuejs3 ?

**Comment by mtlehtin** [comment]
There is no Vue 3 support yet.

There are already couple of issues related to this matter:

- https://github.com/euvl/vue-js-modal/issues/626
- https://github.com/euvl/vue-js-modal/issues/586
