### ISSUE TITLE
Please tell me how to enable the "Dynamic Modal" function. ver1.3.34

### ISSUE THREAD

**Issue by quick919** [euvl/vue-js-modal#646]
#### Problem: 

$modal() received object as a first argument, but dynamic modals are switched off.

I've checked the documentation, but I don't know how to enable the "dynamic modal" feature.

I know that in 2.0.0 rc, it is not necessary to turn on the "dynamic modal" function.
It didn't work in 2.0.0rc, so I want to check it in the stable version.

#### Version:
1.3.34

**Comment by samuelduann** [comment]
import VModal from 'vue-js-modal'

Vue.use(VModal, {dynamic: true})

**Comment by quick919** [comment]
Thank you very much.

In my environment, `[vue-js-modal] In order to render dynamic modals, a <modals-container> component must be present on the page.`
I got a warning.

`Vue.use (VModal, {dynamic: true, injectModalsContainer: true});`

After changing to, the modal started normally.

This isuue closes.
