### ISSUE TITLE
Opacity transitions not working on the overlay

### ISSUE THREAD

**Issue by adampbragg** [euvl/vue-js-modal#647]
#### Problem: 
Opacity transitions not working on the overlay. Other transitions do work, just not opacity. The result is the same with or without the opacity transition as the default overlay styles. Applying the same transition to the modal results in a fade-in like what we should be seeing here with the overlay.

#### Version:
2.0.0-rc.6

####
Using the following css:

```
  .curtain-enter,
  .curtain-leave-to {
    opacity: 0;
  }

  .curtain-enter-active,
  .curtain-leave-active {
    transition: all 2s;
  }
```
With the following instantiation:
```
this.$modal.show(Experience, { config }, { name: 'ExperienceRating', overlayTransition: 'curtain' });
```

**Comment by euvl** [comment]
Strange, maybe it is because overlay has it's own opacity?
