### ISSUE TITLE
Missing required prop: "open"

### ISSUE THREAD

**Issue by fyzbh** [euvl/vue-js-modal#651]
#### Problem: 
Error when using the modal with our existing Nuxt js project

```
[Vue warn]: Missing required prop: "open"

found in

---> <Modal> at components/base/Modal/Modal.vue
```

I have used this plugin to show modals with multiple plugins with the same tech stack, recently I tried adding in a nuxt project, I keep getting this error which I have never face in other projects actually. 

Can someone please help us on what exactly this is?

I just tried adding a prop called `:open=true` to see anything happens, this error is still thrown and the modal is not opened.

#### Example & screenshots:

![image](https://user-images.githubusercontent.com/76206394/102601415-24738a00-4146-11eb-9182-1f71d42766fb.png)

> I have checked stackoverflow for solutions and 100% sure that this issue is not not related to my code.

**Comment by euvl** [comment]
Hey, there is no `open` prop in the modal, https://github.com/euvl/vue-js-modal/blob/2682950e4f9ad37b50d0c4bff0a009856df0be9a/src/components/Modal.vue

**Comment by fyzbh** [comment]
@euvl Yes, that's what my issue is, there is no prop required to use the modal, and yet it fails to render throwing a error asking for a prop called `open`.
