### ISSUE TITLE
Impossible de scroll more (up / down)

### ISSUE THREAD

**Issue by HamzaInPerth** [euvl/vue-js-modal#655]
#### Problem: 

After the modal got trigger, I'm able to scroll down once, but then I won't be able to scroll more down or back to top.

#### Version:
    "vue-js-modal": "^2.0.0-rc.6"

I use firefox developer edition

#### Example & screenshots:

```
        this.$modal.show(
          modalLog,
          {
            data: data,
          },
          { height: "auto", scrollable: true }
        );
```

> I have checked stackoverflow for solutions and 100% sure that this issue is not not related to my code.

**Comment by HamzaInPerth** [comment]
All good. That was a CSS library issue.

**Comment by fervailanti** [comment]
@HamzaInPerth Hi! I'm facing the same issue. How did you solve it?

**Comment by HamzaInPerth** [comment]
I use another lib, it wasn't a CSS issue finally. use : vue-modal

**Comment by fervailanti** [comment]
Oh! I imagined that. That is a serious issue with the scroll there...

Do you mean **[this](https://github.com/wizardpisces/vue-modal)** vue-modal?

Thanks!
