### ISSUE TITLE
Passing values to my new modal window from firebase

### ISSUE THREAD

**Issue by ejpusa** [euvl/vue-js-modal#67]
Making progress. Have my modal opening. Great, now need to pass a value to that window from the calling function. Can pass hard-coded values, but not unique ID's generated from firebase.

Wondering how to do that. thanks.

<img width="830" alt="screen shot 2017-08-17 at 6 46 47 pm" src="https://user-images.githubusercontent.com/1279819/29437059-99572d80-837c-11e7-8a4c-dfedd68b1922.png">

**Comment by euvl** [comment]
Hi @ejpusa, if the modal works, and it renders 1234.. , then the problem is in your id retrieving function (not in the modal). Not sure how i can help you with it.

Thanks.

**Comment by ejpusa** [comment]
Can access my value from firebase in the "beforeCreate."  Where I'm stuck is passing that value so it replaces the '12345678''

      export default {
      name: 'edit',
      beforeCreate() {
        const id = this.$route.params.id
        console.log('ID: ', id)
      },

Thinking need to bind id to the "thing" representing the "value" of foo. That way, when click into creating modal code, code in modal has access to my passed firebase key.

 "id", "this.id" are not accessible in the html. That's where I'm stuck right now.

**Comment by ejpusa** [comment]
Got it.  

  <div style="margin-top: 20px; margin-bottom: 15px;">
        <button id="login-btn" class="btn btn-primary" v-on:click="showModal()">
          Upload photo
        </button>
      </div>

       and showModal()

       showModal: function () {
          this.$modal.show('login', { foo: this.$route.params.id })
        }

       That will pass the key  ( this.$route.params.id ) to my firebase record to the modal. I'm using it there to prefix the file name with the key. Making it easy to retrieve an image attached to a record created.

**Comment by euvl** [comment]
Awesome, nice work! 👍
