### ISSUE TITLE
Anonymous component in vue dev tool

### ISSUE THREAD

**Issue by AmirRezaM75** [euvl/vue-js-modal#678]
#### Problem: 

I don't know why but my modal renders outside of my vue root element (#app).
every functionality woks fine.

#### Code:

Here is my setup:
app.js
```
Vue.use(VueJSModal, {
    dynamicDefaults: {
        height: "auto",
        adaptive: true
    }
});
```
How I call it:
```
this.$modal.show(ReplyModal,{}, { name: "create-reply"});
```
ReplyModal.vue

```

<template>
    <div class="v--modal-box v--modal conversation-modal">
        // my content
    </div>
</template>

<script>

export default {
    name: "ReplyModal",
    props: ['reply'],
    //reset of code
```

#### Version:
``"vue-js-modal": "^2.0.0-rc.6",``

#### screenshots:
![Screenshot from 2021-04-01 10-40-49](https://user-images.githubusercontent.com/20792176/113251667-ec98e880-92d7-11eb-9794-5e71e9c76309.png)
![Screenshot from 2021-04-01 10-41-26](https://user-images.githubusercontent.com/20792176/113251679-f0c50600-92d7-11eb-8a96-80b44ee968a1.png)

Is there any misconfiguration?

**Comment by AmirRezaM75** [comment]
I wasn't declare ``<modals-container/>`` in my master page

**Comment by rudolfbruder** [comment]
@AmirRezaM75 How did you added to the master page (layout). We are using laravel and it is creating second vue app for us in the dev tools. Thanks
