### ISSUE TITLE
Set Modal's name dynamically

### ISSUE THREAD

**Issue by hys7756** [euvl/vue-js-modal#68]
Hi, I'm a beginner in vue.js and happy to meet your modal :)

I want to set modal's name dynamically.
It meas, when I define modal, pass modal's name.
And in modal component, get modal's name and set it.

I want to make it like this code.
```
// in modal use component
var modalName = 'aModal';
this.$modal.show(modalName, {});
```

```
// in modal component
<template>
  <modal v-bind:name="modalName" .. />
</template>

<script>
export default {
  data() {
   return {
     modalName: ''
   }
 }
}

...

</script>

```

thanks :)

**Comment by euvl** [comment]
Hi @hys7756, and what stops you from doing this ? 😄

**Comment by euvl** [comment]
Just keep in mind that name is unique identifier for modals and setting it dynamically does not have much sense. If you want to show different content based on your internal application state you can either use vuex or just simply pass parameters to the modal when you do $show.
