### ISSUE TITLE
Can't make the dialog appear

### ISSUE THREAD

**Issue by jaryroxas** [euvl/vue-js-modal#69]
Already set the dialog to true but nothing happens
`Vue.use(VModal, { dialog: true });`

Added this on the template
`</Dialog>` - tried `</dialog>` as well

method
```
methods: {
    test: function () {
      this.$modal.show('dialog', {
        title: 'Alert!',
        text: 'You are too awesome',
        buttons: [
          { title: 'Deal with it' },
          { title: 'Close' }
        ]
      });
    }
  }

```

**Comment by euvl** [comment]
Hey @jaryroxas. You are putting a **closing** tag  - the one that starts with / (`< / dialog>`). You have to use either opening and closing tag (`<dialog></dialog>`) or "empty" tag (`<dialog/>`)

Read more here: https://www.tutorialspoint.com/xml/xml_tags.htm

**Comment by jaryroxas** [comment]
Hi @euvl thanks for your reply ! :) forgot to mention i tried those as well but not working either, only the regular modal `<modal name=""></modal>` works

**Comment by euvl** [comment]
That is weird, can you please run the examples from the demo folder? Wondering if it will work for you.

**Comment by jaryroxas** [comment]
ok after reading the plugin code it should be <v-dialog/> not <dialog/> :) works now

**Comment by euvl** [comment]
Awesome, thanks! i will change it in the docs, completely forgot about the change 👍
