### ISSUE TITLE
Disable page scrolling on scrollable="true"

### ISSUE THREAD

**Issue by freearhey** [euvl/vue-js-modal#71]
Disable scroll the page when modal window is open and the option scrollable is enabled.

**Comment by coolemur** [comment]
👍  Up. I need to disable page (background) scrolling too, when modal window is scrolled.

**Comment by euvl** [comment]
Hey @coolemur, @freearhey 

You might want to add/remove `overflow:hidden` to your body for now, when you show/hide a modal. I do not think that adding such a side effect to the plugin (modifying <body/>) is good. I will think over a way to make it right, but again, its 2 lines of code for you guys....

**Comment by coolemur** [comment]
@euvl Hi. This could be in documentation that you might want to add overflow:hidden to body after opening a modal and remove it after closing a modal. :) Looks like this might work for me. Thank you.

**Comment by freearhey** [comment]
@euvl Yes, I understand that you can do it outside the plugin, I just think this is a predictable behavior, especially when the scrollable option is enabled. And there is no need to change `body` directly, you can simply add a separate class (e.g. `modal-open`) to `body` as is done in bootstrap by default (https://getbootstrap.com/docs/4.0/components/modal/#usage)

**Comment by euvl** [comment]
Yeah, you are right, ill add a class, probs on these or next weekends 👍

**Comment by euvl** [comment]
Hey @freearhey, @coolemur, 

Change published in `v1.2.10`, let me know if it works for you.

**Comment by alexbleon** [comment]
Hey @euvl , thanks for fix scroll for component. It work but only for follow type of usage:
`Vue.use(VModal, { componentName: "foo-modal" })
...
<foo-modal name="bar"></foo-modal>`
and not work for [Dialog](https://github.com/euvl/vue-js-modal#dialog) and for [Dynamic Modals](https://github.com/euvl/vue-js-modal#dynamic-modals). Whould you lke to fix it?
