### ISSUE TITLE
clickToClose does not work on iOS Safari

### ISSUE THREAD

**Issue by moroya** [euvl/vue-js-modal#72]
When using the clickToClose option on a touch device such as a smartphone, the dialog will not be closed because mousedown event will not fire.

https://github.com/euvl/vue-js-modal/blob/0a9cbb037a51e543df52e6988f90576d327ab53a/src/Modal.vue#L8

Can I change this event from mousedown to click?

**Comment by euvl** [comment]
Hey @moroya,
Yeah it should catch touch events as well.

**Comment by moroya** [comment]
It worked! Thank you.

**Comment by euvl** [comment]
Thanks, published in v1.2.9

**Comment by ianengelbrecht** [comment]
Sorry to ask a silly question, but how do I pass false to clickToClose? I've tried clickToClose="false" and clickToClose=false. Neither is working. This is in Chrome.
