### ISSUE TITLE
Dialog: clickToClose should be false by default or configurable

### ISSUE THREAD

**Issue by alex3683** [euvl/vue-js-modal#76]
When presenting a dialog to a user, he has to choose from a set of given options. Being able to click the background to close the dialog in most cases makes no sense (at least in my opinion and use cases ;-) ). Another problem is, that I'm not able to attach a background-click-handler to cover that case. So I'd propose to either make this configurable (just like it is for a normal modal) or set it to `false` for dialogs.

**Comment by euvl** [comment]
Hi @alex3683,

Sorry that it takes me so long to reply, i think you are right, and making `clickToClose`, `width` and some other parameters configurable (not all of them though) would be a good idea.

I will be able to spend some time on it on the next weekends. Also, if you feel like you could do it, I will be happy to accept a PR. 

Thanks.

**Comment by euvl** [comment]
hey @alex3683, 

i've added this feature, will be published in next version 👍

**Comment by alex3683** [comment]
Cool, thanks. Would have liked to do it as PR, but you surely know the problem of limited time ;-)

**Comment by euvl** [comment]
Absolutely, took me 20 days to add 5 lines of code >_____________<
