### ISSUE TITLE
scrollable true don't let me write on inputs

### ISSUE THREAD

**Issue by Caxinaswin** [euvl/vue-js-modal#78]
Hey guys, when i set scrollable true in my modal, i can't change the inputs that are inside, dunno what is the issue, any help with that?

    [  <modal :adaptive="true" height="70%"  width="60%" :resizable="true" :draggable="true" class="modalSize" name="modalSection" @closed="checkClose">
        <span class="cross" @click="$modal.hide('modalSection')">
          ✖
        </span>
        <component :is="getView">
        </component>
      </modal>](url)

**Comment by euvl** [comment]
Hey @Caxinaswin 

It is actually `:draggable="true"` that blocks your inputs. `true` makes all your modal draggable (including every element on it).

You can set draggable with string (`:draggable=".handler"`) where `.handler` is a class of some element that will be responsible for dragging.

More here: https://github.com/euvl/vue-js-modal#draggable-handler
Let me know if it fixes your issue and thanks for using the plugin! 👍 😄

**Comment by Caxinaswin** [comment]
well feels ok, but is there a way i can handle the class to just move the background? because all my inputs are inside the modal i can't just say drag all the background except the inputs, any help? thank you!

**Comment by euvl** [comment]
Sorry, but you will have to come up with solution. You might have a some background element or make a header that is responsible for drugging.
