### ISSUE TITLE
could you suppor the  title name by Properties or slot, and the close button by Properties

### ISSUE THREAD

**Issue by ansn001** [euvl/vue-js-modal#79]
I  always have to put the title and close button into template.
could you support the default to deal with this?
thanks a lot .

**Comment by euvl** [comment]
Hey, you will have to creat a wrapper component that has title and close button, something like HoC in react. Plugin just gives you a tool to create a modal, customisation is up to you 👍👌😁

**Comment by ansn001** [comment]
thanks
