### ISSUE TITLE
how to slove the nested modal?

### ISSUE THREAD

**Issue by ansn001** [euvl/vue-js-modal#80]
Now,it doesn't append to the body。
They are not directly related. I have to hide them by nested.
![image](https://user-images.githubusercontent.com/6737296/30238617-d7de82e4-957c-11e7-9701-1b17c20d20d9.png)

**Comment by euvl** [comment]
Hey @ansn001, I didn't try using nested modals. Did you manage to sort out your issue?

**Comment by ansn001** [comment]
i slove it simplete  by dynamic create component and append it to body when showing the modal. Then i just show or hide by the name
