### ISSUE TITLE
Error: Cannot find module 'vue-hot-reload-api'

### ISSUE THREAD

**Issue by arve0** [euvl/vue-js-modal#82]
Hi!
I get two errors when using `browserify src/index.js -o index.js`:

```
Error: Cannot find module 'vue-hot-reload-api' from 'node_modules/vue-js-modal/dist'
Error: Cannot find module '!!../node_modules/css-loader/index.js?sourceMap!../node_modules/vue-loader/lib/style-rewriter.js?id=data-v-18cd6db4!../node_modules/vue-loader/lib/selector.js?type=styles&index=0!./Dialog.vue' from 'node_modules/vue-js-modal/dist'
```

I use the plugin like this:
```js
const Vue = require('vue')
const { VModal } = require('vue-js-modal')

Vue.use(VModal, { dialog: true })
```

Do I need webpack to use this plugin?

**Comment by euvl** [comment]
Hey @arve0,
I did not do tests with browserify as I do not have enough bandwidth (time-wise) for it :(

**Comment by arve0** [comment]
OK. I just tried/migrated to poi/webpack and it works as it should. 

I can add a PR with a comment about browserify in the README.

**Comment by euvl** [comment]
Sure, please do. I would rather fix it for browserify, but I am not sure how tbh.

**Comment by arve0** [comment]
OK, so the issue seems to be that [vue-loader](https://github.com/vuejs/vue-loader) adds this snippet

```js
/* hot reload */
if (false) {(function () {
  var hotAPI = require("vue-hot-reload-api")
  hotAPI.install(require("vue"), false)
  if (!hotAPI.compatible) return
  module.hot.accept()
  if (!module.hot.data) {
    hotAPI.createRecord("data-v-18cd6db4", Component.options)
  } else {
    hotAPI.reload("data-v-18cd6db4", Component.options)
  }
  module.hot.dispose(function (data) {
    disposed = true
  })
})()}
```

to the bundle. I've looked around in the documentation for vue-loader, but have not found a way to turn it of.

One could enable production build (`webpack -p`) or [enable UglifyJS](https://github.com/euvl/vue-js-modal/blob/master/build/webpack.base.config.js#L38) to remove this dead code (`if (false)`).

For example, readable code, but not equal as source:
```js
  plugins: [
    new UglifyJSPlugin({
      mangle: false,
      beautify: true
    })
  ]
```

Complete minify, but with source map:
```js
  plugins: [
    new UglifyJSPlugin({
      sourceMap: true
    })
  ]
```

What do you think?

**Comment by euvl** [comment]
Wow thanks, its very extensive research you've done.  I did not know about `webpack -p` - will try it out tonight/tomorrow.

About `uglify`, I did not want to uglify the dist, but if it will fix the issue than surely it is a good approach too.

**Comment by arve0** [comment]
If you do not want to uglify, tweaking the [parameters of Uglify](https://github.com/webpack-contrib/uglifyjs-webpack-plugin#uglifyoptions) is your best bet (ironically). `-p` will uglify (mangle and optimize).

**Comment by euvl** [comment]
If i understood you right, 

```
  plugins: [
    new UglifyJSPlugin({
      mangle: false,
      beautify: true
    })
  ]
```

Should do the job?

**Comment by arve0** [comment]
Yes.

**Comment by euvl** [comment]
Awesome, I've added a change to `v1.2.11` 👍
