### ISSUE TITLE
dialog with input bound with v-model

### ISSUE THREAD

**Issue by arve0** [euvl/vue-js-modal#83]
I use the modal like this:

```js
const app = new Vue({
  el: '#container',
  data: {
    name: 'a name for this...'
  },
  methods: {
    save: function () {
      this.$modal.show('dialog', {
        title: 'Choose a name',
        text: '<input v-model=name>',
        buttons: [
          { title: 'Save', handler: () => {
            console.log('saving to ' + this.name)
            this.$modal.hide('dialog')
          } }
        ]
      })
    }
  }
})
```

```html
<button id="save" v-on:click="save"><img src="save.svg"> Save</button>
```

When a user presses the button, the dialog should show with the input. Is this possible? Currently I can not get `this.name` bound to the input. 

Should I rather use `<v-modal name=asdf><input v-model=name></v-modal>` in the HTML and to `this.modal.show('asdf')`?

**Comment by euvl** [comment]
Hey @arve0, you will have to use modal itself. Dialog is a very basic wrapper for simple things. I made it just to show how one can easily create such wrapper but it appeared to be useful 😄 😄 

You can try just copying the source of dialog and tweak it sit would fit your needs.
Also I dont think that `v-htm`l will render `..v-model=name>` as expected.

**Comment by euvl** [comment]
Alternatively you could pass your input with id `<input id="woooot">` and then just do vanilla js 

```
document.querySelector('input#woooot').value
```

On modal close event.

**Comment by arve0** [comment]
I did copy it, this it what I have so far:

```html
    <modal name="saveDialog" classes="v--modal vue-dialog" height="auto" pivotY=0.3>
      <div class="dialog-content">
        <div class="dialog-c-title">Choose a name</div>
        <div class="dialog-c-text"><input v-model="name"></div>
      </div>
      <div class="dialog-buttons">
        <button style="flex: 1 1 100%;">Save</button>
      </div> <!---->
    </modal>
```

Btw, I cannot get the `pivotY` attribute to work. Opening the Vue Dev Console, it says that it is `0.5`.

I've tried
- `pivotY=0.3`
- `pivotY="0.3"`
- `:pivotY=0.3`
- `:pivotY="0.3"`

Also, the README states this code:

```js
<modal name="example"
  :width="300"
  :height="300"
```

Reading up on the Vue doc, [it states](https://vuejs.org/v2/guide/syntax.html#v-bind-Shorthand) that `:attribute=name` is a shorthand for `v-bind:attribute=name`. Does `:width="300"` make sense, binding to an immutable number?

**Comment by euvl** [comment]
re pivot:

it will be `:pivot-y="0.3"`, camelcase is transformed into kebabcase.

**Comment by euvl** [comment]
re numbers:

I see no reason why not, it is just a property. The reason it is binded (e.g. thourhg v-bind) is because otherwise property would be considered to be string type.

**Comment by arve0** [comment]
Hm, OK. I'm new to Vue, so that was not obvious to me. Thanks.

**Comment by euvl** [comment]
No probs, let me know if you will have any other issues, im happy to help.
