### ISSUE TITLE
pivotX does not work for bodies with clientWidth below window.innerWidth

### ISSUE THREAD

**Issue by arve0** [euvl/vue-js-modal#84]
To calculate `this.left` you use [`document.body.clientWidth`](https://github.com/euvl/vue-js-modal/blob/master/src/Modal.vue#L335), which gives some funny effects when body width is not equal to window width.

Here with `:pivot-x=0.5`
![pivotx 0 5](https://user-images.githubusercontent.com/4810521/30346624-aa253d72-9809-11e7-8e7e-563d8038144c.gif)

**Comment by euvl** [comment]
Lol, this is weird, will take a look, thanks 😄

**Comment by arve0** [comment]
Here is a contrived example for your tests:

```html
<html>
<head>
  <style>
    html {
      background-color: white;
    }
    body {
      width: 20%;
      margin-left: auto;
      margin-right: auto;
      background-color: lightgreen;
    }
  </style>
</head>
<body>
</body>
</html>
```
