### ISSUE TITLE
Fullscreen Modal

### ISSUE THREAD

**Issue by dscummings** [euvl/vue-js-modal#85]
Defining the width at 100% is leaving an 80px margin down the right edge of the screen for me. 

The top right 'close' slot sits correctly in the top right corner of the browser, but the modal background doesn't quite reach then end.

I don't believe any other CSS is affecting these elements. Is this a known issue? Any suggestions on how to correct this?

**Comment by euvl** [comment]
Hey @dscummings,

Can you try 

```
<modal name="test"
         :adaptive="true"
         width="100%"
         height="100%">...</modal>
```

pls

**Comment by dscummings** [comment]
@euvl Thanks euvl. That's what I was using but it turns out something else affecting the width after all (sorry, amateur hour over here : ) 

All good now. Nice plugin!

**Comment by euvl** [comment]
Thanks! No probs:) Let me know if you will need any help 👍
