### ISSUE TITLE
conflict with bootstrap

### ISSUE THREAD

**Issue by zhujiancc** [euvl/vue-js-modal#9]
when I use  bootstrap in my project , the vue-js-modal  can't work well . it stop overlay ,but not show the modal ,

**Comment by airatkh** [comment]
I confirm this behavior

**Comment by euvl** [comment]
thanks for the issue, i think i've found the problem, i was using class name ".modal" which was also used by bootstrap, will let you know when fixed

**Comment by euvl** [comment]
@airatkh , @zhujiancc , I've changed the class name, it is in release 1.0.20.

If you could check it out  and let me know if it fixed problem for you guys - it would be very helpful 👍 😄 

Have to run, have a nice day!
