### ISSUE TITLE
Press escape key to close modal

### ISSUE THREAD

**Issue by diachedelic** [euvl/vue-js-modal#90]
It's quite difficult to support this without it being built in.

**Comment by euvl** [comment]
```
methods: {
  beforeOpen () {
    document.addEventListener('mouseup', this.close)
  },

  beforeClose () {
    document.removeEventListener('mouseup', this.close)
  },

  close (e) {
    if (e.keyCode === 27) this.$modal.hide('mymyodal') 
  }
}
```

does not look very difficult to me tbh.
p.s. didnt test, but something like this should work.

**Comment by euvl** [comment]
Also some use-cases require modals not being possible to close. For example,  authentication requests.

I think you will have to support this behaviour manually.

**Comment by diachedelic** [comment]
In that scenario, I would expect `clickToClose` === false - and that should disable the esc key, right?

It is a difficult thing to support manually because vue-js-modal does not expose an API to determine which modals, or any, are currently shown.  Upon capturing an esc key event, I don't think there's any method on `$modal` which closes all modals.

**Comment by euvl** [comment]
Interesting, is your project public, can I take a look? I did not think that showing more than one modal will actually work 😄 

Its a fair point that`clickToClose` can be responsible for ESC button, I will think about it.
Thanks

**Comment by diachedelic** [comment]
Sorry I did not mean I'm showing more than one modal at one time.  My project is not public, but here is an example:

```
<template>

  <div>
    <button @click="$modal.show('foo')">Show Foo</button>
    <button @click="$modal.show('bar')">Show Bar</button>

    <modal name="foo">Foo</modal>
    <modal name="bar">Bar</modal>
  </div>

</template>

<script>

export default {
  mounted() {
    document.body.addEventListener('keyup', e => {
      if (e.keyCode === 27) {
        this.$modal.??? // how to hide any open modal?
      }
    })
  }
}
</script>
```

**Comment by euvl** [comment]
Good point, I will add it in one of the next releases.

**Comment by euvl** [comment]
Publishing in 1.3.5

**Comment by anotherthomas** [comment]
Sorry to revive this old issue, but I wanted to create one about splitting "clickToClose" and "close by ESC". Since the coupling seems to be a design decision, is that worthwhile?

**Comment by danrocha** [comment]
One up for @anotherthomas 's issue.

One example would be: 
- I want to keep the clickToClose functionality
- I want to use ESC key events for elements within my open modal (in forms for example), and not have it close the modal whenever esc is pressed.

Or how would you do it currently?

**Comment by peterg98** [comment]
@danrocha The event being passed in through the `before-close` listener does not have the key attribute. Perhaps someone can do a pull request for this?
