### ISSUE TITLE
BeforeOpen and BeforeClose for dialog

### ISSUE THREAD

**Issue by nodirshams** [euvl/vue-js-modal#91]
Could you please answer to my question https://stackoverflow.com/questions/46417179/how-to-pass-to-vue-js-modal-dialog-beforeopen-and-beforeclose-listeners

**Comment by euvl** [comment]
Hey @nodirshams, events on `v-dialog` will work in next version. Also keep in mind that `v-dialog` is just a very simple wrapper for `modal`.

**Comment by nodirshams** [comment]
thanks for reply
