### ISSUE TITLE
Make Modal Scrollable Even in Full Screen?

### ISSUE THREAD

**Issue by codeitlikemiley** [euvl/vue-js-modal#92]
I know we can Do Full Screen, but i dont know if it is possible that we can also scroll inside the modal if the modal content exceed the height of the window

**Comment by codeitlikemiley** [comment]
Has Anyone Implemented https://bosnaufal.github.io/vue2-scrollbar/  ?
Coz i Had a FullScreen Modal , and i want the inside of a div to have a scrollbar to it...

**Comment by euvl** [comment]
you probably want a div with `overflow: auto; height: 100vh` or something inside the fullscreen modal.
