### ISSUE TITLE
[Vue warn]: Invalid prop: custom validator check failed for prop "height".

### ISSUE THREAD

**Issue by davidm-public** [euvl/vue-js-modal#95]
validator fails when height is set to `height:"calc(100vh - 100px)"`

this is unfortunate, as it's a useful work-around for the problem with setting height to auto, and setting scrollable.

**Comment by euvl** [comment]
Wow, it clearly will not work this way. You have to specify one of the values described in readme (Number, String, String with suffix or "auto")

**Comment by davidm-public** [comment]
works great for me when commenting out the following in Modal.vue:

```
  /*
        validator (value) {
          if (typeof value === 'string') {
            if (value === 'auto') {
              return true
            }

            let height = parseNumber(value)
            return (height.type === '%' || height.type === 'px') &&
              height.value > 0
          }

          return value >= 0
        }
        */
```

**Comment by euvl** [comment]
@davidm-public so fix it.
